/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentsSubtasksQueryParams, StudentsSubtasks200, StudentsSubtasks422, StudentsSubtasksQueryResponse } from "../../types/StudentsSubtasks/StudentsSubtasks.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { sortableFieldsSchema } from "../sortableFieldsSchema.ts";
import { sortDirectionSchema } from "../sortDirectionSchema.ts";
import { studentTaskReadSchema } from "../studentTaskReadSchema.ts";
import { z } from "zod";

export const studentsSubtasksQueryParamsSchema = z.object({
    "student_task_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"student_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"sub_task_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"task_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"subject_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"variant_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"completion_status": z.optional(z.union([z.string(), z.null()])),
"search": z.optional(z.union([z.string(), z.null()])),
get "sort_column1"(){
                return z.optional(z.union([sortableFieldsSchema, z.null()]).default("StartDate"))
              },
get "sort_column2"(){
                return z.optional(z.union([sortableFieldsSchema, z.null()]))
              },
get "sort_direction1"(){
                return z.optional(z.union([sortDirectionSchema, z.null()]).default("ASC"))
              },
get "sort_direction2"(){
                return z.optional(z.union([sortDirectionSchema, z.null()]))
              },
"p_limit": z.optional(z.union([z.coerce.number().int(), z.null()])),
"p_offset": z.optional(z.union([z.coerce.number().int(), z.null()]))
    }) as unknown as z.ZodType<StudentsSubtasksQueryParams>

/**
 * @description Successful Response
 */
export const studentsSubtasks200Schema = z.array(studentTaskReadSchema) as unknown as z.ZodType<StudentsSubtasks200>

/**
 * @description Validation Error
 */
export const studentsSubtasks422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<StudentsSubtasks422>

export const studentsSubtasksQueryResponseSchema = studentsSubtasks200Schema as unknown as z.ZodType<StudentsSubtasksQueryResponse>