/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks200, StudentsSubtasksAssignSubtasks422, StudentsSubtasksAssignSubtasksQueryResponse } from "../../types/StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const studentsSubtasksAssignSubtasksQueryParamsSchema = z.object({
    "student_id": z.coerce.number().int(),
"subtask_id": z.coerce.number().int()
    }) as unknown as z.ZodType<StudentsSubtasksAssignSubtasksQueryParams>

/**
 * @description Successful Response
 */
export const studentsSubtasksAssignSubtasks200Schema = z.unknown() as unknown as z.ZodType<StudentsSubtasksAssignSubtasks200>

/**
 * @description Validation Error
 */
export const studentsSubtasksAssignSubtasks422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<StudentsSubtasksAssignSubtasks422>

export const studentsSubtasksAssignSubtasksQueryResponseSchema = studentsSubtasksAssignSubtasks200Schema as unknown as z.ZodType<StudentsSubtasksAssignSubtasksQueryResponse>