/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetDocumentationApiDocsGet200, GetDocumentationApiDocsGetQueryResponse } from "../../types/Default/GetDocumentationApiDocsGet.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const getDocumentationApiDocsGet200Schema = z.unknown() as unknown as z.ZodType<GetDocumentationApiDocsGet200>

export const getDocumentationApiDocsGetQueryResponseSchema = getDocumentationApiDocsGet200Schema as unknown as z.ZodType<GetDocumentationApiDocsGetQueryResponse>