/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetRedocDocumentationApiRedocGet200, GetRedocDocumentationApiRedocGetQueryResponse } from "../../types/Default/GetRedocDocumentationApiRedocGet.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const getRedocDocumentationApiRedocGet200Schema = z.unknown() as unknown as z.ZodType<GetRedocDocumentationApiRedocGet200>

export const getRedocDocumentationApiRedocGetQueryResponseSchema = getRedocDocumentationApiRedocGet200Schema as unknown as z.ZodType<GetRedocDocumentationApiRedocGetQueryResponse>