/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OpenapiApiOpenapiJsonGet200, OpenapiApiOpenapiJsonGetQueryResponse } from "../../types/Default/OpenapiApiOpenapiJsonGet.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const openapiApiOpenapiJsonGet200Schema = z.unknown() as unknown as z.ZodType<OpenapiApiOpenapiJsonGet200>

export const openapiApiOpenapiJsonGetQueryResponseSchema = openapiApiOpenapiJsonGet200Schema as unknown as z.ZodType<OpenapiApiOpenapiJsonGetQueryResponse>