/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { UserCreate } from "../UserCreate.ts";

/**
 * @description Successful Response
*/
export type AuthRegister200 = unknown;

/**
 * @description Validation Error
*/
export type AuthRegister422 = HTTPValidationError;

export type AuthRegisterMutationRequest = UserCreate;

export type AuthRegisterMutationResponse = AuthRegister200;

export type AuthRegisterMutation = {
    Response: AuthRegister200;
    Request: AuthRegisterMutationRequest;
    Errors: AuthRegister422;
};