/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface AuthConfirmEmailQueryParams {
    /**
     * @type string
    */
    token: string;
}

/**
 * @description Successful Response
*/
export type AuthConfirmEmail200 = unknown;

/**
 * @description Validation Error
*/
export type AuthConfirmEmail422 = HTTPValidationError;

export type AuthConfirmEmailQueryResponse = AuthConfirmEmail200;

export type AuthConfirmEmailQuery = {
    Response: AuthConfirmEmail200;
    QueryParams: AuthConfirmEmailQueryParams;
    Errors: AuthConfirmEmail422;
};