/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type AuthLogout200 = unknown;

export type AuthLogoutMutationResponse = AuthLogout200;

export type AuthLogoutMutation = {
    Response: AuthLogout200;
    Errors: any;
};