/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { PasswordReset } from "../PasswordReset.ts";

/**
 * @description Successful Response
*/
export type AuthPasswordReset200 = unknown;

/**
 * @description Validation Error
*/
export type AuthPasswordReset422 = HTTPValidationError;

export type AuthPasswordResetMutationRequest = PasswordReset;

export type AuthPasswordResetMutationResponse = AuthPasswordReset200;

export type AuthPasswordResetMutation = {
    Response: AuthPasswordReset200;
    Request: AuthPasswordResetMutationRequest;
    Errors: AuthPasswordReset422;
};