/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { PasswordResetConfirm } from "../PasswordResetConfirm.ts";

/**
 * @description Successful Response
*/
export type AuthPasswordResetWithToken200 = unknown;

/**
 * @description Validation Error
*/
export type AuthPasswordResetWithToken422 = HTTPValidationError;

export type AuthPasswordResetWithTokenMutationRequest = PasswordResetConfirm;

export type AuthPasswordResetWithTokenMutationResponse = AuthPasswordResetWithToken200;

export type AuthPasswordResetWithTokenMutation = {
    Response: AuthPasswordResetWithToken200;
    Request: AuthPasswordResetWithTokenMutationRequest;
    Errors: AuthPasswordResetWithToken422;
};