/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthRequest } from "../AuthRequest.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { TokenWithStudent } from "../TokenWithStudent.ts";

/**
 * @description Successful Response
*/
export type AuthLogin200 = TokenWithStudent;

/**
 * @description Validation Error
*/
export type AuthLogin422 = HTTPValidationError;

export type AuthLoginMutationRequest = AuthRequest;

export type AuthLoginMutationResponse = AuthLogin200;

export type AuthLoginMutation = {
    Response: AuthLogin200;
    Request: AuthLoginMutationRequest;
    Errors: AuthLogin422;
};