/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentOut } from "../StudentOut.ts";

/**
 * @description Successful Response
*/
export type AuthCheckToken200 = StudentOut;

export type AuthCheckTokenQueryResponse = AuthCheckToken200;

export type AuthCheckTokenQuery = {
    Response: AuthCheckToken200;
    Errors: any;
};