/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangePasswordRequest } from "../ChangePasswordRequest.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";

/**
 * @description Successful Response
*/
export type AuthChangePassword200 = unknown;

/**
 * @description Validation Error
*/
export type AuthChangePassword422 = HTTPValidationError;

export type AuthChangePasswordMutationRequest = ChangePasswordRequest;

export type AuthChangePasswordMutationResponse = AuthChangePassword200;

export type AuthChangePasswordMutation = {
    Response: AuthChangePassword200;
    Request: AuthChangePasswordMutationRequest;
    Errors: AuthChangePassword422;
};