/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminChangePasswordRequest } from "../AdminChangePasswordRequest.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams {
    /**
     * @type integer
    */
    student_id: number;
}

/**
 * @description Successful Response
*/
export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200 = unknown;

/**
 * @description Validation Error
*/
export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422 = HTTPValidationError;

export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest = AdminChangePasswordRequest;

export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse = AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200;

export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutation = {
    Response: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200;
    Request: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest;
    PathParams: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams;
    Errors: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422;
};