/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams {
    /**
     * @type integer
    */
    studentID: number;
}

export interface AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams {
    /**
     * @type integer
    */
    RoleID: number;
}

/**
 * @description Successful Response
*/
export type AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200 = unknown;

/**
 * @description Validation Error
*/
export type AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422 = HTTPValidationError;

export type AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse = AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200;

export type AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutation = {
    Response: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200;
    PathParams: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams;
    QueryParams: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams;
    Errors: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422;
};