/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignPermissionsRequest } from "../AssignPermissionsRequest.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams {
    /**
     * @type integer
    */
    role_id: number;
}

/**
 * @description Successful Response
*/
export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200 = unknown;

/**
 * @description Validation Error
*/
export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422 = HTTPValidationError;

export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest = AssignPermissionsRequest;

export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse = AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200;

export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutation = {
    Response: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200;
    Request: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest;
    PathParams: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams;
    Errors: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422;
};