/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface GetLogsApiAdminStudentsStudentIDLogsGetPathParams {
    /**
     * @type integer
    */
    studentID: number;
}

/**
 * @description Successful Response
*/
export type GetLogsApiAdminStudentsStudentIDLogsGet200 = unknown;

/**
 * @description Validation Error
*/
export type GetLogsApiAdminStudentsStudentIDLogsGet422 = HTTPValidationError;

export type GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse = GetLogsApiAdminStudentsStudentIDLogsGet200;

export type GetLogsApiAdminStudentsStudentIDLogsGetQuery = {
    Response: GetLogsApiAdminStudentsStudentIDLogsGet200;
    PathParams: GetLogsApiAdminStudentsStudentIDLogsGetPathParams;
    Errors: GetLogsApiAdminStudentsStudentIDLogsGet422;
};