/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface GetLogsApiAdminStudentsLogsGetQueryParams {
    /**
     * @minLength 1
     * @maxLength 10000
     * @default 50
     * @type integer | undefined
    */
    limit?: number;
    /**
     * @minLength 0
     * @default 0
     * @type integer | undefined
    */
    offset?: number;
}

/**
 * @description Successful Response
*/
export type GetLogsApiAdminStudentsLogsGet200 = unknown;

/**
 * @description Validation Error
*/
export type GetLogsApiAdminStudentsLogsGet422 = HTTPValidationError;

export type GetLogsApiAdminStudentsLogsGetQueryResponse = GetLogsApiAdminStudentsLogsGet200;

export type GetLogsApiAdminStudentsLogsGetQuery = {
    Response: GetLogsApiAdminStudentsLogsGet200;
    QueryParams: GetLogsApiAdminStudentsLogsGetQueryParams;
    Errors: GetLogsApiAdminStudentsLogsGet422;
};