/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams {
    /**
     * @type integer
    */
    role_id: number;
}

/**
 * @description Successful Response
*/
export type ReadPermissionsRoleApiAdminRolesRoleIdGet200 = unknown;

/**
 * @description Validation Error
*/
export type ReadPermissionsRoleApiAdminRolesRoleIdGet422 = HTTPValidationError;

export type ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse = ReadPermissionsRoleApiAdminRolesRoleIdGet200;

export type ReadPermissionsRoleApiAdminRolesRoleIdGetQuery = {
    Response: ReadPermissionsRoleApiAdminRolesRoleIdGet200;
    PathParams: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams;
    Errors: ReadPermissionsRoleApiAdminRolesRoleIdGet422;
};