/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Roles } from "../Roles.ts";

/**
 * @description Successful Response
*/
export type ReadRolesApiAdminRolesGet200 = Roles[];

export type ReadRolesApiAdminRolesGetQueryResponse = ReadRolesApiAdminRolesGet200;

export type ReadRolesApiAdminRolesGetQuery = {
    Response: ReadRolesApiAdminRolesGet200;
    Errors: any;
};