/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Permission } from "../Permission.ts";

/**
 * @description Successful Response
*/
export type ReadPermissionApiAdminPermissionGet200 = Permission[];

export type ReadPermissionApiAdminPermissionGetQueryResponse = ReadPermissionApiAdminPermissionGet200;

export type ReadPermissionApiAdminPermissionGetQuery = {
    Response: ReadPermissionApiAdminPermissionGet200;
    Errors: any;
};