/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentOut } from "../StudentOut.ts";

/**
 * @description Successful Response
*/
export type ReadAllStudentsApiAdminStudentsGet200 = StudentOut[];

export type ReadAllStudentsApiAdminStudentsGetQueryResponse = ReadAllStudentsApiAdminStudentsGet200;

export type ReadAllStudentsApiAdminStudentsGetQuery = {
    Response: ReadAllStudentsApiAdminStudentsGet200;
    Errors: any;
};