/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse } from "../../types/Admin/AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
import { adminChangePasswordRequestSchema } from "../adminChangePasswordRequestSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParamsSchema = z.object({
    "student_id": z.coerce.number().int()
    }) as unknown as z.ZodType<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams>

/**
 * @description Successful Response
 */
export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200Schema = z.unknown() as unknown as z.ZodType<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200>

/**
 * @description Validation Error
 */
export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>

export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequestSchema = adminChangePasswordRequestSchema as unknown as z.ZodType<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest>

export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponseSchema = adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200Schema as unknown as z.ZodType<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse>