/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse } from "../../types/Admin/AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
import { assignPermissionsRequestSchema } from "../assignPermissionsRequestSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParamsSchema = z.object({
    "role_id": z.coerce.number().int()
    }) as unknown as z.ZodType<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams>

/**
 * @description Successful Response
 */
export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200Schema = z.unknown() as unknown as z.ZodType<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200>

/**
 * @description Validation Error
 */
export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>

export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequestSchema = assignPermissionsRequestSchema as unknown as z.ZodType<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest>

export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponseSchema = assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200Schema as unknown as z.ZodType<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse>