/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse } from "../../types/Admin/AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParamsSchema = z.object({
    "studentID": z.coerce.number().int()
    }) as unknown as z.ZodType<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams>

export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParamsSchema = z.object({
    "RoleID": z.coerce.number().int()
    }) as unknown as z.ZodType<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams>

/**
 * @description Successful Response
 */
export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200Schema = z.unknown() as unknown as z.ZodType<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200>

/**
 * @description Validation Error
 */
export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>

export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponseSchema = assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200Schema as unknown as z.ZodType<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse>