/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLogsApiAdminStudentsStudentIDLogsGetPathParams, GetLogsApiAdminStudentsStudentIDLogsGet200, GetLogsApiAdminStudentsStudentIDLogsGet422, GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse } from "../../types/Admin/GetLogsApiAdminStudentsStudentIDLogsGet.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const getLogsApiAdminStudentsStudentIDLogsGetPathParamsSchema = z.object({
    "studentID": z.coerce.number().int()
    }) as unknown as z.ZodType<GetLogsApiAdminStudentsStudentIDLogsGetPathParams>

/**
 * @description Successful Response
 */
export const getLogsApiAdminStudentsStudentIDLogsGet200Schema = z.unknown() as unknown as z.ZodType<GetLogsApiAdminStudentsStudentIDLogsGet200>

/**
 * @description Validation Error
 */
export const getLogsApiAdminStudentsStudentIDLogsGet422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<GetLogsApiAdminStudentsStudentIDLogsGet422>

export const getLogsApiAdminStudentsStudentIDLogsGetQueryResponseSchema = getLogsApiAdminStudentsStudentIDLogsGet200Schema as unknown as z.ZodType<GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse>