/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetLogsApiAdminStudentsLogsGetQueryParams, GetLogsApiAdminStudentsLogsGet200, GetLogsApiAdminStudentsLogsGet422, GetLogsApiAdminStudentsLogsGetQueryResponse } from "../../types/Admin/GetLogsApiAdminStudentsLogsGet.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const getLogsApiAdminStudentsLogsGetQueryParamsSchema = z.object({
    "limit": z.optional(z.coerce.number().int().min(1).max(10000).default(50)),
"offset": z.optional(z.coerce.number().int().min(0).default(0))
    }) as unknown as z.ZodType<GetLogsApiAdminStudentsLogsGetQueryParams>

/**
 * @description Successful Response
 */
export const getLogsApiAdminStudentsLogsGet200Schema = z.unknown() as unknown as z.ZodType<GetLogsApiAdminStudentsLogsGet200>

/**
 * @description Validation Error
 */
export const getLogsApiAdminStudentsLogsGet422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<GetLogsApiAdminStudentsLogsGet422>

export const getLogsApiAdminStudentsLogsGetQueryResponseSchema = getLogsApiAdminStudentsLogsGet200Schema as unknown as z.ZodType<GetLogsApiAdminStudentsLogsGetQueryResponse>