/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReadPermissionApiAdminPermissionGet200, ReadPermissionApiAdminPermissionGetQueryResponse } from "../../types/Admin/ReadPermissionApiAdminPermissionGet.ts";
import { permissionSchema } from "../permissionSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const readPermissionApiAdminPermissionGet200Schema = z.array(permissionSchema) as unknown as z.ZodType<ReadPermissionApiAdminPermissionGet200>

export const readPermissionApiAdminPermissionGetQueryResponseSchema = readPermissionApiAdminPermissionGet200Schema as unknown as z.ZodType<ReadPermissionApiAdminPermissionGetQueryResponse>