/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams, ReadPermissionsRoleApiAdminRolesRoleIdGet200, ReadPermissionsRoleApiAdminRolesRoleIdGet422, ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse } from "../../types/Admin/ReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const readPermissionsRoleApiAdminRolesRoleIdGetPathParamsSchema = z.object({
    "role_id": z.coerce.number().int()
    }) as unknown as z.ZodType<ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams>

/**
 * @description Successful Response
 */
export const readPermissionsRoleApiAdminRolesRoleIdGet200Schema = z.unknown() as unknown as z.ZodType<ReadPermissionsRoleApiAdminRolesRoleIdGet200>

/**
 * @description Validation Error
 */
export const readPermissionsRoleApiAdminRolesRoleIdGet422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<ReadPermissionsRoleApiAdminRolesRoleIdGet422>

export const readPermissionsRoleApiAdminRolesRoleIdGetQueryResponseSchema = readPermissionsRoleApiAdminRolesRoleIdGet200Schema as unknown as z.ZodType<ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse>