/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReadAllStudentsApiAdminStudentsGet200, ReadAllStudentsApiAdminStudentsGetQueryResponse } from "../../types/Admin/ReadAllStudentsApiAdminStudentsGet.ts";
import { studentOutSchema } from "../studentOutSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const readAllStudentsApiAdminStudentsGet200Schema = z.array(studentOutSchema) as unknown as z.ZodType<ReadAllStudentsApiAdminStudentsGet200>

export const readAllStudentsApiAdminStudentsGetQueryResponseSchema = readAllStudentsApiAdminStudentsGet200Schema as unknown as z.ZodType<ReadAllStudentsApiAdminStudentsGetQueryResponse>