/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ReadRolesApiAdminRolesGet200, ReadRolesApiAdminRolesGetQueryResponse } from "../../types/Admin/ReadRolesApiAdminRolesGet.ts";
import { rolesSchema } from "../rolesSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const readRolesApiAdminRolesGet200Schema = z.array(rolesSchema) as unknown as z.ZodType<ReadRolesApiAdminRolesGet200>

export const readRolesApiAdminRolesGetQueryResponseSchema = readRolesApiAdminRolesGet200Schema as unknown as z.ZodType<ReadRolesApiAdminRolesGetQueryResponse>