/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type GetDocumentationApiDocsGet200 = unknown;

export type GetDocumentationApiDocsGetQueryResponse = GetDocumentationApiDocsGet200;

export type GetDocumentationApiDocsGetQuery = {
    Response: GetDocumentationApiDocsGet200;
    Errors: any;
};