/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type GetRedocDocumentationApiRedocGet200 = unknown;

export type GetRedocDocumentationApiRedocGetQueryResponse = GetRedocDocumentationApiRedocGet200;

export type GetRedocDocumentationApiRedocGetQuery = {
    Response: GetRedocDocumentationApiRedocGet200;
    Errors: any;
};