/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type OpenapiApiOpenapiJsonGet200 = unknown;

export type OpenapiApiOpenapiJsonGetQueryResponse = OpenapiApiOpenapiJsonGet200;

export type OpenapiApiOpenapiJsonGetQuery = {
    Response: OpenapiApiOpenapiJsonGet200;
    Errors: any;
};