/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksTaskIDQueryResponse, TasksTaskIDPathParams, TasksTaskID422 } from "../../types/Tasks/TasksTaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tasksTaskID } from "../../services/TasksService/tasksTaskID.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tasksTaskIDQueryKey = (task_id: TasksTaskIDPathParams["task_id"]) => [{ url: '/api/tasks/:task_id', params: {task_id:task_id} }] as const

export type TasksTaskIDQueryKey = ReturnType<typeof tasksTaskIDQueryKey>

export function tasksTaskIDQueryOptions(task_id: TasksTaskIDPathParams["task_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tasksTaskIDQueryKey(task_id)
  return queryOptions<TasksTaskIDQueryResponse, ResponseErrorConfig<TasksTaskID422>, TasksTaskIDQueryResponse, typeof queryKey>({
   enabled: !!(task_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tasksTaskID(task_id, config)
   },
  })
}

/**
 * @summary Получить категорию по его task_id
 * {@link /api/tasks/:task_id}
 */
export function useTasksTaskID<TData = TasksTaskIDQueryResponse, TQueryData = TasksTaskIDQueryResponse, TQueryKey extends QueryKey = TasksTaskIDQueryKey>(task_id: TasksTaskIDPathParams["task_id"], options: 
{
  query?: Partial<QueryObserverOptions<TasksTaskIDQueryResponse, ResponseErrorConfig<TasksTaskID422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tasksTaskIDQueryKey(task_id)

  const query = useQuery({
   ...tasksTaskIDQueryOptions(task_id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<TasksTaskID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}