/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksTaskIDQueryResponse, TasksTaskIDPathParams, TasksTaskID422 } from "../../types/Tasks/TasksTaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { tasksTaskID } from "../../services/TasksService/tasksTaskID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const tasksTaskIDSuspenseQueryKey = (task_id: TasksTaskIDPathParams["task_id"]) => [{ url: '/api/tasks/:task_id', params: {task_id:task_id} }] as const

export type TasksTaskIDSuspenseQueryKey = ReturnType<typeof tasksTaskIDSuspenseQueryKey>

export function tasksTaskIDSuspenseQueryOptions(task_id: TasksTaskIDPathParams["task_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tasksTaskIDSuspenseQueryKey(task_id)
  return queryOptions<TasksTaskIDQueryResponse, ResponseErrorConfig<TasksTaskID422>, TasksTaskIDQueryResponse, typeof queryKey>({
   enabled: !!(task_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tasksTaskID(task_id, config)
   },
  })
}

/**
 * @summary Получить категорию по его task_id
 * {@link /api/tasks/:task_id}
 */
export function useTasksTaskIDSuspense<TData = TasksTaskIDQueryResponse, TQueryKey extends QueryKey = TasksTaskIDSuspenseQueryKey>(task_id: TasksTaskIDPathParams["task_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<TasksTaskIDQueryResponse, ResponseErrorConfig<TasksTaskID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tasksTaskIDSuspenseQueryKey(task_id)

  const query = useSuspenseQuery({
   ...tasksTaskIDSuspenseQueryOptions(task_id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<TasksTaskID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}