/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksQueryResponse, TasksQueryParams, Tasks422 } from "../../types/Tasks/Tasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { tasks } from "../../services/TasksService/tasks.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const tasksQueryKey = (params?: TasksQueryParams) => [{ url: '/api/tasks' }, ...(params ? [params] : [])] as const

export type TasksQueryKey = ReturnType<typeof tasksQueryKey>

export function tasksQueryOptions(params?: TasksQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = tasksQueryKey(params)
  return queryOptions<TasksQueryResponse, ResponseErrorConfig<Tasks422>, TasksQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return tasks(params, config)
   },
  })
}

/**
 * @description Если передан параметр **subjectID**, то возвращаются категории только для указанного предмета.          Если параметр не передан, возвращаются категории по всем предметам.          **subjectID** передается как Query-параметр                   "`/api/tasks` — все категории"                  "`/api/tasks?subjectID=10` — категории для предмета с subject ID 10"                  так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список категорий (ЕГЭ_1 ЕГЭ_2, и т.д)
 * {@link /api/tasks}
 */
export function useTasks<TData = TasksQueryResponse, TQueryData = TasksQueryResponse, TQueryKey extends QueryKey = TasksQueryKey>(params?: TasksQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<TasksQueryResponse, ResponseErrorConfig<Tasks422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? tasksQueryKey(params)

  const query = useQuery({
   ...tasksQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Tasks422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}