/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface VariantsVariantIDPathParams {
    /**
     * @type integer
    */
    variant_id: number;
}

/**
 * @description Successful Response
*/
export type VariantsVariantID200 = unknown;

/**
 * @description Validation Error
*/
export type VariantsVariantID422 = HTTPValidationError;

export type VariantsVariantIDQueryResponse = VariantsVariantID200;

export type VariantsVariantIDQuery = {
    Response: VariantsVariantID200;
    PathParams: VariantsVariantIDPathParams;
    Errors: VariantsVariantID422;
};