/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface VariantsQueryParams {
    /**
     * @description ID предмета для фильтрации
    */
    subject_id?: (number | null);
}

/**
 * @description Successful Response
*/
export type Variants200 = unknown;

/**
 * @description Validation Error
*/
export type Variants422 = HTTPValidationError;

export type VariantsQueryResponse = Variants200;

export type VariantsQuery = {
    Response: Variants200;
    QueryParams: VariantsQueryParams;
    Errors: Variants422;
};