/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface VariantsExecVariantIDStudentIDPathParams {
    /**
     * @type integer
    */
    VariantID: number;
    /**
     * @type integer
    */
    StudentID: number;
}

/**
 * @description Successful Response
*/
export type VariantsExecVariantIDStudentID200 = unknown;

/**
 * @description Validation Error
*/
export type VariantsExecVariantIDStudentID422 = HTTPValidationError;

export type VariantsExecVariantIDStudentIDQueryResponse = VariantsExecVariantIDStudentID200;

export type VariantsExecVariantIDStudentIDQuery = {
    Response: VariantsExecVariantIDStudentID200;
    PathParams: VariantsExecVariantIDStudentIDPathParams;
    Errors: VariantsExecVariantIDStudentID422;
};