/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthPasswordResetWithTokenMutationRequest, AuthPasswordResetWithTokenMutationResponse, AuthPasswordResetWithToken422 } from "../../types/Auth/AuthPasswordResetWithToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authPasswordResetWithToken } from "../../services/AuthService/authPasswordResetWithToken.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authPasswordResetWithTokenMutationKey = () => [{ url: '/api/auth/password_reset_with_token' }] as const

export type AuthPasswordResetWithTokenMutationKey = ReturnType<typeof authPasswordResetWithTokenMutationKey>

export function authPasswordResetWithTokenMutationOptions(config: Partial<RequestConfig<AuthPasswordResetWithTokenMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = authPasswordResetWithTokenMutationKey()
  return mutationOptions<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, {data: AuthPasswordResetWithTokenMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return authPasswordResetWithToken(data, config)
    },
  })
}

/**
 * @description на один токен идет только один сброс пароля, для повторного сброса надо запрашивать новый токен
 * @summary Сброс пароля по токену
 * {@link /api/auth/password_reset_with_token}
 */
export function useAuthPasswordResetWithToken<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, {data: AuthPasswordResetWithTokenMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthPasswordResetWithTokenMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authPasswordResetWithTokenMutationKey()

  const baseOptions = authPasswordResetWithTokenMutationOptions(config) as UseMutationOptions<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, {data: AuthPasswordResetWithTokenMutationRequest}, TContext>

  return useMutation<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, {data: AuthPasswordResetWithTokenMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, {data: AuthPasswordResetWithTokenMutationRequest}, TContext>
}