/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthLoginMutationRequest, AuthLoginMutationResponse, AuthLogin422 } from "../../types/Auth/AuthLogin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authLogin } from "../../services/AuthService/authLogin.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authLoginMutationKey = () => [{ url: '/api/auth/login' }] as const

export type AuthLoginMutationKey = ReturnType<typeof authLoginMutationKey>

export function authLoginMutationOptions(config: Partial<RequestConfig<AuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = authLoginMutationKey()
  return mutationOptions<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, {data: AuthLoginMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return authLogin(data, config)
    },
  })
}

/**
 * @description Возвращает токен, тип заголовка и небольшую информацию о пользователе, если (логин / email / телефон) и пароль корректны и пользователь активен.
 * @summary Аутентификация (запрос токена для пользователя (логин / email / телефон))
 * {@link /api/auth/login}
 */
export function useAuthLogin<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, {data: AuthLoginMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthLoginMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authLoginMutationKey()

  const baseOptions = authLoginMutationOptions(config) as UseMutationOptions<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, {data: AuthLoginMutationRequest}, TContext>

  return useMutation<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, {data: AuthLoginMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, {data: AuthLoginMutationRequest}, TContext>
}