/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthConfirmEmailQueryResponse, AuthConfirmEmailQueryParams, AuthConfirmEmail422 } from "../../types/Auth/AuthConfirmEmail.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { authConfirmEmail } from "../../services/AuthService/authConfirmEmail.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const authConfirmEmailQueryKey = (params: AuthConfirmEmailQueryParams) => [{ url: '/api/auth/confirm-email' }, ...(params ? [params] : [])] as const

export type AuthConfirmEmailQueryKey = ReturnType<typeof authConfirmEmailQueryKey>

export function authConfirmEmailQueryOptions(params: AuthConfirmEmailQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authConfirmEmailQueryKey(params)
  return queryOptions<AuthConfirmEmailQueryResponse, ResponseErrorConfig<AuthConfirmEmail422>, AuthConfirmEmailQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return authConfirmEmail(params, config)
   },
  })
}

/**
 * @description данный роут вызывается после открытия ссылки из письма с подтверждением email
 * @summary Подтверждение email
 * {@link /api/auth/confirm-email}
 */
export function useAuthConfirmEmail<TData = AuthConfirmEmailQueryResponse, TQueryData = AuthConfirmEmailQueryResponse, TQueryKey extends QueryKey = AuthConfirmEmailQueryKey>(params: AuthConfirmEmailQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<AuthConfirmEmailQueryResponse, ResponseErrorConfig<AuthConfirmEmail422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? authConfirmEmailQueryKey(params)

  const query = useQuery({
   ...authConfirmEmailQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<AuthConfirmEmail422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}