/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthPasswordResetMutationRequest, AuthPasswordResetMutationResponse, AuthPasswordReset422 } from "../../types/Auth/AuthPasswordReset.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authPasswordReset } from "../../services/AuthService/authPasswordReset.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authPasswordResetMutationKey = () => [{ url: '/api/auth/password_reset' }] as const

export type AuthPasswordResetMutationKey = ReturnType<typeof authPasswordResetMutationKey>

export function authPasswordResetMutationOptions(config: Partial<RequestConfig<AuthPasswordResetMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = authPasswordResetMutationKey()
  return mutationOptions<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, {data: AuthPasswordResetMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return authPasswordReset(data, config)
    },
  })
}

/**
 * @description Высылается письмо с ссылкой для сброса пароля с использованием временного токена, который вшит в ссылку                               `https://info-run.ru/auth/reset-password?token={token}`                                далее используется роут `/api/auth/password_reset_with_token` непосредственно для изменения пароля
 * @summary Запрос на сброс пароля
 * {@link /api/auth/password_reset}
 */
export function useAuthPasswordReset<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, {data: AuthPasswordResetMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthPasswordResetMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authPasswordResetMutationKey()

  const baseOptions = authPasswordResetMutationOptions(config) as UseMutationOptions<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, {data: AuthPasswordResetMutationRequest}, TContext>

  return useMutation<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, {data: AuthPasswordResetMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, {data: AuthPasswordResetMutationRequest}, TContext>
}