/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthLogoutMutationResponse } from "../../types/Auth/AuthLogout.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authLogout } from "../../services/AuthService/authLogout.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authLogoutMutationKey = () => [{ url: '/api/auth/logout' }] as const

export type AuthLogoutMutationKey = ReturnType<typeof authLogoutMutationKey>

export function authLogoutMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = authLogoutMutationKey()
  return mutationOptions<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, void, typeof mutationKey>({
    mutationKey,
    mutationFn: async() => {
      return authLogout(config)
    },
  })
}

/**
 * @description Необходимо в заголовке отправлять токен (требуется для логироания выхода пользователя
 * @summary Выход, удаление токена при использовании 'HttpOnly cookie'
 * {@link /api/auth/logout}
 */
export function useAuthLogout<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authLogoutMutationKey()

  const baseOptions = authLogoutMutationOptions(config) as UseMutationOptions<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, void, TContext>

  return useMutation<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, void, TContext>
}