/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthChangePasswordMutationRequest, AuthChangePasswordMutationResponse, AuthChangePassword422 } from "../../types/Auth/AuthChangePassword.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authChangePassword } from "../../services/AuthService/authChangePassword.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authChangePasswordMutationKey = () => [{ url: '/api/auth/change-password' }] as const

export type AuthChangePasswordMutationKey = ReturnType<typeof authChangePasswordMutationKey>

export function authChangePasswordMutationOptions(config: Partial<RequestConfig<AuthChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = authChangePasswordMutationKey()
  return mutationOptions<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, {data: AuthChangePasswordMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return authChangePassword(data, config)
    },
  })
}

/**
 * @description пользователя получаем по токену, который передается из заголовка с frontend. Требуется проверка студента.
 * @summary Сменить пароль текущего пользователя (меняет сам пользователь)
 * {@link /api/auth/change-password}
 */
export function useAuthChangePassword<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, {data: AuthChangePasswordMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthChangePasswordMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authChangePasswordMutationKey()

  const baseOptions = authChangePasswordMutationOptions(config) as UseMutationOptions<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, {data: AuthChangePasswordMutationRequest}, TContext>

  return useMutation<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, {data: AuthChangePasswordMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, {data: AuthChangePasswordMutationRequest}, TContext>
}