/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthCheckTokenQueryResponse } from "../../types/Auth/AuthCheckToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { authCheckToken } from "../../services/AuthService/authCheckToken.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const authCheckTokenSuspenseQueryKey = () => [{ url: '/api/auth/check-token' }] as const

export type AuthCheckTokenSuspenseQueryKey = ReturnType<typeof authCheckTokenSuspenseQueryKey>

export function authCheckTokenSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authCheckTokenSuspenseQueryKey()
  return queryOptions<AuthCheckTokenQueryResponse, ResponseErrorConfig<Error>, AuthCheckTokenQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return authCheckToken(config)
   },
  })
}

/**
 * @summary Образец получения данных пользователя по токену (с разрешениями)
 * {@link /api/auth/check-token}
 */
export function useAuthCheckTokenSuspense<TData = AuthCheckTokenQueryResponse, TQueryKey extends QueryKey = AuthCheckTokenSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<AuthCheckTokenQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? authCheckTokenSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...authCheckTokenSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}