/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthConfirmEmailQueryResponse, AuthConfirmEmailQueryParams, AuthConfirmEmail422 } from "../../types/Auth/AuthConfirmEmail.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { authConfirmEmail } from "../../services/AuthService/authConfirmEmail.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const authConfirmEmailSuspenseQueryKey = (params: AuthConfirmEmailQueryParams) => [{ url: '/api/auth/confirm-email' }, ...(params ? [params] : [])] as const

export type AuthConfirmEmailSuspenseQueryKey = ReturnType<typeof authConfirmEmailSuspenseQueryKey>

export function authConfirmEmailSuspenseQueryOptions(params: AuthConfirmEmailQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authConfirmEmailSuspenseQueryKey(params)
  return queryOptions<AuthConfirmEmailQueryResponse, ResponseErrorConfig<AuthConfirmEmail422>, AuthConfirmEmailQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return authConfirmEmail(params, config)
   },
  })
}

/**
 * @description данный роут вызывается после открытия ссылки из письма с подтверждением email
 * @summary Подтверждение email
 * {@link /api/auth/confirm-email}
 */
export function useAuthConfirmEmailSuspense<TData = AuthConfirmEmailQueryResponse, TQueryKey extends QueryKey = AuthConfirmEmailSuspenseQueryKey>(params: AuthConfirmEmailQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<AuthConfirmEmailQueryResponse, ResponseErrorConfig<AuthConfirmEmail422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? authConfirmEmailSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...authConfirmEmailSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<AuthConfirmEmail422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}