/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthRegisterMutationRequest, AuthRegisterMutationResponse, AuthRegister422 } from "../../types/Auth/AuthRegister.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { authRegister } from "../../services/AuthService/authRegister.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const authRegisterMutationKey = () => [{ url: '/api/auth/register' }] as const

export type AuthRegisterMutationKey = ReturnType<typeof authRegisterMutationKey>

export function authRegisterMutationOptions(config: Partial<RequestConfig<AuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = authRegisterMutationKey()
  return mutationOptions<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, {data: AuthRegisterMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return authRegister(data, config)
    },
  })
}

/**
 * @description после ввода данных на указанный email отправляется письмо с подтверждением почты
 * @summary Регистрация пользователя
 * {@link /api/auth/register}
 */
export function useAuthRegister<TContext>(options: 
{
  mutation?: UseMutationOptions<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, {data: AuthRegisterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AuthRegisterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? authRegisterMutationKey()

  const baseOptions = authRegisterMutationOptions(config) as UseMutationOptions<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, {data: AuthRegisterMutationRequest}, TContext>

  return useMutation<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, {data: AuthRegisterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, {data: AuthRegisterMutationRequest}, TContext>
}