/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthCheckTokenQueryResponse } from "../../types/Auth/AuthCheckToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { authCheckToken } from "../../services/AuthService/authCheckToken.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const authCheckTokenQueryKey = () => [{ url: '/api/auth/check-token' }] as const

export type AuthCheckTokenQueryKey = ReturnType<typeof authCheckTokenQueryKey>

export function authCheckTokenQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = authCheckTokenQueryKey()
  return queryOptions<AuthCheckTokenQueryResponse, ResponseErrorConfig<Error>, AuthCheckTokenQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return authCheckToken(config)
   },
  })
}

/**
 * @summary Образец получения данных пользователя по токену (с разрешениями)
 * {@link /api/auth/check-token}
 */
export function useAuthCheckToken<TData = AuthCheckTokenQueryResponse, TQueryData = AuthCheckTokenQueryResponse, TQueryKey extends QueryKey = AuthCheckTokenQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<AuthCheckTokenQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? authCheckTokenQueryKey()

  const query = useQuery({
   ...authCheckTokenQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}