/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubtasksQueryParams, Subtasks200, Subtasks422, SubtasksQueryResponse } from "../../types/Subtasks/Subtasks.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const subtasksQueryParamsSchema = z.object({
    "subtask_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"task_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"subject_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"variant_id": z.optional(z.union([z.coerce.number().int(), z.null()])),
"search": z.optional(z.union([z.string(), z.null()])),
"created_date": z.optional(z.union([z.iso.date(), z.null()])),
"creator": z.optional(z.union([z.string(), z.null()])),
"sort_column1": z.optional(z.union([z.string(), z.null()]).default("SubTaskID")),
"sort_column2": z.optional(z.union([z.string(), z.null()]).default("SubTaskID")),
"sort_direction1": z.optional(z.union([z.string(), z.null()]).default("ASC")),
"sort_direction2": z.optional(z.union([z.string(), z.null()]).default("ASC")),
"p_offset": z.optional(z.union([z.coerce.number().int(), z.null()]).default(0)),
"p_limit": z.optional(z.union([z.coerce.number().int(), z.null()]).default(500000))
    }) as unknown as z.ZodType<SubtasksQueryParams>

/**
 * @description Successful Response
 */
export const subtasks200Schema = z.unknown() as unknown as z.ZodType<Subtasks200>

/**
 * @description Validation Error
 */
export const subtasks422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<Subtasks422>

export const subtasksQueryResponseSchema = subtasks200Schema as unknown as z.ZodType<SubtasksQueryResponse>