/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubtasksDeleteSubtaskIDPathParams, SubtasksDeleteSubtaskID200, SubtasksDeleteSubtaskID422, SubtasksDeleteSubtaskIDMutationResponse } from "../../types/Subtasks/SubtasksDeleteSubtaskID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const subtasksDeleteSubtaskIDPathParamsSchema = z.object({
    "subtask_id": z.coerce.number().int()
    }) as unknown as z.ZodType<SubtasksDeleteSubtaskIDPathParams>

/**
 * @description Successful Response
 */
export const subtasksDeleteSubtaskID200Schema = z.unknown() as unknown as z.ZodType<SubtasksDeleteSubtaskID200>

/**
 * @description Validation Error
 */
export const subtasksDeleteSubtaskID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<SubtasksDeleteSubtaskID422>

export const subtasksDeleteSubtaskIDMutationResponseSchema = subtasksDeleteSubtaskID200Schema as unknown as z.ZodType<SubtasksDeleteSubtaskIDMutationResponse>