/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubtasksCreate200, SubtasksCreate422, SubtasksCreateMutationRequest, SubtasksCreateMutationResponse } from "../../types/Subtasks/SubtasksCreate.ts";
import { bodySubtasksCreateSchema } from "../bodySubtasksCreateSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const subtasksCreate200Schema = z.unknown() as unknown as z.ZodType<SubtasksCreate200>

/**
 * @description Validation Error
 */
export const subtasksCreate422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<SubtasksCreate422>

export const subtasksCreateMutationRequestSchema = bodySubtasksCreateSchema as unknown as z.ZodType<SubtasksCreateMutationRequest>

export const subtasksCreateMutationResponseSchema = subtasksCreate200Schema as unknown as z.ZodType<SubtasksCreateMutationResponse>