/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubtasksUpdateSubtaskIDPathParams, SubtasksUpdateSubtaskID200, SubtasksUpdateSubtaskID422, SubtasksUpdateSubtaskIDMutationRequest, SubtasksUpdateSubtaskIDMutationResponse } from "../../types/Subtasks/SubtasksUpdateSubtaskID.ts";
import { bodySubtasksUpdateSubtaskIDSchema } from "../bodySubtasksUpdateSubtaskIDSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const subtasksUpdateSubtaskIDPathParamsSchema = z.object({
    "subtask_id": z.coerce.number().int()
    }) as unknown as z.ZodType<SubtasksUpdateSubtaskIDPathParams>

/**
 * @description Successful Response
 */
export const subtasksUpdateSubtaskID200Schema = z.unknown() as unknown as z.ZodType<SubtasksUpdateSubtaskID200>

/**
 * @description Validation Error
 */
export const subtasksUpdateSubtaskID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<SubtasksUpdateSubtaskID422>

export const subtasksUpdateSubtaskIDMutationRequestSchema = bodySubtasksUpdateSubtaskIDSchema as unknown as z.ZodType<SubtasksUpdateSubtaskIDMutationRequest>

export const subtasksUpdateSubtaskIDMutationResponseSchema = subtasksUpdateSubtaskID200Schema as unknown as z.ZodType<SubtasksUpdateSubtaskIDMutationResponse>