/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubtasksSubtaskIDPathParams, SubtasksSubtaskID200, SubtasksSubtaskID422, SubtasksSubtaskIDQueryResponse } from "../../types/Subtasks/SubtasksSubtaskID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const subtasksSubtaskIDPathParamsSchema = z.object({
    "subtask_id": z.coerce.number().int()
    }) as unknown as z.ZodType<SubtasksSubtaskIDPathParams>

/**
 * @description Successful Response
 */
export const subtasksSubtaskID200Schema = z.unknown() as unknown as z.ZodType<SubtasksSubtaskID200>

/**
 * @description Validation Error
 */
export const subtasksSubtaskID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<SubtasksSubtaskID422>

export const subtasksSubtaskIDQueryResponseSchema = subtasksSubtaskID200Schema as unknown as z.ZodType<SubtasksSubtaskIDQueryResponse>