/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { HealthCheckApiHealthGetQueryResponse } from "../../types/Health/HealthCheckApiHealthGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { healthCheckApiHealthGetQueryResponseSchema } from "../../zod/HealthSchemas/healthCheckApiHealthGetSchema.ts";

function getHealthCheckApiHealthGetUrl() {
  const res = { method: 'GET', url: `/api/health` as const }  
  return res
}

/**
 * @description Проверка состояния сервиса.
 * @summary роут проверки конфигурации
 * {@link /api/health}
 */
export async function healthCheckApiHealthGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<HealthCheckApiHealthGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getHealthCheckApiHealthGetUrl().url.toString(), ... requestConfig })  
  return healthCheckApiHealthGetQueryResponseSchema.parse(res.data)
}