/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { healthCheckApiHealthGet } from "./healthCheckApiHealthGet.ts";

export function HealthService() {
  return { healthCheckApiHealthGet }
}