/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost } from "./adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
import { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost } from "./assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
import { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost } from "./assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
import { getLogsApiAdminStudentsLogsGet } from "./getLogsApiAdminStudentsLogsGet.ts";
import { getLogsApiAdminStudentsStudentIDLogsGet } from "./getLogsApiAdminStudentsStudentIDLogsGet.ts";
import { readAllStudentsApiAdminStudentsGet } from "./readAllStudentsApiAdminStudentsGet.ts";
import { readPermissionApiAdminPermissionGet } from "./readPermissionApiAdminPermissionGet.ts";
import { readPermissionsRoleApiAdminRolesRoleIdGet } from "./readPermissionsRoleApiAdminRolesRoleIdGet.ts";
import { readRolesApiAdminRolesGet } from "./readRolesApiAdminRolesGet.ts";

export function AdminService() {
  return { readRolesApiAdminRolesGet, readPermissionsRoleApiAdminRolesRoleIdGet, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost, readPermissionApiAdminPermissionGet, readAllStudentsApiAdminStudentsGet, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost, getLogsApiAdminStudentsLogsGet, getLogsApiAdminStudentsStudentIDLogsGet }
}