/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422 } from "../../types/Admin/AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponseSchema, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequestSchema } from "../../zod/AdminSchemas/adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostSchema.ts";

function getAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostUrl({ studentId }: { studentId: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"] }) {
  const res = { method: 'POST', url: `/api/admin/students/${studentId}/change-password` as const }  
  return res
}

/**
 * @description пароль смены студента администратором
 * @summary Сменить пароль выбранного студента по его id
 * {@link /api/admin/students/:student_id/change-password}
 */
export async function adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost({ studentId, data }: { studentId: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"]; data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest }, config: Partial<RequestConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequestSchema.parse(data)  
  
  const res = await request<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest>({ method : "POST", url : getAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostUrl({ studentId }).url.toString(), data : requestData, ... requestConfig })  
  return adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponseSchema.parse(res.data)
}