/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422 } from "../../types/Admin/AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponseSchema } from "../../zod/AdminSchemas/assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostSchema.ts";

function getAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostUrl({ studentID }: { studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"] }) {
  const res = { method: 'POST', url: `/api/admin/students/${studentID}/assign-role` as const }  
  return res
}

/**
 * @description требуется токен авторизации                     studentID передается как path **/students/4**                     RoleID передается как query параметр **/assign-role?RoleID=2**
 * @summary Назначить роль студенту по его id с указанием id роли
 * {@link /api/admin/students/:studentID/assign-role}
 */
export async function assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost({ studentID, params }: { studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"]; params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, unknown>({ method : "POST", url : getAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostUrl({ studentID }).url.toString(), params, ... requestConfig })  
  return assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponseSchema.parse(res.data)
}