/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422 } from "../../types/Admin/AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponseSchema, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequestSchema } from "../../zod/AdminSchemas/assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostSchema.ts";

function getAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostUrl({ roleId }: { roleId: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"] }) {
  const res = { method: 'POST', url: `/api/admin/roles/${roleId}/assign-permission` as const }  
  return res
}

/**
 * @description для выбранной роли по её id необходимо передать массив из id разрашений, данный массив и будет назначен для данной роли                   список разрешений можно посмотреть по роуту: /api/admin/permission
 * @summary Назначить разрешения для роли
 * {@link /api/admin/roles/:role_id/assign-permission}
 */
export async function assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost({ roleId, data }: { roleId: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"]; data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest }, config: Partial<RequestConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequestSchema.parse(data)  
  
  const res = await request<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest>({ method : "POST", url : getAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostUrl({ roleId }).url.toString(), data : requestData, ... requestConfig })  
  return assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponseSchema.parse(res.data)
}