/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetLogsApiAdminStudentsLogsGetQueryResponse, GetLogsApiAdminStudentsLogsGetQueryParams, GetLogsApiAdminStudentsLogsGet422 } from "../../types/Admin/GetLogsApiAdminStudentsLogsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { getLogsApiAdminStudentsLogsGetQueryResponseSchema } from "../../zod/AdminSchemas/getLogsApiAdminStudentsLogsGetSchema.ts";

function getGetLogsApiAdminStudentsLogsGetUrl() {
  const res = { method: 'GET', url: `/api/admin/students/logs` as const }  
  return res
}

/**
 * @description Роут доступен только пользователям с разрешением `view_history`.                    `limit`: Сколько логов вернуть (по умолчанию 50, максимум 10000)                    `offset`: Смещение от начала выборки
 * @summary Вывод истории действий всех пользователей
 * {@link /api/admin/students/logs}
 */
export async function getLogsApiAdminStudentsLogsGet({ params }: { params?: GetLogsApiAdminStudentsLogsGetQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetLogsApiAdminStudentsLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsLogsGet422>, unknown>({ method : "GET", url : getGetLogsApiAdminStudentsLogsGetUrl().url.toString(), params, ... requestConfig })  
  return getLogsApiAdminStudentsLogsGetQueryResponseSchema.parse(res.data)
}