/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, GetLogsApiAdminStudentsStudentIDLogsGetPathParams, GetLogsApiAdminStudentsStudentIDLogsGet422 } from "../../types/Admin/GetLogsApiAdminStudentsStudentIDLogsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { getLogsApiAdminStudentsStudentIDLogsGetQueryResponseSchema } from "../../zod/AdminSchemas/getLogsApiAdminStudentsStudentIDLogsGetSchema.ts";

function getGetLogsApiAdminStudentsStudentIDLogsGetUrl({ studentID }: { studentID: GetLogsApiAdminStudentsStudentIDLogsGetPathParams["studentID"] }) {
  const res = { method: 'GET', url: `/api/admin/students/${studentID}/logs` as const }  
  return res
}

/**
 * @description данный роут работает для администратора (может смотреть логи любого студента по его id)                    и для текущего авторизованного пользователя (если совпадает его id с studentID из адреса)
 * @summary Вывод истории действий пользователя по его ID
 * {@link /api/admin/students/:studentID/logs}
 */
export async function getLogsApiAdminStudentsStudentIDLogsGet({ studentID }: { studentID: GetLogsApiAdminStudentsStudentIDLogsGetPathParams["studentID"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsStudentIDLogsGet422>, unknown>({ method : "GET", url : getGetLogsApiAdminStudentsStudentIDLogsGetUrl({ studentID }).url.toString(), ... requestConfig })  
  return getLogsApiAdminStudentsStudentIDLogsGetQueryResponseSchema.parse(res.data)
}