/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams, ReadPermissionsRoleApiAdminRolesRoleIdGet422 } from "../../types/Admin/ReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { readPermissionsRoleApiAdminRolesRoleIdGetQueryResponseSchema } from "../../zod/AdminSchemas/readPermissionsRoleApiAdminRolesRoleIdGetSchema.ts";

function getReadPermissionsRoleApiAdminRolesRoleIdGetUrl({ roleId }: { roleId: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams["role_id"] }) {
  const res = { method: 'GET', url: `/api/admin/roles/${roleId}` as const }  
  return res
}

/**
 * @summary Получить список разрешения для роли по её id
 * {@link /api/admin/roles/:role_id}
 */
export async function readPermissionsRoleApiAdminRolesRoleIdGet({ roleId }: { roleId: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams["role_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ResponseErrorConfig<ReadPermissionsRoleApiAdminRolesRoleIdGet422>, unknown>({ method : "GET", url : getReadPermissionsRoleApiAdminRolesRoleIdGetUrl({ roleId }).url.toString(), ... requestConfig })  
  return readPermissionsRoleApiAdminRolesRoleIdGetQueryResponseSchema.parse(res.data)
}