/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadRolesApiAdminRolesGetQueryResponse } from "../../types/Admin/ReadRolesApiAdminRolesGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { readRolesApiAdminRolesGetQueryResponseSchema } from "../../zod/AdminSchemas/readRolesApiAdminRolesGetSchema.ts";

function getReadRolesApiAdminRolesGetUrl() {
  const res = { method: 'GET', url: `/api/admin/roles` as const }  
  return res
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех ролей
 * {@link /api/admin/roles}
 */
export async function readRolesApiAdminRolesGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ReadRolesApiAdminRolesGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getReadRolesApiAdminRolesGetUrl().url.toString(), ... requestConfig })  
  return readRolesApiAdminRolesGetQueryResponseSchema.parse(res.data)
}