/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadPermissionApiAdminPermissionGetQueryResponse } from "../../types/Admin/ReadPermissionApiAdminPermissionGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { readPermissionApiAdminPermissionGetQueryResponseSchema } from "../../zod/AdminSchemas/readPermissionApiAdminPermissionGetSchema.ts";

function getReadPermissionApiAdminPermissionGetUrl() {
  const res = { method: 'GET', url: `/api/admin/permission` as const }  
  return res
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех разрешений
 * {@link /api/admin/permission}
 */
export async function readPermissionApiAdminPermissionGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ReadPermissionApiAdminPermissionGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getReadPermissionApiAdminPermissionGetUrl().url.toString(), ... requestConfig })  
  return readPermissionApiAdminPermissionGetQueryResponseSchema.parse(res.data)
}