/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadAllStudentsApiAdminStudentsGetQueryResponse } from "../../types/Admin/ReadAllStudentsApiAdminStudentsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { readAllStudentsApiAdminStudentsGetQueryResponseSchema } from "../../zod/AdminSchemas/readAllStudentsApiAdminStudentsGetSchema.ts";

function getReadAllStudentsApiAdminStudentsGetUrl() {
  const res = { method: 'GET', url: `/api/admin/students` as const }  
  return res
}

/**
 * @summary Получить список студентов в формате JSON (для админа)
 * {@link /api/admin/students}
 */
export async function readAllStudentsApiAdminStudentsGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ReadAllStudentsApiAdminStudentsGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getReadAllStudentsApiAdminStudentsGetUrl().url.toString(), ... requestConfig })  
  return readAllStudentsApiAdminStudentsGetQueryResponseSchema.parse(res.data)
}