/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsQueryResponse, VariantsQueryParams, Variants422 } from "../../types/Variants/Variants.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { variantsQueryResponseSchema } from "../../zod/VariantsSchemas/variantsSchema.ts";

function getVariantsUrl() {
  const res = { method: 'GET', url: `/api/variants` as const }  
  return res
}

/**
 * @description Если передан параметр **subject_id**, то возвращаются варианты только для указанного предмета.                              Если параметр не передан, возвращаются варианты по всем предметам.                              **subjectID** передается как Query-параметр                                       "`/api/variants` — все варианты"                                      "`/api/variants?subjectID=10` — варианты для предмета с subject ID 10"                                      так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список вариантов
 * {@link /api/variants}
 */
export async function variants({ params }: { params?: VariantsQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<VariantsQueryResponse, ResponseErrorConfig<Variants422>, unknown>({ method : "GET", url : getVariantsUrl().url.toString(), params, ... requestConfig })  
  return variantsQueryResponseSchema.parse(res.data)
}