/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsVariantIDQueryResponse, VariantsVariantIDPathParams, VariantsVariantID422 } from "../../types/Variants/VariantsVariantID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { variantsVariantIDQueryResponseSchema } from "../../zod/VariantsSchemas/variantsVariantIDSchema.ts";

function getVariantsVariantIDUrl({ variantId }: { variantId: VariantsVariantIDPathParams["variant_id"] }) {
  const res = { method: 'GET', url: `/api/variants/${variantId}` as const }  
  return res
}

/**
 * @summary Получить вариант по его variant_id
 * {@link /api/variants/:variant_id}
 */
export async function variantsVariantID({ variantId }: { variantId: VariantsVariantIDPathParams["variant_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<VariantsVariantIDQueryResponse, ResponseErrorConfig<VariantsVariantID422>, unknown>({ method : "GET", url : getVariantsVariantIDUrl({ variantId }).url.toString(), ... requestConfig })  
  return variantsVariantIDQueryResponseSchema.parse(res.data)
}