/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { variants } from "./variants.ts";
import { variantsExecVariantIDStudentID } from "./variantsExecVariantIDStudentID.ts";
import { variantsVariantID } from "./variantsVariantID.ts";

export function VariantsService() {
  return { variants, variantsVariantID, variantsExecVariantIDStudentID }
}