/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsExecVariantIDStudentIDQueryResponse, VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID422 } from "../../types/Variants/VariantsExecVariantIDStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { variantsExecVariantIDStudentIDQueryResponseSchema } from "../../zod/VariantsSchemas/variantsExecVariantIDStudentIDSchema.ts";

function getVariantsExecVariantIDStudentIDUrl({ variantID, studentID }: { variantID: VariantsExecVariantIDStudentIDPathParams["VariantID"]; studentID: VariantsExecVariantIDStudentIDPathParams["StudentID"] }) {
  const res = { method: 'GET', url: `/api/variants/exec/${variantID}/${studentID}` as const }  
  return res
}

/**
 * @summary роут с вызовом хранимой процедуры
 * {@link /api/variants/exec/:VariantID/:StudentID}
 */
export async function variantsExecVariantIDStudentID({ variantID, studentID }: { variantID: VariantsExecVariantIDStudentIDPathParams["VariantID"]; studentID: VariantsExecVariantIDStudentIDPathParams["StudentID"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<VariantsExecVariantIDStudentIDQueryResponse, ResponseErrorConfig<VariantsExecVariantIDStudentID422>, unknown>({ method : "GET", url : getVariantsExecVariantIDStudentIDUrl({ variantID, studentID }).url.toString(), ... requestConfig })  
  return variantsExecVariantIDStudentIDQueryResponseSchema.parse(res.data)
}