export type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey } from "./hooks/AdminHooks/useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey } from "./hooks/AdminHooks/useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey } from "./hooks/AdminHooks/useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export type { GetLogsApiAdminStudentsLogsGetQueryKey } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsLogsGet.ts";
export type { GetLogsApiAdminStudentsLogsGetSuspenseQueryKey } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsLogsGetSuspense.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetQueryKey } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGet.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGetSuspense.ts";
export type { ReadAllStudentsApiAdminStudentsGetQueryKey } from "./hooks/AdminHooks/useReadAllStudentsApiAdminStudentsGet.ts";
export type { ReadAllStudentsApiAdminStudentsGetSuspenseQueryKey } from "./hooks/AdminHooks/useReadAllStudentsApiAdminStudentsGetSuspense.ts";
export type { ReadPermissionApiAdminPermissionGetQueryKey } from "./hooks/AdminHooks/useReadPermissionApiAdminPermissionGet.ts";
export type { ReadPermissionApiAdminPermissionGetSuspenseQueryKey } from "./hooks/AdminHooks/useReadPermissionApiAdminPermissionGetSuspense.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetQueryKey } from "./hooks/AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey } from "./hooks/AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense.ts";
export type { ReadRolesApiAdminRolesGetQueryKey } from "./hooks/AdminHooks/useReadRolesApiAdminRolesGet.ts";
export type { ReadRolesApiAdminRolesGetSuspenseQueryKey } from "./hooks/AdminHooks/useReadRolesApiAdminRolesGetSuspense.ts";
export type { AuthChangePasswordMutationKey } from "./hooks/AuthHooks/useAuthChangePassword.ts";
export type { AuthCheckTokenQueryKey } from "./hooks/AuthHooks/useAuthCheckToken.ts";
export type { AuthCheckTokenSuspenseQueryKey } from "./hooks/AuthHooks/useAuthCheckTokenSuspense.ts";
export type { AuthConfirmEmailQueryKey } from "./hooks/AuthHooks/useAuthConfirmEmail.ts";
export type { AuthConfirmEmailSuspenseQueryKey } from "./hooks/AuthHooks/useAuthConfirmEmailSuspense.ts";
export type { AuthLoginMutationKey } from "./hooks/AuthHooks/useAuthLogin.ts";
export type { AuthLogoutMutationKey } from "./hooks/AuthHooks/useAuthLogout.ts";
export type { AuthPasswordResetMutationKey } from "./hooks/AuthHooks/useAuthPasswordReset.ts";
export type { AuthPasswordResetWithTokenMutationKey } from "./hooks/AuthHooks/useAuthPasswordResetWithToken.ts";
export type { AuthRegisterMutationKey } from "./hooks/AuthHooks/useAuthRegister.ts";
export type { GetDocumentationApiDocsGetQueryKey } from "./hooks/DefaultHooks/useGetDocumentationApiDocsGet.ts";
export type { GetDocumentationApiDocsGetSuspenseQueryKey } from "./hooks/DefaultHooks/useGetDocumentationApiDocsGetSuspense.ts";
export type { GetRedocDocumentationApiRedocGetQueryKey } from "./hooks/DefaultHooks/useGetRedocDocumentationApiRedocGet.ts";
export type { GetRedocDocumentationApiRedocGetSuspenseQueryKey } from "./hooks/DefaultHooks/useGetRedocDocumentationApiRedocGetSuspense.ts";
export type { OpenapiApiOpenapiJsonGetQueryKey } from "./hooks/DefaultHooks/useOpenapiApiOpenapiJsonGet.ts";
export type { OpenapiApiOpenapiJsonGetSuspenseQueryKey } from "./hooks/DefaultHooks/useOpenapiApiOpenapiJsonGetSuspense.ts";
export type { HealthCheckApiHealthGetQueryKey } from "./hooks/HealthHooks/useHealthCheckApiHealthGet.ts";
export type { HealthCheckApiHealthGetSuspenseQueryKey } from "./hooks/HealthHooks/useHealthCheckApiHealthGetSuspense.ts";
export type { DeleteStudentMutationKey } from "./hooks/StudentsHooks/useDeleteStudent.ts";
export type { NewStudentMutationKey } from "./hooks/StudentsHooks/useNewStudent.ts";
export type { StudentsQueryKey, StudentsMutationKey } from "./hooks/StudentsHooks/useStudents.ts";
export type { StudentsSearchQueryKey } from "./hooks/StudentsHooks/useStudentsSearch.ts";
export type { StudentsSearchSuspenseQueryKey } from "./hooks/StudentsHooks/useStudentsSearchSuspense.ts";
export type { StudentsStudentIDQueryKey } from "./hooks/StudentsHooks/useStudentsStudentID.ts";
export type { StudentsStudentIDSuspenseQueryKey } from "./hooks/StudentsHooks/useStudentsStudentIDSuspense.ts";
export type { StudentsSuspenseQueryKey } from "./hooks/StudentsHooks/useStudentsSuspense.ts";
export type { StudentsSubtasksQueryKey } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksQueryKey } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksSuspenseQueryKey } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasksSuspense.ts";
export type { StudentsSubtasksSuspenseQueryKey } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksSuspense.ts";
export type { SubjectsQueryKey } from "./hooks/SubjectsHooks/useSubjects.ts";
export type { SubjectsSubjectIDQueryKey } from "./hooks/SubjectsHooks/useSubjectsSubjectID.ts";
export type { SubjectsSubjectIDSuspenseQueryKey } from "./hooks/SubjectsHooks/useSubjectsSubjectIDSuspense.ts";
export type { SubjectsSuspenseQueryKey } from "./hooks/SubjectsHooks/useSubjectsSuspense.ts";
export type { SubtasksQueryKey } from "./hooks/SubtasksHooks/useSubtasks.ts";
export type { SubtasksCreateMutationKey } from "./hooks/SubtasksHooks/useSubtasksCreate.ts";
export type { SubtasksDeleteSubtaskIDMutationKey } from "./hooks/SubtasksHooks/useSubtasksDeleteSubtaskID.ts";
export type { SubtasksSubtaskIDQueryKey } from "./hooks/SubtasksHooks/useSubtasksSubtaskID.ts";
export type { SubtasksSubtaskIDSuspenseQueryKey } from "./hooks/SubtasksHooks/useSubtasksSubtaskIDSuspense.ts";
export type { SubtasksSuspenseQueryKey } from "./hooks/SubtasksHooks/useSubtasksSuspense.ts";
export type { SubtasksUpdateSubtaskIDMutationKey } from "./hooks/SubtasksHooks/useSubtasksUpdateSubtaskID.ts";
export type { TasksQueryKey } from "./hooks/TasksHooks/useTasks.ts";
export type { TasksSuspenseQueryKey } from "./hooks/TasksHooks/useTasksSuspense.ts";
export type { TasksTaskIDQueryKey } from "./hooks/TasksHooks/useTasksTaskID.ts";
export type { TasksTaskIDSuspenseQueryKey } from "./hooks/TasksHooks/useTasksTaskIDSuspense.ts";
export type { VariantsQueryKey } from "./hooks/VariantsHooks/useVariants.ts";
export type { VariantsExecVariantIDStudentIDQueryKey } from "./hooks/VariantsHooks/useVariantsExecVariantIDStudentID.ts";
export type { VariantsExecVariantIDStudentIDSuspenseQueryKey } from "./hooks/VariantsHooks/useVariantsExecVariantIDStudentIDSuspense.ts";
export type { VariantsSuspenseQueryKey } from "./hooks/VariantsHooks/useVariantsSuspense.ts";
export type { VariantsVariantIDQueryKey } from "./hooks/VariantsHooks/useVariantsVariantID.ts";
export type { VariantsVariantIDSuspenseQueryKey } from "./hooks/VariantsHooks/useVariantsVariantIDSuspense.ts";
export type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutation } from "./types/Admin/AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutation } from "./types/Admin/AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutation } from "./types/Admin/AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export type { GetLogsApiAdminStudentsLogsGetQueryParams, GetLogsApiAdminStudentsLogsGet200, GetLogsApiAdminStudentsLogsGet422, GetLogsApiAdminStudentsLogsGetQueryResponse, GetLogsApiAdminStudentsLogsGetQuery } from "./types/Admin/GetLogsApiAdminStudentsLogsGet.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetPathParams, GetLogsApiAdminStudentsStudentIDLogsGet200, GetLogsApiAdminStudentsStudentIDLogsGet422, GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, GetLogsApiAdminStudentsStudentIDLogsGetQuery } from "./types/Admin/GetLogsApiAdminStudentsStudentIDLogsGet.ts";
export type { ReadAllStudentsApiAdminStudentsGet200, ReadAllStudentsApiAdminStudentsGetQueryResponse, ReadAllStudentsApiAdminStudentsGetQuery } from "./types/Admin/ReadAllStudentsApiAdminStudentsGet.ts";
export type { ReadPermissionApiAdminPermissionGet200, ReadPermissionApiAdminPermissionGetQueryResponse, ReadPermissionApiAdminPermissionGetQuery } from "./types/Admin/ReadPermissionApiAdminPermissionGet.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams, ReadPermissionsRoleApiAdminRolesRoleIdGet200, ReadPermissionsRoleApiAdminRolesRoleIdGet422, ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ReadPermissionsRoleApiAdminRolesRoleIdGetQuery } from "./types/Admin/ReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export type { ReadRolesApiAdminRolesGet200, ReadRolesApiAdminRolesGetQueryResponse, ReadRolesApiAdminRolesGetQuery } from "./types/Admin/ReadRolesApiAdminRolesGet.ts";
export type { AdminChangePasswordRequest } from "./types/AdminChangePasswordRequest.ts";
export type { AssignPermissionsRequest } from "./types/AssignPermissionsRequest.ts";
export type { AuthChangePassword200, AuthChangePassword422, AuthChangePasswordMutationRequest, AuthChangePasswordMutationResponse, AuthChangePasswordMutation } from "./types/Auth/AuthChangePassword.ts";
export type { AuthCheckToken200, AuthCheckTokenQueryResponse, AuthCheckTokenQuery } from "./types/Auth/AuthCheckToken.ts";
export type { AuthConfirmEmailQueryParams, AuthConfirmEmail200, AuthConfirmEmail422, AuthConfirmEmailQueryResponse, AuthConfirmEmailQuery } from "./types/Auth/AuthConfirmEmail.ts";
export type { AuthLogin200, AuthLogin422, AuthLoginMutationRequest, AuthLoginMutationResponse, AuthLoginMutation } from "./types/Auth/AuthLogin.ts";
export type { AuthLogout200, AuthLogoutMutationResponse, AuthLogoutMutation } from "./types/Auth/AuthLogout.ts";
export type { AuthPasswordReset200, AuthPasswordReset422, AuthPasswordResetMutationRequest, AuthPasswordResetMutationResponse, AuthPasswordResetMutation } from "./types/Auth/AuthPasswordReset.ts";
export type { AuthPasswordResetWithToken200, AuthPasswordResetWithToken422, AuthPasswordResetWithTokenMutationRequest, AuthPasswordResetWithTokenMutationResponse, AuthPasswordResetWithTokenMutation } from "./types/Auth/AuthPasswordResetWithToken.ts";
export type { AuthRegister200, AuthRegister422, AuthRegisterMutationRequest, AuthRegisterMutationResponse, AuthRegisterMutation } from "./types/Auth/AuthRegister.ts";
export type { AuthRequest } from "./types/AuthRequest.ts";
export type { BodySubtasksCreate } from "./types/BodySubtasksCreate.ts";
export type { BodySubtasksUpdateSubtaskID } from "./types/BodySubtasksUpdateSubtaskID.ts";
export type { ChangePasswordRequest } from "./types/ChangePasswordRequest.ts";
export type { GetDocumentationApiDocsGet200, GetDocumentationApiDocsGetQueryResponse, GetDocumentationApiDocsGetQuery } from "./types/Default/GetDocumentationApiDocsGet.ts";
export type { GetRedocDocumentationApiRedocGet200, GetRedocDocumentationApiRedocGetQueryResponse, GetRedocDocumentationApiRedocGetQuery } from "./types/Default/GetRedocDocumentationApiRedocGet.ts";
export type { OpenapiApiOpenapiJsonGet200, OpenapiApiOpenapiJsonGetQueryResponse, OpenapiApiOpenapiJsonGetQuery } from "./types/Default/OpenapiApiOpenapiJsonGet.ts";
export type { HealthCheckApiHealthGet200, HealthCheckApiHealthGetQueryResponse, HealthCheckApiHealthGetQuery } from "./types/Health/HealthCheckApiHealthGet.ts";
export type { HTTPValidationError } from "./types/HTTPValidationError.ts";
export type { PasswordReset } from "./types/PasswordReset.ts";
export type { PasswordResetConfirm } from "./types/PasswordResetConfirm.ts";
export type { Permission } from "./types/Permission.ts";
export type { Roles } from "./types/Roles.ts";
export type { SortableFields } from "./types/SortableFields.ts";
export type { SortDirection } from "./types/SortDirection.ts";
export type { StudentAuth } from "./types/StudentAuth.ts";
export type { StudentCreate } from "./types/StudentCreate.ts";
export type { StudentEdit } from "./types/StudentEdit.ts";
export type { StudentField } from "./types/StudentField.ts";
export type { StudentOut } from "./types/StudentOut.ts";
export type { DeleteStudentQueryParams, DeleteStudent200, DeleteStudent422, DeleteStudentMutationResponse, DeleteStudentMutation } from "./types/Students/DeleteStudent.ts";
export type { EditStudentQueryParams, EditStudent200, EditStudent422, EditStudentMutationRequest, EditStudentMutationResponse, EditStudentMutation } from "./types/Students/EditStudent.ts";
export type { NewStudent200, NewStudent422, NewStudentMutationRequest, NewStudentMutationResponse, NewStudentMutation } from "./types/Students/NewStudent.ts";
export type { Students200, StudentsQueryResponse, StudentsQuery, StudentsQueryParams, Students422, StudentsMutationResponse, StudentsMutation } from "./types/Students/Students.ts";
export type { StudentsSearchQueryParams, StudentsSearch200, StudentsSearch422, StudentsSearchQueryResponse, StudentsSearchQuery } from "./types/Students/StudentsSearch.ts";
export type { StudentsStudentIDPathParams, StudentsStudentID200, StudentsStudentID422, StudentsStudentIDQueryResponse, StudentsStudentIDQuery } from "./types/Students/StudentsStudentID.ts";
export type { StudentsSubtasksQueryParams, StudentsSubtasks200, StudentsSubtasks422, StudentsSubtasksQueryResponse, StudentsSubtasksQuery } from "./types/StudentsSubtasks/StudentsSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks200, StudentsSubtasksAssignSubtasks422, StudentsSubtasksAssignSubtasksQueryResponse, StudentsSubtasksAssignSubtasksQuery } from "./types/StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
export type { StudentTaskRead } from "./types/StudentTaskRead.ts";
export type { SubjectListResponse } from "./types/SubjectListResponse.ts";
export type { SubjectRead } from "./types/SubjectRead.ts";
export type { Subjects200, SubjectsQueryResponse, SubjectsQuery } from "./types/Subjects/Subjects.ts";
export type { SubjectsSubjectIDPathParams, SubjectsSubjectID200, SubjectsSubjectID422, SubjectsSubjectIDQueryResponse, SubjectsSubjectIDQuery } from "./types/Subjects/SubjectsSubjectID.ts";
export type { SubtasksQueryParams, Subtasks200, Subtasks422, SubtasksQueryResponse, SubtasksQuery } from "./types/Subtasks/Subtasks.ts";
export type { SubtasksCreate200, SubtasksCreate422, SubtasksCreateMutationRequest, SubtasksCreateMutationResponse, SubtasksCreateMutation } from "./types/Subtasks/SubtasksCreate.ts";
export type { SubtasksDeleteSubtaskIDPathParams, SubtasksDeleteSubtaskID200, SubtasksDeleteSubtaskID422, SubtasksDeleteSubtaskIDMutationResponse, SubtasksDeleteSubtaskIDMutation } from "./types/Subtasks/SubtasksDeleteSubtaskID.ts";
export type { SubtasksSubtaskIDPathParams, SubtasksSubtaskID200, SubtasksSubtaskID422, SubtasksSubtaskIDQueryResponse, SubtasksSubtaskIDQuery } from "./types/Subtasks/SubtasksSubtaskID.ts";
export type { SubtasksUpdateSubtaskIDPathParams, SubtasksUpdateSubtaskID200, SubtasksUpdateSubtaskID422, SubtasksUpdateSubtaskIDMutationRequest, SubtasksUpdateSubtaskIDMutationResponse, SubtasksUpdateSubtaskIDMutation } from "./types/Subtasks/SubtasksUpdateSubtaskID.ts";
export type { TaskListResponse } from "./types/TaskListResponse.ts";
export type { TaskRead } from "./types/TaskRead.ts";
export type { TasksQueryParams, Tasks200, Tasks422, TasksQueryResponse, TasksQuery } from "./types/Tasks/Tasks.ts";
export type { TasksTaskIDPathParams, TasksTaskID200, TasksTaskID422, TasksTaskIDQueryResponse, TasksTaskIDQuery } from "./types/Tasks/TasksTaskID.ts";
export type { TokenWithStudent } from "./types/TokenWithStudent.ts";
export type { UserCreate } from "./types/UserCreate.ts";
export type { ValidationError } from "./types/ValidationError.ts";
export type { VariantsQueryParams, Variants200, Variants422, VariantsQueryResponse, VariantsQuery } from "./types/Variants/Variants.ts";
export type { VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID200, VariantsExecVariantIDStudentID422, VariantsExecVariantIDStudentIDQueryResponse, VariantsExecVariantIDStudentIDQuery } from "./types/Variants/VariantsExecVariantIDStudentID.ts";
export type { VariantsVariantIDPathParams, VariantsVariantID200, VariantsVariantID422, VariantsVariantIDQueryResponse, VariantsVariantIDQuery } from "./types/Variants/VariantsVariantID.ts";
export { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationOptions, useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost } from "./hooks/AdminHooks/useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationOptions, useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost } from "./hooks/AdminHooks/useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationOptions, useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost } from "./hooks/AdminHooks/useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export { getLogsApiAdminStudentsLogsGetQueryKey, getLogsApiAdminStudentsLogsGetQueryOptions, useGetLogsApiAdminStudentsLogsGet } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsLogsGet.ts";
export { getLogsApiAdminStudentsLogsGetSuspenseQueryKey, getLogsApiAdminStudentsLogsGetSuspenseQueryOptions, useGetLogsApiAdminStudentsLogsGetSuspense } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsLogsGetSuspense.ts";
export { getLogsApiAdminStudentsStudentIDLogsGetQueryKey, getLogsApiAdminStudentsStudentIDLogsGetQueryOptions, useGetLogsApiAdminStudentsStudentIDLogsGet } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGet.ts";
export { getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey, getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryOptions, useGetLogsApiAdminStudentsStudentIDLogsGetSuspense } from "./hooks/AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGetSuspense.ts";
export { readAllStudentsApiAdminStudentsGetQueryKey, readAllStudentsApiAdminStudentsGetQueryOptions, useReadAllStudentsApiAdminStudentsGet } from "./hooks/AdminHooks/useReadAllStudentsApiAdminStudentsGet.ts";
export { readAllStudentsApiAdminStudentsGetSuspenseQueryKey, readAllStudentsApiAdminStudentsGetSuspenseQueryOptions, useReadAllStudentsApiAdminStudentsGetSuspense } from "./hooks/AdminHooks/useReadAllStudentsApiAdminStudentsGetSuspense.ts";
export { readPermissionApiAdminPermissionGetQueryKey, readPermissionApiAdminPermissionGetQueryOptions, useReadPermissionApiAdminPermissionGet } from "./hooks/AdminHooks/useReadPermissionApiAdminPermissionGet.ts";
export { readPermissionApiAdminPermissionGetSuspenseQueryKey, readPermissionApiAdminPermissionGetSuspenseQueryOptions, useReadPermissionApiAdminPermissionGetSuspense } from "./hooks/AdminHooks/useReadPermissionApiAdminPermissionGetSuspense.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGetQueryKey, readPermissionsRoleApiAdminRolesRoleIdGetQueryOptions, useReadPermissionsRoleApiAdminRolesRoleIdGet } from "./hooks/AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey, readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryOptions, useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense } from "./hooks/AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense.ts";
export { readRolesApiAdminRolesGetQueryKey, readRolesApiAdminRolesGetQueryOptions, useReadRolesApiAdminRolesGet } from "./hooks/AdminHooks/useReadRolesApiAdminRolesGet.ts";
export { readRolesApiAdminRolesGetSuspenseQueryKey, readRolesApiAdminRolesGetSuspenseQueryOptions, useReadRolesApiAdminRolesGetSuspense } from "./hooks/AdminHooks/useReadRolesApiAdminRolesGetSuspense.ts";
export { authChangePasswordMutationKey, authChangePasswordMutationOptions, useAuthChangePassword } from "./hooks/AuthHooks/useAuthChangePassword.ts";
export { authCheckTokenQueryKey, authCheckTokenQueryOptions, useAuthCheckToken } from "./hooks/AuthHooks/useAuthCheckToken.ts";
export { authCheckTokenSuspenseQueryKey, authCheckTokenSuspenseQueryOptions, useAuthCheckTokenSuspense } from "./hooks/AuthHooks/useAuthCheckTokenSuspense.ts";
export { authConfirmEmailQueryKey, authConfirmEmailQueryOptions, useAuthConfirmEmail } from "./hooks/AuthHooks/useAuthConfirmEmail.ts";
export { authConfirmEmailSuspenseQueryKey, authConfirmEmailSuspenseQueryOptions, useAuthConfirmEmailSuspense } from "./hooks/AuthHooks/useAuthConfirmEmailSuspense.ts";
export { authLoginMutationKey, authLoginMutationOptions, useAuthLogin } from "./hooks/AuthHooks/useAuthLogin.ts";
export { authLogoutMutationKey, authLogoutMutationOptions, useAuthLogout } from "./hooks/AuthHooks/useAuthLogout.ts";
export { authPasswordResetMutationKey, authPasswordResetMutationOptions, useAuthPasswordReset } from "./hooks/AuthHooks/useAuthPasswordReset.ts";
export { authPasswordResetWithTokenMutationKey, authPasswordResetWithTokenMutationOptions, useAuthPasswordResetWithToken } from "./hooks/AuthHooks/useAuthPasswordResetWithToken.ts";
export { authRegisterMutationKey, authRegisterMutationOptions, useAuthRegister } from "./hooks/AuthHooks/useAuthRegister.ts";
export { getDocumentationApiDocsGetQueryKey, getDocumentationApiDocsGetQueryOptions, useGetDocumentationApiDocsGet } from "./hooks/DefaultHooks/useGetDocumentationApiDocsGet.ts";
export { getDocumentationApiDocsGetSuspenseQueryKey, getDocumentationApiDocsGetSuspenseQueryOptions, useGetDocumentationApiDocsGetSuspense } from "./hooks/DefaultHooks/useGetDocumentationApiDocsGetSuspense.ts";
export { getRedocDocumentationApiRedocGetQueryKey, getRedocDocumentationApiRedocGetQueryOptions, useGetRedocDocumentationApiRedocGet } from "./hooks/DefaultHooks/useGetRedocDocumentationApiRedocGet.ts";
export { getRedocDocumentationApiRedocGetSuspenseQueryKey, getRedocDocumentationApiRedocGetSuspenseQueryOptions, useGetRedocDocumentationApiRedocGetSuspense } from "./hooks/DefaultHooks/useGetRedocDocumentationApiRedocGetSuspense.ts";
export { openapiApiOpenapiJsonGetQueryKey, openapiApiOpenapiJsonGetQueryOptions, useOpenapiApiOpenapiJsonGet } from "./hooks/DefaultHooks/useOpenapiApiOpenapiJsonGet.ts";
export { openapiApiOpenapiJsonGetSuspenseQueryKey, openapiApiOpenapiJsonGetSuspenseQueryOptions, useOpenapiApiOpenapiJsonGetSuspense } from "./hooks/DefaultHooks/useOpenapiApiOpenapiJsonGetSuspense.ts";
export { healthCheckApiHealthGetQueryKey, healthCheckApiHealthGetQueryOptions, useHealthCheckApiHealthGet } from "./hooks/HealthHooks/useHealthCheckApiHealthGet.ts";
export { healthCheckApiHealthGetSuspenseQueryKey, healthCheckApiHealthGetSuspenseQueryOptions, useHealthCheckApiHealthGetSuspense } from "./hooks/HealthHooks/useHealthCheckApiHealthGetSuspense.ts";
export { deleteStudentMutationKey, deleteStudentMutationOptions, useDeleteStudent } from "./hooks/StudentsHooks/useDeleteStudent.ts";
export { newStudentMutationKey, newStudentMutationOptions, useNewStudent } from "./hooks/StudentsHooks/useNewStudent.ts";
export { studentsQueryKey, studentsQueryOptions, useStudents, studentsMutationKey, studentsMutationOptions } from "./hooks/StudentsHooks/useStudents.ts";
export { studentsSearchQueryKey, studentsSearchQueryOptions, useStudentsSearch } from "./hooks/StudentsHooks/useStudentsSearch.ts";
export { studentsSearchSuspenseQueryKey, studentsSearchSuspenseQueryOptions, useStudentsSearchSuspense } from "./hooks/StudentsHooks/useStudentsSearchSuspense.ts";
export { studentsStudentIDQueryKey, studentsStudentIDQueryOptions, useStudentsStudentID } from "./hooks/StudentsHooks/useStudentsStudentID.ts";
export { studentsStudentIDSuspenseQueryKey, studentsStudentIDSuspenseQueryOptions, useStudentsStudentIDSuspense } from "./hooks/StudentsHooks/useStudentsStudentIDSuspense.ts";
export { studentsSuspenseQueryKey, studentsSuspenseQueryOptions, useStudentsSuspense } from "./hooks/StudentsHooks/useStudentsSuspense.ts";
export { studentsSubtasksQueryKey, studentsSubtasksQueryOptions, useStudentsSubtasks } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasks.ts";
export { studentsSubtasksAssignSubtasksQueryKey, studentsSubtasksAssignSubtasksQueryOptions, useStudentsSubtasksAssignSubtasks } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasks.ts";
export { studentsSubtasksAssignSubtasksSuspenseQueryKey, studentsSubtasksAssignSubtasksSuspenseQueryOptions, useStudentsSubtasksAssignSubtasksSuspense } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasksSuspense.ts";
export { studentsSubtasksSuspenseQueryKey, studentsSubtasksSuspenseQueryOptions, useStudentsSubtasksSuspense } from "./hooks/StudentsSubtasksHooks/useStudentsSubtasksSuspense.ts";
export { subjectsQueryKey, subjectsQueryOptions, useSubjects } from "./hooks/SubjectsHooks/useSubjects.ts";
export { subjectsSubjectIDQueryKey, subjectsSubjectIDQueryOptions, useSubjectsSubjectID } from "./hooks/SubjectsHooks/useSubjectsSubjectID.ts";
export { subjectsSubjectIDSuspenseQueryKey, subjectsSubjectIDSuspenseQueryOptions, useSubjectsSubjectIDSuspense } from "./hooks/SubjectsHooks/useSubjectsSubjectIDSuspense.ts";
export { subjectsSuspenseQueryKey, subjectsSuspenseQueryOptions, useSubjectsSuspense } from "./hooks/SubjectsHooks/useSubjectsSuspense.ts";
export { subtasksQueryKey, subtasksQueryOptions, useSubtasks } from "./hooks/SubtasksHooks/useSubtasks.ts";
export { subtasksCreateMutationKey, subtasksCreateMutationOptions, useSubtasksCreate } from "./hooks/SubtasksHooks/useSubtasksCreate.ts";
export { subtasksDeleteSubtaskIDMutationKey, subtasksDeleteSubtaskIDMutationOptions, useSubtasksDeleteSubtaskID } from "./hooks/SubtasksHooks/useSubtasksDeleteSubtaskID.ts";
export { subtasksSubtaskIDQueryKey, subtasksSubtaskIDQueryOptions, useSubtasksSubtaskID } from "./hooks/SubtasksHooks/useSubtasksSubtaskID.ts";
export { subtasksSubtaskIDSuspenseQueryKey, subtasksSubtaskIDSuspenseQueryOptions, useSubtasksSubtaskIDSuspense } from "./hooks/SubtasksHooks/useSubtasksSubtaskIDSuspense.ts";
export { subtasksSuspenseQueryKey, subtasksSuspenseQueryOptions, useSubtasksSuspense } from "./hooks/SubtasksHooks/useSubtasksSuspense.ts";
export { subtasksUpdateSubtaskIDMutationKey, subtasksUpdateSubtaskIDMutationOptions, useSubtasksUpdateSubtaskID } from "./hooks/SubtasksHooks/useSubtasksUpdateSubtaskID.ts";
export { tasksQueryKey, tasksQueryOptions, useTasks } from "./hooks/TasksHooks/useTasks.ts";
export { tasksSuspenseQueryKey, tasksSuspenseQueryOptions, useTasksSuspense } from "./hooks/TasksHooks/useTasksSuspense.ts";
export { tasksTaskIDQueryKey, tasksTaskIDQueryOptions, useTasksTaskID } from "./hooks/TasksHooks/useTasksTaskID.ts";
export { tasksTaskIDSuspenseQueryKey, tasksTaskIDSuspenseQueryOptions, useTasksTaskIDSuspense } from "./hooks/TasksHooks/useTasksTaskIDSuspense.ts";
export { variantsQueryKey, variantsQueryOptions, useVariants } from "./hooks/VariantsHooks/useVariants.ts";
export { variantsExecVariantIDStudentIDQueryKey, variantsExecVariantIDStudentIDQueryOptions, useVariantsExecVariantIDStudentID } from "./hooks/VariantsHooks/useVariantsExecVariantIDStudentID.ts";
export { variantsExecVariantIDStudentIDSuspenseQueryKey, variantsExecVariantIDStudentIDSuspenseQueryOptions, useVariantsExecVariantIDStudentIDSuspense } from "./hooks/VariantsHooks/useVariantsExecVariantIDStudentIDSuspense.ts";
export { variantsSuspenseQueryKey, variantsSuspenseQueryOptions, useVariantsSuspense } from "./hooks/VariantsHooks/useVariantsSuspense.ts";
export { variantsVariantIDQueryKey, variantsVariantIDQueryOptions, useVariantsVariantID } from "./hooks/VariantsHooks/useVariantsVariantID.ts";
export { variantsVariantIDSuspenseQueryKey, variantsVariantIDSuspenseQueryOptions, useVariantsVariantIDSuspense } from "./hooks/VariantsHooks/useVariantsVariantIDSuspense.ts";
export { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost } from "./services/AdminService/adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export { AdminService } from "./services/AdminService/AdminService.ts";
export { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost } from "./services/AdminService/assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost } from "./services/AdminService/assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export { getLogsApiAdminStudentsLogsGet } from "./services/AdminService/getLogsApiAdminStudentsLogsGet.ts";
export { getLogsApiAdminStudentsStudentIDLogsGet } from "./services/AdminService/getLogsApiAdminStudentsStudentIDLogsGet.ts";
export { readAllStudentsApiAdminStudentsGet } from "./services/AdminService/readAllStudentsApiAdminStudentsGet.ts";
export { readPermissionApiAdminPermissionGet } from "./services/AdminService/readPermissionApiAdminPermissionGet.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGet } from "./services/AdminService/readPermissionsRoleApiAdminRolesRoleIdGet.ts";
export { readRolesApiAdminRolesGet } from "./services/AdminService/readRolesApiAdminRolesGet.ts";
export { authChangePassword } from "./services/AuthService/authChangePassword.ts";
export { authCheckToken } from "./services/AuthService/authCheckToken.ts";
export { authConfirmEmail } from "./services/AuthService/authConfirmEmail.ts";
export { authLogin } from "./services/AuthService/authLogin.ts";
export { authLogout } from "./services/AuthService/authLogout.ts";
export { authPasswordReset } from "./services/AuthService/authPasswordReset.ts";
export { authPasswordResetWithToken } from "./services/AuthService/authPasswordResetWithToken.ts";
export { authRegister } from "./services/AuthService/authRegister.ts";
export { AuthService } from "./services/AuthService/AuthService.ts";
export { getDocumentationApiDocsGet } from "./services/DefaultService/getDocumentationApiDocsGet.ts";
export { getRedocDocumentationApiRedocGet } from "./services/DefaultService/getRedocDocumentationApiRedocGet.ts";
export { openapiApiOpenapiJsonGet } from "./services/DefaultService/openapiApiOpenapiJsonGet.ts";
export { healthCheckApiHealthGet } from "./services/HealthService/healthCheckApiHealthGet.ts";
export { HealthService } from "./services/HealthService/HealthService.ts";
export { deleteStudent } from "./services/StudentsService/deleteStudent.ts";
export { editStudent } from "./services/StudentsService/editStudent.ts";
export { newStudent } from "./services/StudentsService/newStudent.ts";
export { students } from "./services/StudentsService/students.ts";
export { studentsSearch } from "./services/StudentsService/studentsSearch.ts";
export { StudentsService } from "./services/StudentsService/StudentsService.ts";
export { studentsStudentID } from "./services/StudentsService/studentsStudentID.ts";
export { studentsSubtasks } from "./services/StudentsSubtasksService/studentsSubtasks.ts";
export { studentsSubtasksAssignSubtasks } from "./services/StudentsSubtasksService/studentsSubtasksAssignSubtasks.ts";
export { StudentsSubtasksService } from "./services/StudentsSubtasksService/StudentsSubtasksService.ts";
export { subjects } from "./services/SubjectsService/subjects.ts";
export { SubjectsService } from "./services/SubjectsService/SubjectsService.ts";
export { subjectsSubjectID } from "./services/SubjectsService/subjectsSubjectID.ts";
export { subtasks } from "./services/SubtasksService/subtasks.ts";
export { subtasksCreate } from "./services/SubtasksService/subtasksCreate.ts";
export { subtasksDeleteSubtaskID } from "./services/SubtasksService/subtasksDeleteSubtaskID.ts";
export { SubtasksService } from "./services/SubtasksService/SubtasksService.ts";
export { subtasksSubtaskID } from "./services/SubtasksService/subtasksSubtaskID.ts";
export { subtasksUpdateSubtaskID } from "./services/SubtasksService/subtasksUpdateSubtaskID.ts";
export { tasks } from "./services/TasksService/tasks.ts";
export { TasksService } from "./services/TasksService/TasksService.ts";
export { tasksTaskID } from "./services/TasksService/tasksTaskID.ts";
export { variants } from "./services/VariantsService/variants.ts";
export { variantsExecVariantIDStudentID } from "./services/VariantsService/variantsExecVariantIDStudentID.ts";
export { VariantsService } from "./services/VariantsService/VariantsService.ts";
export { variantsVariantID } from "./services/VariantsService/variantsVariantID.ts";
export { SortableFieldsEnum } from "./types/SortableFields.ts";
export { SortDirectionEnum } from "./types/SortDirection.ts";
export { StudentFieldEnum } from "./types/StudentField.ts";
export { adminChangePasswordRequestSchema } from "./zod/adminChangePasswordRequestSchema.ts";
export { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParamsSchema, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200Schema, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422Schema, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequestSchema, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponseSchema } from "./zod/AdminSchemas/adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostSchema.ts";
export { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParamsSchema, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200Schema, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422Schema, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequestSchema, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponseSchema } from "./zod/AdminSchemas/assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostSchema.ts";
export { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParamsSchema, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParamsSchema, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200Schema, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422Schema, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponseSchema } from "./zod/AdminSchemas/assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostSchema.ts";
export { getLogsApiAdminStudentsLogsGetQueryParamsSchema, getLogsApiAdminStudentsLogsGet200Schema, getLogsApiAdminStudentsLogsGet422Schema, getLogsApiAdminStudentsLogsGetQueryResponseSchema } from "./zod/AdminSchemas/getLogsApiAdminStudentsLogsGetSchema.ts";
export { getLogsApiAdminStudentsStudentIDLogsGetPathParamsSchema, getLogsApiAdminStudentsStudentIDLogsGet200Schema, getLogsApiAdminStudentsStudentIDLogsGet422Schema, getLogsApiAdminStudentsStudentIDLogsGetQueryResponseSchema } from "./zod/AdminSchemas/getLogsApiAdminStudentsStudentIDLogsGetSchema.ts";
export { readAllStudentsApiAdminStudentsGet200Schema, readAllStudentsApiAdminStudentsGetQueryResponseSchema } from "./zod/AdminSchemas/readAllStudentsApiAdminStudentsGetSchema.ts";
export { readPermissionApiAdminPermissionGet200Schema, readPermissionApiAdminPermissionGetQueryResponseSchema } from "./zod/AdminSchemas/readPermissionApiAdminPermissionGetSchema.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGetPathParamsSchema, readPermissionsRoleApiAdminRolesRoleIdGet200Schema, readPermissionsRoleApiAdminRolesRoleIdGet422Schema, readPermissionsRoleApiAdminRolesRoleIdGetQueryResponseSchema } from "./zod/AdminSchemas/readPermissionsRoleApiAdminRolesRoleIdGetSchema.ts";
export { readRolesApiAdminRolesGet200Schema, readRolesApiAdminRolesGetQueryResponseSchema } from "./zod/AdminSchemas/readRolesApiAdminRolesGetSchema.ts";
export { assignPermissionsRequestSchema } from "./zod/assignPermissionsRequestSchema.ts";
export { authRequestSchema } from "./zod/authRequestSchema.ts";
export { authChangePassword200Schema, authChangePassword422Schema, authChangePasswordMutationRequestSchema, authChangePasswordMutationResponseSchema } from "./zod/AuthSchemas/authChangePasswordSchema.ts";
export { authCheckToken200Schema, authCheckTokenQueryResponseSchema } from "./zod/AuthSchemas/authCheckTokenSchema.ts";
export { authConfirmEmailQueryParamsSchema, authConfirmEmail200Schema, authConfirmEmail422Schema, authConfirmEmailQueryResponseSchema } from "./zod/AuthSchemas/authConfirmEmailSchema.ts";
export { authLogin200Schema, authLogin422Schema, authLoginMutationRequestSchema, authLoginMutationResponseSchema } from "./zod/AuthSchemas/authLoginSchema.ts";
export { authLogout200Schema, authLogoutMutationResponseSchema } from "./zod/AuthSchemas/authLogoutSchema.ts";
export { authPasswordReset200Schema, authPasswordReset422Schema, authPasswordResetMutationRequestSchema, authPasswordResetMutationResponseSchema } from "./zod/AuthSchemas/authPasswordResetSchema.ts";
export { authPasswordResetWithToken200Schema, authPasswordResetWithToken422Schema, authPasswordResetWithTokenMutationRequestSchema, authPasswordResetWithTokenMutationResponseSchema } from "./zod/AuthSchemas/authPasswordResetWithTokenSchema.ts";
export { authRegister200Schema, authRegister422Schema, authRegisterMutationRequestSchema, authRegisterMutationResponseSchema } from "./zod/AuthSchemas/authRegisterSchema.ts";
export { bodySubtasksCreateSchema } from "./zod/bodySubtasksCreateSchema.ts";
export { bodySubtasksUpdateSubtaskIDSchema } from "./zod/bodySubtasksUpdateSubtaskIDSchema.ts";
export { changePasswordRequestSchema } from "./zod/changePasswordRequestSchema.ts";
export { getDocumentationApiDocsGet200Schema, getDocumentationApiDocsGetQueryResponseSchema } from "./zod/DefaultSchemas/getDocumentationApiDocsGetSchema.ts";
export { getRedocDocumentationApiRedocGet200Schema, getRedocDocumentationApiRedocGetQueryResponseSchema } from "./zod/DefaultSchemas/getRedocDocumentationApiRedocGetSchema.ts";
export { openapiApiOpenapiJsonGet200Schema, openapiApiOpenapiJsonGetQueryResponseSchema } from "./zod/DefaultSchemas/openapiApiOpenapiJsonGetSchema.ts";
export { healthCheckApiHealthGet200Schema, healthCheckApiHealthGetQueryResponseSchema } from "./zod/HealthSchemas/healthCheckApiHealthGetSchema.ts";
export { HTTPValidationErrorSchema } from "./zod/HTTPValidationErrorSchema.ts";
export { passwordResetConfirmSchema } from "./zod/passwordResetConfirmSchema.ts";
export { passwordResetSchema } from "./zod/passwordResetSchema.ts";
export { permissionSchema } from "./zod/permissionSchema.ts";
export { rolesSchema } from "./zod/rolesSchema.ts";
export { sortableFieldsSchema } from "./zod/sortableFieldsSchema.ts";
export { sortDirectionSchema } from "./zod/sortDirectionSchema.ts";
export { studentAuthSchema } from "./zod/studentAuthSchema.ts";
export { studentCreateSchema } from "./zod/studentCreateSchema.ts";
export { studentEditSchema } from "./zod/studentEditSchema.ts";
export { studentFieldSchema } from "./zod/studentFieldSchema.ts";
export { studentOutSchema } from "./zod/studentOutSchema.ts";
export { deleteStudentQueryParamsSchema, deleteStudent200Schema, deleteStudent422Schema, deleteStudentMutationResponseSchema } from "./zod/StudentsSchemas/deleteStudentSchema.ts";
export { editStudentQueryParamsSchema, editStudent200Schema, editStudent422Schema, editStudentMutationRequestSchema, editStudentMutationResponseSchema } from "./zod/StudentsSchemas/editStudentSchema.ts";
export { newStudent200Schema, newStudent422Schema, newStudentMutationRequestSchema, newStudentMutationResponseSchema } from "./zod/StudentsSchemas/newStudentSchema.ts";
export { students200Schema, studentsQueryResponseSchema, studentsQueryParamsSchema, students422Schema, studentsMutationResponseSchema } from "./zod/StudentsSchemas/studentsSchema.ts";
export { studentsSearchQueryParamsSchema, studentsSearch200Schema, studentsSearch422Schema, studentsSearchQueryResponseSchema } from "./zod/StudentsSchemas/studentsSearchSchema.ts";
export { studentsStudentIDPathParamsSchema, studentsStudentID200Schema, studentsStudentID422Schema, studentsStudentIDQueryResponseSchema } from "./zod/StudentsSchemas/studentsStudentIDSchema.ts";
export { studentsSubtasksAssignSubtasksQueryParamsSchema, studentsSubtasksAssignSubtasks200Schema, studentsSubtasksAssignSubtasks422Schema, studentsSubtasksAssignSubtasksQueryResponseSchema } from "./zod/StudentsSubtasksSchemas/studentsSubtasksAssignSubtasksSchema.ts";
export { studentsSubtasksQueryParamsSchema, studentsSubtasks200Schema, studentsSubtasks422Schema, studentsSubtasksQueryResponseSchema } from "./zod/StudentsSubtasksSchemas/studentsSubtasksSchema.ts";
export { studentTaskReadSchema } from "./zod/studentTaskReadSchema.ts";
export { subjectListResponseSchema } from "./zod/subjectListResponseSchema.ts";
export { subjectReadSchema } from "./zod/subjectReadSchema.ts";
export { subjects200Schema, subjectsQueryResponseSchema } from "./zod/SubjectsSchemas/subjectsSchema.ts";
export { subjectsSubjectIDPathParamsSchema, subjectsSubjectID200Schema, subjectsSubjectID422Schema, subjectsSubjectIDQueryResponseSchema } from "./zod/SubjectsSchemas/subjectsSubjectIDSchema.ts";
export { subtasksCreate200Schema, subtasksCreate422Schema, subtasksCreateMutationRequestSchema, subtasksCreateMutationResponseSchema } from "./zod/SubtasksSchemas/subtasksCreateSchema.ts";
export { subtasksDeleteSubtaskIDPathParamsSchema, subtasksDeleteSubtaskID200Schema, subtasksDeleteSubtaskID422Schema, subtasksDeleteSubtaskIDMutationResponseSchema } from "./zod/SubtasksSchemas/subtasksDeleteSubtaskIDSchema.ts";
export { subtasksQueryParamsSchema, subtasks200Schema, subtasks422Schema, subtasksQueryResponseSchema } from "./zod/SubtasksSchemas/subtasksSchema.ts";
export { subtasksSubtaskIDPathParamsSchema, subtasksSubtaskID200Schema, subtasksSubtaskID422Schema, subtasksSubtaskIDQueryResponseSchema } from "./zod/SubtasksSchemas/subtasksSubtaskIDSchema.ts";
export { subtasksUpdateSubtaskIDPathParamsSchema, subtasksUpdateSubtaskID200Schema, subtasksUpdateSubtaskID422Schema, subtasksUpdateSubtaskIDMutationRequestSchema, subtasksUpdateSubtaskIDMutationResponseSchema } from "./zod/SubtasksSchemas/subtasksUpdateSubtaskIDSchema.ts";
export { taskListResponseSchema } from "./zod/taskListResponseSchema.ts";
export { taskReadSchema } from "./zod/taskReadSchema.ts";
export { tasksQueryParamsSchema, tasks200Schema, tasks422Schema, tasksQueryResponseSchema } from "./zod/TasksSchemas/tasksSchema.ts";
export { tasksTaskIDPathParamsSchema, tasksTaskID200Schema, tasksTaskID422Schema, tasksTaskIDQueryResponseSchema } from "./zod/TasksSchemas/tasksTaskIDSchema.ts";
export { tokenWithStudentSchema } from "./zod/tokenWithStudentSchema.ts";
export { userCreateSchema } from "./zod/userCreateSchema.ts";
export { validationErrorSchema } from "./zod/validationErrorSchema.ts";
export { variantsExecVariantIDStudentIDPathParamsSchema, variantsExecVariantIDStudentID200Schema, variantsExecVariantIDStudentID422Schema, variantsExecVariantIDStudentIDQueryResponseSchema } from "./zod/VariantsSchemas/variantsExecVariantIDStudentIDSchema.ts";
export { variantsQueryParamsSchema, variants200Schema, variants422Schema, variantsQueryResponseSchema } from "./zod/VariantsSchemas/variantsSchema.ts";
export { variantsVariantIDPathParamsSchema, variantsVariantID200Schema, variantsVariantID422Schema, variantsVariantIDQueryResponseSchema } from "./zod/VariantsSchemas/variantsVariantIDSchema.ts";