export type { DeleteStudentMutationKey } from "./useDeleteStudent.ts";
export type { NewStudentMutationKey } from "./useNewStudent.ts";
export type { StudentsQueryKey, StudentsMutationKey } from "./useStudents.ts";
export type { StudentsSearchQueryKey } from "./useStudentsSearch.ts";
export type { StudentsSearchSuspenseQueryKey } from "./useStudentsSearchSuspense.ts";
export type { StudentsStudentIDQueryKey } from "./useStudentsStudentID.ts";
export type { StudentsStudentIDSuspenseQueryKey } from "./useStudentsStudentIDSuspense.ts";
export type { StudentsSuspenseQueryKey } from "./useStudentsSuspense.ts";
export { deleteStudentMutationKey, deleteStudentMutationOptions, useDeleteStudent } from "./useDeleteStudent.ts";
export { newStudentMutationKey, newStudentMutationOptions, useNewStudent } from "./useNewStudent.ts";
export { studentsQueryKey, studentsQueryOptions, useStudents, studentsMutationKey, studentsMutationOptions } from "./useStudents.ts";
export { studentsSearchQueryKey, studentsSearchQueryOptions, useStudentsSearch } from "./useStudentsSearch.ts";
export { studentsSearchSuspenseQueryKey, studentsSearchSuspenseQueryOptions, useStudentsSearchSuspense } from "./useStudentsSearchSuspense.ts";
export { studentsStudentIDQueryKey, studentsStudentIDQueryOptions, useStudentsStudentID } from "./useStudentsStudentID.ts";
export { studentsStudentIDSuspenseQueryKey, studentsStudentIDSuspenseQueryOptions, useStudentsStudentIDSuspense } from "./useStudentsStudentIDSuspense.ts";
export { studentsSuspenseQueryKey, studentsSuspenseQueryOptions, useStudentsSuspense } from "./useStudentsSuspense.ts";