/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteStudentMutationResponse, DeleteStudentQueryParams, DeleteStudent422 } from "../../types/Students/DeleteStudent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { deleteStudent } from "../../services/StudentsService/deleteStudent.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const deleteStudentMutationKey = () => [{ url: '/api/students/delete_student' }] as const

export type DeleteStudentMutationKey = ReturnType<typeof deleteStudentMutationKey>

export function deleteStudentMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = deleteStudentMutationKey()
  return mutationOptions<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, {params: DeleteStudentQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ params }) => {
      return deleteStudent(params, config)
    },
  })
}

/**
 * @summary Удаление студента выбранному полю
 * {@link /api/students/delete_student}
 */
export function useDeleteStudent<TContext>(options: 
{
  mutation?: UseMutationOptions<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, {params: DeleteStudentQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? deleteStudentMutationKey()

  const baseOptions = deleteStudentMutationOptions(config) as UseMutationOptions<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, {params: DeleteStudentQueryParams}, TContext>

  return useMutation<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, {params: DeleteStudentQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, {params: DeleteStudentQueryParams}, TContext>
}