/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NewStudentMutationRequest, NewStudentMutationResponse, NewStudent422 } from "../../types/Students/NewStudent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { newStudent } from "../../services/StudentsService/newStudent.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const newStudentMutationKey = () => [{ url: '/api/students/new_student' }] as const

export type NewStudentMutationKey = ReturnType<typeof newStudentMutationKey>

export function newStudentMutationOptions(config: Partial<RequestConfig<NewStudentMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = newStudentMutationKey()
  return mutationOptions<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, {data: NewStudentMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return newStudent(data, config)
    },
  })
}

/**
 * @description `Login`, `email` обязательный поля  (должны быть уникальными)    `Sex` может быть: М, Ж, пустой      `RoleID` именно id роли, а не её имя    `Phone` строка, но должна состоять из цифр
 * @summary Добавить нового студента
 * {@link /api/students/new_student}
 */
export function useNewStudent<TContext>(options: 
{
  mutation?: UseMutationOptions<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, {data: NewStudentMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<NewStudentMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? newStudentMutationKey()

  const baseOptions = newStudentMutationOptions(config) as UseMutationOptions<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, {data: NewStudentMutationRequest}, TContext>

  return useMutation<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, {data: NewStudentMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, {data: NewStudentMutationRequest}, TContext>
}