/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsStudentIDQueryResponse, StudentsStudentIDPathParams, StudentsStudentID422 } from "../../types/Students/StudentsStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { studentsStudentID } from "../../services/StudentsService/studentsStudentID.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const studentsStudentIDQueryKey = (student_id: StudentsStudentIDPathParams["student_id"]) => [{ url: '/api/students/api/:student_id', params: {student_id:student_id} }] as const

export type StudentsStudentIDQueryKey = ReturnType<typeof studentsStudentIDQueryKey>

export function studentsStudentIDQueryOptions(student_id: StudentsStudentIDPathParams["student_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsStudentIDQueryKey(student_id)
  return queryOptions<StudentsStudentIDQueryResponse, ResponseErrorConfig<StudentsStudentID422>, StudentsStudentIDQueryResponse, typeof queryKey>({
   enabled: !!(student_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsStudentID(student_id, config)
   },
  })
}

/**
 * @summary Получить студента по его ID)
 * {@link /api/students/api/:student_id}
 */
export function useStudentsStudentID<TData = StudentsStudentIDQueryResponse, TQueryData = StudentsStudentIDQueryResponse, TQueryKey extends QueryKey = StudentsStudentIDQueryKey>(student_id: StudentsStudentIDPathParams["student_id"], options: 
{
  query?: Partial<QueryObserverOptions<StudentsStudentIDQueryResponse, ResponseErrorConfig<StudentsStudentID422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsStudentIDQueryKey(student_id)

  const query = useQuery({
   ...studentsStudentIDQueryOptions(student_id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<StudentsStudentID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}