/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsQueryResponse, StudentsMutationResponse, StudentsQueryParams, Students422 } from "../../types/Students/Students.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult, UseMutationOptions, UseMutationResult } from "@tanstack/react-query";
import { students } from "../../services/StudentsService/students.ts";
import { queryOptions, useQuery, mutationOptions, useMutation } from "@tanstack/react-query";

export const studentsQueryKey = () => [{ url: '/api/students' }] as const

export type StudentsQueryKey = ReturnType<typeof studentsQueryKey>

export function studentsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsQueryKey()
  return queryOptions<StudentsQueryResponse, ResponseErrorConfig<Error>, StudentsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return students(config)
   },
  })
}

/**
 * @summary Получить список студентов в формате JSON
 * {@link /api/students}
 */
export function useStudents<TData = StudentsQueryResponse, TQueryData = StudentsQueryResponse, TQueryKey extends QueryKey = StudentsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<StudentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsQueryKey()

  const query = useQuery({
   ...studentsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}

export const studentsMutationKey = () => [{ url: '/api/students/active' }] as const

export type StudentsMutationKey = ReturnType<typeof studentsMutationKey>

export function studentsMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = studentsMutationKey()
  return mutationOptions<StudentsMutationResponse, ResponseErrorConfig<Students422>, {params: StudentsQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ params }) => {
      return students(params, config)
    },
  })
}

/**
 * @summary Активация/деакцтивация студента
 * {@link /api/students/active}
 */
export function useStudents<TContext>(options: 
{
  mutation?: UseMutationOptions<StudentsMutationResponse, ResponseErrorConfig<Students422>, {params: StudentsQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? studentsMutationKey()

  const baseOptions = studentsMutationOptions(config) as UseMutationOptions<StudentsMutationResponse, ResponseErrorConfig<Students422>, {params: StudentsQueryParams}, TContext>

  return useMutation<StudentsMutationResponse, ResponseErrorConfig<Students422>, {params: StudentsQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<StudentsMutationResponse, ResponseErrorConfig<Students422>, {params: StudentsQueryParams}, TContext>
}