/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsQueryResponse } from "../../types/Students/Students.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { students } from "../../services/StudentsService/students.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const studentsSuspenseQueryKey = () => [{ url: '/api/students' }] as const

export type StudentsSuspenseQueryKey = ReturnType<typeof studentsSuspenseQueryKey>

export function studentsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSuspenseQueryKey()
  return queryOptions<StudentsQueryResponse, ResponseErrorConfig<Error>, StudentsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return students(config)
   },
  })
}

/**
 * @summary Получить список студентов в формате JSON
 * {@link /api/students}
 */
export function useStudentsSuspense<TData = StudentsQueryResponse, TQueryKey extends QueryKey = StudentsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<StudentsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...studentsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}