/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSearchQueryResponse, StudentsSearchQueryParams, StudentsSearch422 } from "../../types/Students/StudentsSearch.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { studentsSearch } from "../../services/StudentsService/studentsSearch.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const studentsSearchSuspenseQueryKey = (params: StudentsSearchQueryParams) => [{ url: '/api/students/search' }, ...(params ? [params] : [])] as const

export type StudentsSearchSuspenseQueryKey = ReturnType<typeof studentsSearchSuspenseQueryKey>

export function studentsSearchSuspenseQueryOptions(params: StudentsSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSearchSuspenseQueryKey(params)
  return queryOptions<StudentsSearchQueryResponse, ResponseErrorConfig<StudentsSearch422>, StudentsSearchQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsSearch(params, config)
   },
  })
}

/**
 * @summary Поиск студента по выбранному полю(ID, Login, Email, Phone
 * {@link /api/students/search}
 */
export function useStudentsSearchSuspense<TData = StudentsSearchQueryResponse, TQueryKey extends QueryKey = StudentsSearchSuspenseQueryKey>(params: StudentsSearchQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<StudentsSearchQueryResponse, ResponseErrorConfig<StudentsSearch422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSearchSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...studentsSearchSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<StudentsSearch422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}