/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSearchQueryResponse, StudentsSearchQueryParams, StudentsSearch422 } from "../../types/Students/StudentsSearch.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { studentsSearch } from "../../services/StudentsService/studentsSearch.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const studentsSearchQueryKey = (params: StudentsSearchQueryParams) => [{ url: '/api/students/search' }, ...(params ? [params] : [])] as const

export type StudentsSearchQueryKey = ReturnType<typeof studentsSearchQueryKey>

export function studentsSearchQueryOptions(params: StudentsSearchQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSearchQueryKey(params)
  return queryOptions<StudentsSearchQueryResponse, ResponseErrorConfig<StudentsSearch422>, StudentsSearchQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsSearch(params, config)
   },
  })
}

/**
 * @summary Поиск студента по выбранному полю(ID, Login, Email, Phone
 * {@link /api/students/search}
 */
export function useStudentsSearch<TData = StudentsSearchQueryResponse, TQueryData = StudentsSearchQueryResponse, TQueryKey extends QueryKey = StudentsSearchQueryKey>(params: StudentsSearchQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<StudentsSearchQueryResponse, ResponseErrorConfig<StudentsSearch422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSearchQueryKey(params)

  const query = useQuery({
   ...studentsSearchQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<StudentsSearch422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}