/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsStudentIDQueryResponse, StudentsStudentIDPathParams, StudentsStudentID422 } from "../../types/Students/StudentsStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { studentsStudentID } from "../../services/StudentsService/studentsStudentID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const studentsStudentIDSuspenseQueryKey = (student_id: StudentsStudentIDPathParams["student_id"]) => [{ url: '/api/students/api/:student_id', params: {student_id:student_id} }] as const

export type StudentsStudentIDSuspenseQueryKey = ReturnType<typeof studentsStudentIDSuspenseQueryKey>

export function studentsStudentIDSuspenseQueryOptions(student_id: StudentsStudentIDPathParams["student_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsStudentIDSuspenseQueryKey(student_id)
  return queryOptions<StudentsStudentIDQueryResponse, ResponseErrorConfig<StudentsStudentID422>, StudentsStudentIDQueryResponse, typeof queryKey>({
   enabled: !!(student_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsStudentID(student_id, config)
   },
  })
}

/**
 * @summary Получить студента по его ID)
 * {@link /api/students/api/:student_id}
 */
export function useStudentsStudentIDSuspense<TData = StudentsStudentIDQueryResponse, TQueryKey extends QueryKey = StudentsStudentIDSuspenseQueryKey>(student_id: StudentsStudentIDPathParams["student_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<StudentsStudentIDQueryResponse, ResponseErrorConfig<StudentsStudentID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsStudentIDSuspenseQueryKey(student_id)

  const query = useSuspenseQuery({
   ...studentsStudentIDSuspenseQueryOptions(student_id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<StudentsStudentID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}