/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422 } from "../../types/Admin/AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost } from "../../services/AdminService/adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey = () => [{ url: '/api/admin/students/:student_id/change-password' }] as const

export type AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey = ReturnType<typeof adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey>

export function adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationOptions(config: Partial<RequestConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey()
  return mutationOptions<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, {student_id: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"], data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ student_id, data }) => {
      return adminChangePasswordApiAdminStudentsStudentIdChangePasswordPost(student_id, data, config)
    },
  })
}

/**
 * @description пароль смены студента администратором
 * @summary Сменить пароль выбранного студента по его id
 * {@link /api/admin/students/:student_id/change-password}
 */
export function useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost<TContext>(options: 
{
  mutation?: UseMutationOptions<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, {student_id: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"], data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey()

  const baseOptions = adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationOptions(config) as UseMutationOptions<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, {student_id: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"], data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest}, TContext>

  return useMutation<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, {student_id: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"], data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, ResponseErrorConfig<AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422>, {student_id: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams["student_id"], data: AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest}, TContext>
}