/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422 } from "../../types/Admin/AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost } from "../../services/AdminService/assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey = () => [{ url: '/api/admin/students/:studentID/assign-role' }] as const

export type AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey = ReturnType<typeof assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey>

export function assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey()
  return mutationOptions<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, {studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"], params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ studentID, params }) => {
      return assignRoleToStudentApiAdminStudentsStudentIDAssignRolePost(studentID, params, config)
    },
  })
}

/**
 * @description требуется токен авторизации                     studentID передается как path **/students/4**                     RoleID передается как query параметр **/assign-role?RoleID=2**
 * @summary Назначить роль студенту по его id с указанием id роли
 * {@link /api/admin/students/:studentID/assign-role}
 */
export function useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost<TContext>(options: 
{
  mutation?: UseMutationOptions<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, {studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"], params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey()

  const baseOptions = assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationOptions(config) as UseMutationOptions<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, {studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"], params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams}, TContext>

  return useMutation<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, {studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"], params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, ResponseErrorConfig<AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422>, {studentID: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams["studentID"], params: AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams}, TContext>
}