/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422 } from "../../types/Admin/AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost } from "../../services/AdminService/assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey = () => [{ url: '/api/admin/roles/:role_id/assign-permission' }] as const

export type AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey = ReturnType<typeof assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey>

export function assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationOptions(config: Partial<RequestConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey()
  return mutationOptions<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, {role_id: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"], data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ role_id, data }) => {
      return assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost(role_id, data, config)
    },
  })
}

/**
 * @description для выбранной роли по её id необходимо передать массив из id разрашений, данный массив и будет назначен для данной роли                   список разрешений можно посмотреть по роуту: /api/admin/permission
 * @summary Назначить разрешения для роли
 * {@link /api/admin/roles/:role_id/assign-permission}
 */
export function useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost<TContext>(options: 
{
  mutation?: UseMutationOptions<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, {role_id: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"], data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey()

  const baseOptions = assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationOptions(config) as UseMutationOptions<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, {role_id: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"], data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest}, TContext>

  return useMutation<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, {role_id: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"], data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, ResponseErrorConfig<AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422>, {role_id: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams["role_id"], data: AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest}, TContext>
}