/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetLogsApiAdminStudentsLogsGetQueryResponse, GetLogsApiAdminStudentsLogsGetQueryParams, GetLogsApiAdminStudentsLogsGet422 } from "../../types/Admin/GetLogsApiAdminStudentsLogsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getLogsApiAdminStudentsLogsGet } from "../../services/AdminService/getLogsApiAdminStudentsLogsGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getLogsApiAdminStudentsLogsGetSuspenseQueryKey = (params?: GetLogsApiAdminStudentsLogsGetQueryParams) => [{ url: '/api/admin/students/logs' }, ...(params ? [params] : [])] as const

export type GetLogsApiAdminStudentsLogsGetSuspenseQueryKey = ReturnType<typeof getLogsApiAdminStudentsLogsGetSuspenseQueryKey>

export function getLogsApiAdminStudentsLogsGetSuspenseQueryOptions(params?: GetLogsApiAdminStudentsLogsGetQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getLogsApiAdminStudentsLogsGetSuspenseQueryKey(params)
  return queryOptions<GetLogsApiAdminStudentsLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsLogsGet422>, GetLogsApiAdminStudentsLogsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getLogsApiAdminStudentsLogsGet(params, config)
   },
  })
}

/**
 * @description Роут доступен только пользователям с разрешением `view_history`.                    `limit`: Сколько логов вернуть (по умолчанию 50, максимум 10000)                    `offset`: Смещение от начала выборки
 * @summary Вывод истории действий всех пользователей
 * {@link /api/admin/students/logs}
 */
export function useGetLogsApiAdminStudentsLogsGetSuspense<TData = GetLogsApiAdminStudentsLogsGetQueryResponse, TQueryKey extends QueryKey = GetLogsApiAdminStudentsLogsGetSuspenseQueryKey>(params?: GetLogsApiAdminStudentsLogsGetQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetLogsApiAdminStudentsLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsLogsGet422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getLogsApiAdminStudentsLogsGetSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...getLogsApiAdminStudentsLogsGetSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetLogsApiAdminStudentsLogsGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}