/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, GetLogsApiAdminStudentsStudentIDLogsGetPathParams, GetLogsApiAdminStudentsStudentIDLogsGet422 } from "../../types/Admin/GetLogsApiAdminStudentsStudentIDLogsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getLogsApiAdminStudentsStudentIDLogsGet } from "../../services/AdminService/getLogsApiAdminStudentsStudentIDLogsGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey = (studentID: GetLogsApiAdminStudentsStudentIDLogsGetPathParams["studentID"]) => [{ url: '/api/admin/students/:studentID/logs', params: {studentID:studentID} }] as const

export type GetLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey = ReturnType<typeof getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey>

export function getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryOptions(studentID: GetLogsApiAdminStudentsStudentIDLogsGetPathParams["studentID"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey(studentID)
  return queryOptions<GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsStudentIDLogsGet422>, GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, typeof queryKey>({
   enabled: !!(studentID),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getLogsApiAdminStudentsStudentIDLogsGet(studentID, config)
   },
  })
}

/**
 * @description данный роут работает для администратора (может смотреть логи любого студента по его id)                    и для текущего авторизованного пользователя (если совпадает его id с studentID из адреса)
 * @summary Вывод истории действий пользователя по его ID
 * {@link /api/admin/students/:studentID/logs}
 */
export function useGetLogsApiAdminStudentsStudentIDLogsGetSuspense<TData = GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, TQueryKey extends QueryKey = GetLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey>(studentID: GetLogsApiAdminStudentsStudentIDLogsGetPathParams["studentID"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, ResponseErrorConfig<GetLogsApiAdminStudentsStudentIDLogsGet422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey(studentID)

  const query = useSuspenseQuery({
   ...getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryOptions(studentID, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetLogsApiAdminStudentsStudentIDLogsGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}