/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadRolesApiAdminRolesGetQueryResponse } from "../../types/Admin/ReadRolesApiAdminRolesGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { readRolesApiAdminRolesGet } from "../../services/AdminService/readRolesApiAdminRolesGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const readRolesApiAdminRolesGetQueryKey = () => [{ url: '/api/admin/roles' }] as const

export type ReadRolesApiAdminRolesGetQueryKey = ReturnType<typeof readRolesApiAdminRolesGetQueryKey>

export function readRolesApiAdminRolesGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readRolesApiAdminRolesGetQueryKey()
  return queryOptions<ReadRolesApiAdminRolesGetQueryResponse, ResponseErrorConfig<Error>, ReadRolesApiAdminRolesGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readRolesApiAdminRolesGet(config)
   },
  })
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех ролей
 * {@link /api/admin/roles}
 */
export function useReadRolesApiAdminRolesGet<TData = ReadRolesApiAdminRolesGetQueryResponse, TQueryData = ReadRolesApiAdminRolesGetQueryResponse, TQueryKey extends QueryKey = ReadRolesApiAdminRolesGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ReadRolesApiAdminRolesGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readRolesApiAdminRolesGetQueryKey()

  const query = useQuery({
   ...readRolesApiAdminRolesGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}