/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadRolesApiAdminRolesGetQueryResponse } from "../../types/Admin/ReadRolesApiAdminRolesGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { readRolesApiAdminRolesGet } from "../../services/AdminService/readRolesApiAdminRolesGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const readRolesApiAdminRolesGetSuspenseQueryKey = () => [{ url: '/api/admin/roles' }] as const

export type ReadRolesApiAdminRolesGetSuspenseQueryKey = ReturnType<typeof readRolesApiAdminRolesGetSuspenseQueryKey>

export function readRolesApiAdminRolesGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readRolesApiAdminRolesGetSuspenseQueryKey()
  return queryOptions<ReadRolesApiAdminRolesGetQueryResponse, ResponseErrorConfig<Error>, ReadRolesApiAdminRolesGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readRolesApiAdminRolesGet(config)
   },
  })
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех ролей
 * {@link /api/admin/roles}
 */
export function useReadRolesApiAdminRolesGetSuspense<TData = ReadRolesApiAdminRolesGetQueryResponse, TQueryKey extends QueryKey = ReadRolesApiAdminRolesGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ReadRolesApiAdminRolesGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readRolesApiAdminRolesGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...readRolesApiAdminRolesGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}