/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadAllStudentsApiAdminStudentsGetQueryResponse } from "../../types/Admin/ReadAllStudentsApiAdminStudentsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { readAllStudentsApiAdminStudentsGet } from "../../services/AdminService/readAllStudentsApiAdminStudentsGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const readAllStudentsApiAdminStudentsGetQueryKey = () => [{ url: '/api/admin/students' }] as const

export type ReadAllStudentsApiAdminStudentsGetQueryKey = ReturnType<typeof readAllStudentsApiAdminStudentsGetQueryKey>

export function readAllStudentsApiAdminStudentsGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readAllStudentsApiAdminStudentsGetQueryKey()
  return queryOptions<ReadAllStudentsApiAdminStudentsGetQueryResponse, ResponseErrorConfig<Error>, ReadAllStudentsApiAdminStudentsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readAllStudentsApiAdminStudentsGet(config)
   },
  })
}

/**
 * @summary Получить список студентов в формате JSON (для админа)
 * {@link /api/admin/students}
 */
export function useReadAllStudentsApiAdminStudentsGet<TData = ReadAllStudentsApiAdminStudentsGetQueryResponse, TQueryData = ReadAllStudentsApiAdminStudentsGetQueryResponse, TQueryKey extends QueryKey = ReadAllStudentsApiAdminStudentsGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ReadAllStudentsApiAdminStudentsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readAllStudentsApiAdminStudentsGetQueryKey()

  const query = useQuery({
   ...readAllStudentsApiAdminStudentsGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}