/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadAllStudentsApiAdminStudentsGetQueryResponse } from "../../types/Admin/ReadAllStudentsApiAdminStudentsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { readAllStudentsApiAdminStudentsGet } from "../../services/AdminService/readAllStudentsApiAdminStudentsGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const readAllStudentsApiAdminStudentsGetSuspenseQueryKey = () => [{ url: '/api/admin/students' }] as const

export type ReadAllStudentsApiAdminStudentsGetSuspenseQueryKey = ReturnType<typeof readAllStudentsApiAdminStudentsGetSuspenseQueryKey>

export function readAllStudentsApiAdminStudentsGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readAllStudentsApiAdminStudentsGetSuspenseQueryKey()
  return queryOptions<ReadAllStudentsApiAdminStudentsGetQueryResponse, ResponseErrorConfig<Error>, ReadAllStudentsApiAdminStudentsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readAllStudentsApiAdminStudentsGet(config)
   },
  })
}

/**
 * @summary Получить список студентов в формате JSON (для админа)
 * {@link /api/admin/students}
 */
export function useReadAllStudentsApiAdminStudentsGetSuspense<TData = ReadAllStudentsApiAdminStudentsGetQueryResponse, TQueryKey extends QueryKey = ReadAllStudentsApiAdminStudentsGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ReadAllStudentsApiAdminStudentsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readAllStudentsApiAdminStudentsGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...readAllStudentsApiAdminStudentsGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}