/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadPermissionApiAdminPermissionGetQueryResponse } from "../../types/Admin/ReadPermissionApiAdminPermissionGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { readPermissionApiAdminPermissionGet } from "../../services/AdminService/readPermissionApiAdminPermissionGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const readPermissionApiAdminPermissionGetSuspenseQueryKey = () => [{ url: '/api/admin/permission' }] as const

export type ReadPermissionApiAdminPermissionGetSuspenseQueryKey = ReturnType<typeof readPermissionApiAdminPermissionGetSuspenseQueryKey>

export function readPermissionApiAdminPermissionGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readPermissionApiAdminPermissionGetSuspenseQueryKey()
  return queryOptions<ReadPermissionApiAdminPermissionGetQueryResponse, ResponseErrorConfig<Error>, ReadPermissionApiAdminPermissionGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readPermissionApiAdminPermissionGet(config)
   },
  })
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех разрешений
 * {@link /api/admin/permission}
 */
export function useReadPermissionApiAdminPermissionGetSuspense<TData = ReadPermissionApiAdminPermissionGetQueryResponse, TQueryKey extends QueryKey = ReadPermissionApiAdminPermissionGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<ReadPermissionApiAdminPermissionGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readPermissionApiAdminPermissionGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...readPermissionApiAdminPermissionGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}