/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadPermissionApiAdminPermissionGetQueryResponse } from "../../types/Admin/ReadPermissionApiAdminPermissionGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { readPermissionApiAdminPermissionGet } from "../../services/AdminService/readPermissionApiAdminPermissionGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const readPermissionApiAdminPermissionGetQueryKey = () => [{ url: '/api/admin/permission' }] as const

export type ReadPermissionApiAdminPermissionGetQueryKey = ReturnType<typeof readPermissionApiAdminPermissionGetQueryKey>

export function readPermissionApiAdminPermissionGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readPermissionApiAdminPermissionGetQueryKey()
  return queryOptions<ReadPermissionApiAdminPermissionGetQueryResponse, ResponseErrorConfig<Error>, ReadPermissionApiAdminPermissionGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readPermissionApiAdminPermissionGet(config)
   },
  })
}

/**
 * @description требуется токен авторизации
 * @summary Получить список всех разрешений
 * {@link /api/admin/permission}
 */
export function useReadPermissionApiAdminPermissionGet<TData = ReadPermissionApiAdminPermissionGetQueryResponse, TQueryData = ReadPermissionApiAdminPermissionGetQueryResponse, TQueryKey extends QueryKey = ReadPermissionApiAdminPermissionGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<ReadPermissionApiAdminPermissionGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readPermissionApiAdminPermissionGetQueryKey()

  const query = useQuery({
   ...readPermissionApiAdminPermissionGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}