/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams, ReadPermissionsRoleApiAdminRolesRoleIdGet422 } from "../../types/Admin/ReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { readPermissionsRoleApiAdminRolesRoleIdGet } from "../../services/AdminService/readPermissionsRoleApiAdminRolesRoleIdGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey = (role_id: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams["role_id"]) => [{ url: '/api/admin/roles/:role_id', params: {role_id:role_id} }] as const

export type ReadPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey = ReturnType<typeof readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey>

export function readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryOptions(role_id: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams["role_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey(role_id)
  return queryOptions<ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ResponseErrorConfig<ReadPermissionsRoleApiAdminRolesRoleIdGet422>, ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, typeof queryKey>({
   enabled: !!(role_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return readPermissionsRoleApiAdminRolesRoleIdGet(role_id, config)
   },
  })
}

/**
 * @summary Получить список разрешения для роли по её id
 * {@link /api/admin/roles/:role_id}
 */
export function useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense<TData = ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, TQueryKey extends QueryKey = ReadPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey>(role_id: ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams["role_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ResponseErrorConfig<ReadPermissionsRoleApiAdminRolesRoleIdGet422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey(role_id)

  const query = useSuspenseQuery({
   ...readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryOptions(role_id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<ReadPermissionsRoleApiAdminRolesRoleIdGet422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}