/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksQueryResponse, TasksQueryParams, Tasks422 } from "../../types/Tasks/Tasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { tasksQueryResponseSchema } from "../../zod/TasksSchemas/tasksSchema.ts";

function getTasksUrl() {
  const res = { method: 'GET', url: `/api/tasks` as const }  
  return res
}

/**
 * @description Если передан параметр **subjectID**, то возвращаются категории только для указанного предмета.          Если параметр не передан, возвращаются категории по всем предметам.          **subjectID** передается как Query-параметр                   "`/api/tasks` — все категории"                  "`/api/tasks?subjectID=10` — категории для предмета с subject ID 10"                  так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список категорий (ЕГЭ_1 ЕГЭ_2, и т.д)
 * {@link /api/tasks}
 */
export async function tasks({ params }: { params?: TasksQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TasksQueryResponse, ResponseErrorConfig<Tasks422>, unknown>({ method : "GET", url : getTasksUrl().url.toString(), params, ... requestConfig })  
  return tasksQueryResponseSchema.parse(res.data)
}