/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { TasksTaskIDQueryResponse, TasksTaskIDPathParams, TasksTaskID422 } from "../../types/Tasks/TasksTaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { tasksTaskIDQueryResponseSchema } from "../../zod/TasksSchemas/tasksTaskIDSchema.ts";

function getTasksTaskIDUrl({ taskId }: { taskId: TasksTaskIDPathParams["task_id"] }) {
  const res = { method: 'GET', url: `/api/tasks/${taskId}` as const }  
  return res
}

/**
 * @summary Получить категорию по его task_id
 * {@link /api/tasks/:task_id}
 */
export async function tasksTaskID({ taskId }: { taskId: TasksTaskIDPathParams["task_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<TasksTaskIDQueryResponse, ResponseErrorConfig<TasksTaskID422>, unknown>({ method : "GET", url : getTasksTaskIDUrl({ taskId }).url.toString(), ... requestConfig })  
  return tasksTaskIDQueryResponseSchema.parse(res.data)
}