/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { tasks } from "./tasks.ts";
import { tasksTaskID } from "./tasksTaskID.ts";

export function TasksService() {
  return { tasks, tasksTaskID }
}