/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentField } from "../StudentField.ts";

export interface DeleteStudentQueryParams {
    field_name?: (StudentField | null);
    /**
     * @type string
    */
    value: string;
}

/**
 * @description Successful Response
*/
export type DeleteStudent200 = unknown;

/**
 * @description Validation Error
*/
export type DeleteStudent422 = HTTPValidationError;

export type DeleteStudentMutationResponse = DeleteStudent200;

export type DeleteStudentMutation = {
    Response: DeleteStudent200;
    QueryParams: DeleteStudentQueryParams;
    Errors: DeleteStudent422;
};