/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentEdit } from "../StudentEdit.ts";

export interface EditStudentQueryParams {
    /**
     * @type integer
    */
    id: number;
}

/**
 * @description Successful Response
*/
export type EditStudent200 = unknown;

/**
 * @description Validation Error
*/
export type EditStudent422 = HTTPValidationError;

export type EditStudentMutationRequest = StudentEdit;

export type EditStudentMutationResponse = EditStudent200;

export type EditStudentMutation = {
    Response: EditStudent200;
    Request: EditStudentMutationRequest;
    QueryParams: EditStudentQueryParams;
    Errors: EditStudent422;
};