/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentCreate } from "../StudentCreate.ts";

/**
 * @description Successful Response
*/
export type NewStudent200 = unknown;

/**
 * @description Validation Error
*/
export type NewStudent422 = HTTPValidationError;

export type NewStudentMutationRequest = StudentCreate;

export type NewStudentMutationResponse = NewStudent200;

export type NewStudentMutation = {
    Response: NewStudent200;
    Request: NewStudentMutationRequest;
    Errors: NewStudent422;
};