/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentAuth } from "../StudentAuth.ts";

export interface StudentsStudentIDPathParams {
    /**
     * @type integer
    */
    student_id: number;
}

/**
 * @description Successful Response
*/
export type StudentsStudentID200 = StudentAuth;

/**
 * @description Validation Error
*/
export type StudentsStudentID422 = HTTPValidationError;

export type StudentsStudentIDQueryResponse = StudentsStudentID200;

export type StudentsStudentIDQuery = {
    Response: StudentsStudentID200;
    PathParams: StudentsStudentIDPathParams;
    Errors: StudentsStudentID422;
};