/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentField } from "../StudentField.ts";

export interface StudentsSearchQueryParams {
    /**
     * @type string
    */
    field_name: StudentField;
    /**
     * @type string
    */
    value: string;
}

/**
 * @description Successful Response
*/
export type StudentsSearch200 = unknown;

/**
 * @description Validation Error
*/
export type StudentsSearch422 = HTTPValidationError;

export type StudentsSearchQueryResponse = StudentsSearch200;

export type StudentsSearchQuery = {
    Response: StudentsSearch200;
    QueryParams: StudentsSearchQueryParams;
    Errors: StudentsSearch422;
};