/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { StudentOut } from "../StudentOut.ts";

/**
 * @description Successful Response
*/
export type Students200 = StudentOut[];

export type StudentsQueryResponse = Students200;

export type StudentsQuery = {
    Response: Students200;
    Errors: any;
};

export interface StudentsQueryParams {
    /**
     * @type integer
    */
    id: number;
    /**
     * @type boolean
    */
    flag: boolean;
}

/**
 * @description Successful Response
*/
export type Students200 = unknown;

/**
 * @description Validation Error
*/
export type Students422 = HTTPValidationError;

export type StudentsMutationResponse = Students200;

export type StudentsMutation = {
    Response: Students200;
    QueryParams: StudentsQueryParams;
    Errors: Students422;
};