/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface StudentsSubtasksAssignSubtasksQueryParams {
    /**
     * @type integer
    */
    student_id: number;
    /**
     * @type integer
    */
    subtask_id: number;
}

/**
 * @description Successful Response
*/
export type StudentsSubtasksAssignSubtasks200 = unknown;

/**
 * @description Validation Error
*/
export type StudentsSubtasksAssignSubtasks422 = HTTPValidationError;

export type StudentsSubtasksAssignSubtasksQueryResponse = StudentsSubtasksAssignSubtasks200;

export type StudentsSubtasksAssignSubtasksQuery = {
    Response: StudentsSubtasksAssignSubtasks200;
    QueryParams: StudentsSubtasksAssignSubtasksQueryParams;
    Errors: StudentsSubtasksAssignSubtasks422;
};