/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { SortableFields } from "../SortableFields.ts";
import type { SortDirection } from "../SortDirection.ts";
import type { StudentTaskRead } from "../StudentTaskRead.ts";

export interface StudentsSubtasksQueryParams {
    student_task_id?: (number | null);
    student_id?: (number | null);
    sub_task_id?: (number | null);
    task_id?: (number | null);
    subject_id?: (number | null);
    variant_id?: (number | null);
    completion_status?: (string | null);
    search?: (string | null);
    /**
     * @default "StartDate"
    */
    sort_column1?: (SortableFields | null);
    sort_column2?: (SortableFields | null);
    /**
     * @default "ASC"
    */
    sort_direction1?: (SortDirection | null);
    sort_direction2?: (SortDirection | null);
    p_limit?: (number | null);
    p_offset?: (number | null);
}

/**
 * @description Successful Response
*/
export type StudentsSubtasks200 = StudentTaskRead[];

/**
 * @description Validation Error
*/
export type StudentsSubtasks422 = HTTPValidationError;

export type StudentsSubtasksQueryResponse = StudentsSubtasks200;

export type StudentsSubtasksQuery = {
    Response: StudentsSubtasks200;
    QueryParams: StudentsSubtasksQueryParams;
    Errors: StudentsSubtasks422;
};