/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksDeleteSubtaskIDMutationResponse, SubtasksDeleteSubtaskIDPathParams, SubtasksDeleteSubtaskID422 } from "../../types/Subtasks/SubtasksDeleteSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subtasksDeleteSubtaskIDMutationResponseSchema } from "../../zod/SubtasksSchemas/subtasksDeleteSubtaskIDSchema.ts";

function getSubtasksDeleteSubtaskIDUrl({ subtaskId }: { subtaskId: SubtasksDeleteSubtaskIDPathParams["subtask_id"] }) {
  const res = { method: 'DELETE', url: `/api/subtasks/delete/${subtaskId}` as const }  
  return res
}

/**
 * @description Удаляет подзадачу, все её файлы и записи из таблиц
 * @summary Удаление подзадачи
 * {@link /api/subtasks/delete/:subtask_id}
 */
export async function subtasksDeleteSubtaskID({ subtaskId }: { subtaskId: SubtasksDeleteSubtaskIDPathParams["subtask_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, unknown>({ method : "DELETE", url : getSubtasksDeleteSubtaskIDUrl({ subtaskId }).url.toString(), ... requestConfig })  
  return subtasksDeleteSubtaskIDMutationResponseSchema.parse(res.data)
}