/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksCreateMutationRequest, SubtasksCreateMutationResponse, SubtasksCreate422 } from "../../types/Subtasks/SubtasksCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subtasksCreateMutationResponseSchema, subtasksCreateMutationRequestSchema } from "../../zod/SubtasksSchemas/subtasksCreateSchema.ts";

function getSubtasksCreateUrl() {
  const res = { method: 'POST', url: `/api/subtasks/create` as const }  
  return res
}

/**
 * @description Создает задачу с текстовыми, графическими и другими блоками.  Поддерживает прикрепление файлов через multipart/form-data.  возвращает `files_blocks` - количество вставленных файлов с изображением задачи  `files_solution` - количество вставленных файлов с решением задачи  `files` - количество вставленных дополнительных файлов к задачи
 * @summary Создание задачи с файлами и блоками
 * {@link /api/subtasks/create}
 */
export async function subtasksCreate({ data }: { data: SubtasksCreateMutationRequest }, config: Partial<RequestConfig<SubtasksCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = subtasksCreateMutationRequestSchema.parse(data)  
  const formData = new FormData()
  if (requestData) {
   Object.keys(requestData).forEach((key) => {
     const value = requestData[key as keyof typeof requestData];
     if (typeof value === 'string' || (value as unknown) instanceof Blob) {
       formData.append(key, value as unknown as string | Blob);
     } else {
       formData.append(key, JSON.stringify(value));
     }
   })
  }  
  const res = await request<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, SubtasksCreateMutationRequest>({ method : "POST", url : getSubtasksCreateUrl().url.toString(), data : formData, ... requestConfig })  
  return subtasksCreateMutationResponseSchema.parse(res.data)
}