/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksUpdateSubtaskIDMutationRequest, SubtasksUpdateSubtaskIDMutationResponse, SubtasksUpdateSubtaskIDPathParams, SubtasksUpdateSubtaskID422 } from "../../types/Subtasks/SubtasksUpdateSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subtasksUpdateSubtaskIDMutationResponseSchema, subtasksUpdateSubtaskIDMutationRequestSchema } from "../../zod/SubtasksSchemas/subtasksUpdateSubtaskIDSchema.ts";

function getSubtasksUpdateSubtaskIDUrl({ subtaskId }: { subtaskId: SubtasksUpdateSubtaskIDPathParams["subtask_id"] }) {
  const res = { method: 'PUT', url: `/api/subtasks/update/${subtaskId}` as const }  
  return res
}

/**
 * @description Заменяет старые значения на новые!(старые файлы удаляются и записываются новые).
 * @summary Полное обновление задачи с блоками и файлами
 * {@link /api/subtasks/update/:subtask_id}
 */
export async function subtasksUpdateSubtaskID({ subtaskId, data }: { subtaskId: SubtasksUpdateSubtaskIDPathParams["subtask_id"]; data: SubtasksUpdateSubtaskIDMutationRequest }, config: Partial<RequestConfig<SubtasksUpdateSubtaskIDMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = subtasksUpdateSubtaskIDMutationRequestSchema.parse(data)  
  const formData = new FormData()
  if (requestData) {
   Object.keys(requestData).forEach((key) => {
     const value = requestData[key as keyof typeof requestData];
     if (typeof value === 'string' || (value as unknown) instanceof Blob) {
       formData.append(key, value as unknown as string | Blob);
     } else {
       formData.append(key, JSON.stringify(value));
     }
   })
  }  
  const res = await request<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, SubtasksUpdateSubtaskIDMutationRequest>({ method : "PUT", url : getSubtasksUpdateSubtaskIDUrl({ subtaskId }).url.toString(), data : formData, ... requestConfig })  
  return subtasksUpdateSubtaskIDMutationResponseSchema.parse(res.data)
}