/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { subtasks } from "./subtasks.ts";
import { subtasksCreate } from "./subtasksCreate.ts";
import { subtasksDeleteSubtaskID } from "./subtasksDeleteSubtaskID.ts";
import { subtasksSubtaskID } from "./subtasksSubtaskID.ts";
import { subtasksUpdateSubtaskID } from "./subtasksUpdateSubtaskID.ts";

export function SubtasksService() {
  return { subtasksCreate, subtasksUpdateSubtaskID, subtasksDeleteSubtaskID, subtasks, subtasksSubtaskID }
}