/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksQueryResponse, SubtasksQueryParams, Subtasks422 } from "../../types/Subtasks/Subtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subtasksQueryResponseSchema } from "../../zod/SubtasksSchemas/subtasksSchema.ts";

function getSubtasksUrl() {
  const res = { method: 'GET', url: `/api/subtasks` as const }  
  return res
}

/**
 * @description Возвращает список всех подзадач с их блоками и прикрепленными файлами.          Подзадачи могут фильтроваться по параметрам: SubTaskID, TaskID, SubjectID, VariantID,           Search, UploadDate, Creator, сортироваться по любым колонкам и ограничиваться диапазоном           через Offset и Limit.
 * @summary Получение всех задач с блоками и дополнительными файлами
 * {@link /api/subtasks}
 */
export async function subtasks({ params }: { params?: SubtasksQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SubtasksQueryResponse, ResponseErrorConfig<Subtasks422>, unknown>({ method : "GET", url : getSubtasksUrl().url.toString(), params, ... requestConfig })  
  return subtasksQueryResponseSchema.parse(res.data)
}