/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksSubtaskIDQueryResponse, SubtasksSubtaskIDPathParams, SubtasksSubtaskID422 } from "../../types/Subtasks/SubtasksSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subtasksSubtaskIDQueryResponseSchema } from "../../zod/SubtasksSchemas/subtasksSubtaskIDSchema.ts";

function getSubtasksSubtaskIDUrl({ subtaskId }: { subtaskId: SubtasksSubtaskIDPathParams["subtask_id"] }) {
  const res = { method: 'GET', url: `/api/subtasks/${subtaskId}` as const }  
  return res
}

/**
 * @description Возвращает задачу с текстовыми, графическими и другими блоками, а также прикрепленные файлы.
 * @summary Получение задачи с блоками и с дополнительными файлами
 * {@link /api/subtasks/:subtask_id}
 */
export async function subtasksSubtaskID({ subtaskId }: { subtaskId: SubtasksSubtaskIDPathParams["subtask_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SubtasksSubtaskIDQueryResponse, ResponseErrorConfig<SubtasksSubtaskID422>, unknown>({ method : "GET", url : getSubtasksSubtaskIDUrl({ subtaskId }).url.toString(), ... requestConfig })  
  return subtasksSubtaskIDQueryResponseSchema.parse(res.data)
}