/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AdminChangePasswordRequest {
    /**
     * @minLength 6
     * @type string
    */
    new_password: string;
}