/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface AuthRequest {
    /**
     * @type string
    */
    identifier: string;
    /**
     * @type string
    */
    password: string;
}