/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface BodySubtasksUpdateSubtaskID {
    /**
     * @description Task_id категории
     * @type integer | undefined
    */
    task_id?: number;
    /**
     * @description Номер задачи в категории
     * @type string | undefined
    */
    subtask_number?: string;
    /**
     * @description ID варианта (если есть)
     * @type integer | undefined
    */
    variant_id?: number;
    /**
     * @description JSON список блоков: [{\"type\":\"image\",\"content\":\"image.png\"},{\"type\":\"text\",\"content\":\"Текст\"}]
     * @type string
    */
    blocks: string;
    /**
     * @description Файлы для блоков
    */
    files_blocks?: (Blob[] | null);
    /**
     * @description Ответ на задачу
     * @type string | undefined
    */
    answer?: string;
    /**
     * @description Файлы решения
    */
    files_solution?: (Blob[] | null);
    /**
     * @description Дополнительные файлы
    */
    files_extra?: (Blob[] | null);
}