/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface BodySubtasksCreate {
    /**
     * @description Task_id категории
     * @type integer | undefined
    */
    task_id?: number;
    /**
     * @description Номер задачи в категории
     * @type string | undefined
    */
    subtask_number?: string;
    /**
     * @description ID варианта (если есть)
     * @type integer | undefined
    */
    variant_id?: number;
    /**
     * @description JSON список блоков: [{\"type\":\"text\",\"content\":\"Текст\"},{\"type\":\"image\",\"content\":\"image.png\"}]
     * @type string
    */
    blocks: string;
    /**
     * @description Список файлов для блоков
     * @type array | undefined
    */
    files_blocks?: Blob[];
    /**
     * @description Ответ на задачу
     * @type string | undefined
    */
    answer?: string;
    /**
     * @description Список файлов для решения
     * @type array | undefined
    */
    files_solution?: Blob[];
    /**
     * @description Список дополнительных файлов к задаче
     * @type array | undefined
    */
    files_extra?: Blob[];
}