/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface ChangePasswordRequest {
    /**
     * @type string
    */
    old_password: string;
    /**
     * @minLength 6
     * @type string
    */
    new_password: string;
    /**
     * @minLength 6
     * @type string
    */
    repeat_new_password: string;
}