/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ValidationError } from "./ValidationError.ts";

export interface HTTPValidationError {
    /**
     * @type array | undefined
    */
    detail?: ValidationError[];
}