export type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostPathParams, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost200, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost422, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationRequest, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationResponse, AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutation } from "./Admin/AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostPathParams, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost200, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost422, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationRequest, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationResponse, AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutation } from "./Admin/AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostPathParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostQueryParams, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost200, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost422, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationResponse, AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutation } from "./Admin/AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export type { GetLogsApiAdminStudentsLogsGetQueryParams, GetLogsApiAdminStudentsLogsGet200, GetLogsApiAdminStudentsLogsGet422, GetLogsApiAdminStudentsLogsGetQueryResponse, GetLogsApiAdminStudentsLogsGetQuery } from "./Admin/GetLogsApiAdminStudentsLogsGet.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetPathParams, GetLogsApiAdminStudentsStudentIDLogsGet200, GetLogsApiAdminStudentsStudentIDLogsGet422, GetLogsApiAdminStudentsStudentIDLogsGetQueryResponse, GetLogsApiAdminStudentsStudentIDLogsGetQuery } from "./Admin/GetLogsApiAdminStudentsStudentIDLogsGet.ts";
export type { ReadAllStudentsApiAdminStudentsGet200, ReadAllStudentsApiAdminStudentsGetQueryResponse, ReadAllStudentsApiAdminStudentsGetQuery } from "./Admin/ReadAllStudentsApiAdminStudentsGet.ts";
export type { ReadPermissionApiAdminPermissionGet200, ReadPermissionApiAdminPermissionGetQueryResponse, ReadPermissionApiAdminPermissionGetQuery } from "./Admin/ReadPermissionApiAdminPermissionGet.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetPathParams, ReadPermissionsRoleApiAdminRolesRoleIdGet200, ReadPermissionsRoleApiAdminRolesRoleIdGet422, ReadPermissionsRoleApiAdminRolesRoleIdGetQueryResponse, ReadPermissionsRoleApiAdminRolesRoleIdGetQuery } from "./Admin/ReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export type { ReadRolesApiAdminRolesGet200, ReadRolesApiAdminRolesGetQueryResponse, ReadRolesApiAdminRolesGetQuery } from "./Admin/ReadRolesApiAdminRolesGet.ts";
export type { AdminChangePasswordRequest } from "./AdminChangePasswordRequest.ts";
export type { AssignPermissionsRequest } from "./AssignPermissionsRequest.ts";
export type { AuthChangePassword200, AuthChangePassword422, AuthChangePasswordMutationRequest, AuthChangePasswordMutationResponse, AuthChangePasswordMutation } from "./Auth/AuthChangePassword.ts";
export type { AuthCheckToken200, AuthCheckTokenQueryResponse, AuthCheckTokenQuery } from "./Auth/AuthCheckToken.ts";
export type { AuthConfirmEmailQueryParams, AuthConfirmEmail200, AuthConfirmEmail422, AuthConfirmEmailQueryResponse, AuthConfirmEmailQuery } from "./Auth/AuthConfirmEmail.ts";
export type { AuthLogin200, AuthLogin422, AuthLoginMutationRequest, AuthLoginMutationResponse, AuthLoginMutation } from "./Auth/AuthLogin.ts";
export type { AuthLogout200, AuthLogoutMutationResponse, AuthLogoutMutation } from "./Auth/AuthLogout.ts";
export type { AuthPasswordReset200, AuthPasswordReset422, AuthPasswordResetMutationRequest, AuthPasswordResetMutationResponse, AuthPasswordResetMutation } from "./Auth/AuthPasswordReset.ts";
export type { AuthPasswordResetWithToken200, AuthPasswordResetWithToken422, AuthPasswordResetWithTokenMutationRequest, AuthPasswordResetWithTokenMutationResponse, AuthPasswordResetWithTokenMutation } from "./Auth/AuthPasswordResetWithToken.ts";
export type { AuthRegister200, AuthRegister422, AuthRegisterMutationRequest, AuthRegisterMutationResponse, AuthRegisterMutation } from "./Auth/AuthRegister.ts";
export type { AuthRequest } from "./AuthRequest.ts";
export type { BodySubtasksCreate } from "./BodySubtasksCreate.ts";
export type { BodySubtasksUpdateSubtaskID } from "./BodySubtasksUpdateSubtaskID.ts";
export type { ChangePasswordRequest } from "./ChangePasswordRequest.ts";
export type { GetDocumentationApiDocsGet200, GetDocumentationApiDocsGetQueryResponse, GetDocumentationApiDocsGetQuery } from "./Default/GetDocumentationApiDocsGet.ts";
export type { GetRedocDocumentationApiRedocGet200, GetRedocDocumentationApiRedocGetQueryResponse, GetRedocDocumentationApiRedocGetQuery } from "./Default/GetRedocDocumentationApiRedocGet.ts";
export type { OpenapiApiOpenapiJsonGet200, OpenapiApiOpenapiJsonGetQueryResponse, OpenapiApiOpenapiJsonGetQuery } from "./Default/OpenapiApiOpenapiJsonGet.ts";
export type { HealthCheckApiHealthGet200, HealthCheckApiHealthGetQueryResponse, HealthCheckApiHealthGetQuery } from "./Health/HealthCheckApiHealthGet.ts";
export type { HTTPValidationError } from "./HTTPValidationError.ts";
export type { PasswordReset } from "./PasswordReset.ts";
export type { PasswordResetConfirm } from "./PasswordResetConfirm.ts";
export type { Permission } from "./Permission.ts";
export type { Roles } from "./Roles.ts";
export type { SortableFields } from "./SortableFields.ts";
export type { SortDirection } from "./SortDirection.ts";
export type { StudentAuth } from "./StudentAuth.ts";
export type { StudentCreate } from "./StudentCreate.ts";
export type { StudentEdit } from "./StudentEdit.ts";
export type { StudentField } from "./StudentField.ts";
export type { StudentOut } from "./StudentOut.ts";
export type { DeleteStudentQueryParams, DeleteStudent200, DeleteStudent422, DeleteStudentMutationResponse, DeleteStudentMutation } from "./Students/DeleteStudent.ts";
export type { EditStudentQueryParams, EditStudent200, EditStudent422, EditStudentMutationRequest, EditStudentMutationResponse, EditStudentMutation } from "./Students/EditStudent.ts";
export type { NewStudent200, NewStudent422, NewStudentMutationRequest, NewStudentMutationResponse, NewStudentMutation } from "./Students/NewStudent.ts";
export type { Students200, StudentsQueryResponse, StudentsQuery, StudentsQueryParams, Students422, StudentsMutationResponse, StudentsMutation } from "./Students/Students.ts";
export type { StudentsSearchQueryParams, StudentsSearch200, StudentsSearch422, StudentsSearchQueryResponse, StudentsSearchQuery } from "./Students/StudentsSearch.ts";
export type { StudentsStudentIDPathParams, StudentsStudentID200, StudentsStudentID422, StudentsStudentIDQueryResponse, StudentsStudentIDQuery } from "./Students/StudentsStudentID.ts";
export type { StudentsSubtasksQueryParams, StudentsSubtasks200, StudentsSubtasks422, StudentsSubtasksQueryResponse, StudentsSubtasksQuery } from "./StudentsSubtasks/StudentsSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks200, StudentsSubtasksAssignSubtasks422, StudentsSubtasksAssignSubtasksQueryResponse, StudentsSubtasksAssignSubtasksQuery } from "./StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
export type { StudentTaskRead } from "./StudentTaskRead.ts";
export type { SubjectListResponse } from "./SubjectListResponse.ts";
export type { SubjectRead } from "./SubjectRead.ts";
export type { Subjects200, SubjectsQueryResponse, SubjectsQuery } from "./Subjects/Subjects.ts";
export type { SubjectsSubjectIDPathParams, SubjectsSubjectID200, SubjectsSubjectID422, SubjectsSubjectIDQueryResponse, SubjectsSubjectIDQuery } from "./Subjects/SubjectsSubjectID.ts";
export type { SubtasksQueryParams, Subtasks200, Subtasks422, SubtasksQueryResponse, SubtasksQuery } from "./Subtasks/Subtasks.ts";
export type { SubtasksCreate200, SubtasksCreate422, SubtasksCreateMutationRequest, SubtasksCreateMutationResponse, SubtasksCreateMutation } from "./Subtasks/SubtasksCreate.ts";
export type { SubtasksDeleteSubtaskIDPathParams, SubtasksDeleteSubtaskID200, SubtasksDeleteSubtaskID422, SubtasksDeleteSubtaskIDMutationResponse, SubtasksDeleteSubtaskIDMutation } from "./Subtasks/SubtasksDeleteSubtaskID.ts";
export type { SubtasksSubtaskIDPathParams, SubtasksSubtaskID200, SubtasksSubtaskID422, SubtasksSubtaskIDQueryResponse, SubtasksSubtaskIDQuery } from "./Subtasks/SubtasksSubtaskID.ts";
export type { SubtasksUpdateSubtaskIDPathParams, SubtasksUpdateSubtaskID200, SubtasksUpdateSubtaskID422, SubtasksUpdateSubtaskIDMutationRequest, SubtasksUpdateSubtaskIDMutationResponse, SubtasksUpdateSubtaskIDMutation } from "./Subtasks/SubtasksUpdateSubtaskID.ts";
export type { TaskListResponse } from "./TaskListResponse.ts";
export type { TaskRead } from "./TaskRead.ts";
export type { TasksQueryParams, Tasks200, Tasks422, TasksQueryResponse, TasksQuery } from "./Tasks/Tasks.ts";
export type { TasksTaskIDPathParams, TasksTaskID200, TasksTaskID422, TasksTaskIDQueryResponse, TasksTaskIDQuery } from "./Tasks/TasksTaskID.ts";
export type { TokenWithStudent } from "./TokenWithStudent.ts";
export type { UserCreate } from "./UserCreate.ts";
export type { ValidationError } from "./ValidationError.ts";
export type { VariantsQueryParams, Variants200, Variants422, VariantsQueryResponse, VariantsQuery } from "./Variants/Variants.ts";
export type { VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID200, VariantsExecVariantIDStudentID422, VariantsExecVariantIDStudentIDQueryResponse, VariantsExecVariantIDStudentIDQuery } from "./Variants/VariantsExecVariantIDStudentID.ts";
export type { VariantsVariantIDPathParams, VariantsVariantID200, VariantsVariantID422, VariantsVariantIDQueryResponse, VariantsVariantIDQuery } from "./Variants/VariantsVariantID.ts";
export { SortableFieldsEnum } from "./SortableFields.ts";
export { SortDirectionEnum } from "./SortDirection.ts";
export { StudentFieldEnum } from "./StudentField.ts";