/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface Permission {
    /**
     * @type integer
    */
    PermissionID: number;
    /**
     * @type string
    */
    Name: string;
    /**
     * @type string
    */
    Description: string;
}