/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface Roles {
    /**
     * @type integer
    */
    RoleID: number;
    /**
     * @type string
    */
    Name: string;
}