/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export enum SortableFieldsEnum {
    "StudentTaskID" = "StudentTaskID",
    "StudentID" = "StudentID",
    "SubTaskID" = "SubTaskID",
    "TaskID" = "TaskID",
    "SubjectID" = "SubjectID",
    "VariantID" = "VariantID",
    "StartDate" = "StartDate",
    "ModifiedDate" = "ModifiedDate",
    "CompletionDate" = "CompletionDate",
    "DeadlineDate" = "DeadlineDate",
    "TypeVariant" = "TypeVariant",
    "YearVariant" = "YearVariant",
    "NumberVarinat" = "NumberVarinat",
    "DifficultyLevel" = "DifficultyLevel",
    "Attempts" = "Attempts"
}

export type SortableFields = SortableFieldsEnum;