/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface StudentAuth {
    /**
     * @type integer
    */
    ID: number;
    Login: (string | null);
    Last_Name: (string | null);
    First_Name: (string | null);
    Email: (string | null);
    RoleName: (string | null);
    IsActive: (boolean | null);
    IsDeleted: (string | null);
}