/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface StudentTaskRead {
    /**
     * @type integer
    */
    StudentTaskID: number;
    /**
     * @type integer
    */
    StudentID: number;
    /**
     * @type integer
    */
    SubTaskID: number;
    StudentAnswer?: (string | null);
    CompletionStatus?: (string | null);
    Score?: (number | null);
    StartDate?: (string | null);
    ModifiedDate?: (string | null);
    CompletionDate?: (string | null);
    DeadlineDate?: (string | null);
    Attempts?: (number | null);
    Login?: (string | null);
    ID?: (number | null);
    Name?: (string | null);
    TaskID?: (number | null);
    TaskTitle?: (string | null);
    SubTaskNumber?: (number | null);
    Blocks?: (string | null);
    SolutionStudentPath?: (string | null);
    Description?: (string | null);
    VariantID?: (number | null);
    VariantName?: (string | null);
    TypeVariant?: (string | null);
    YearVariant?: (number | null);
    NumberVarinat?: (number | null);
    DifficultyLevel?: (number | null);
    Comment?: (string | null);
}