/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface StudentOut {
    /**
     * @type integer
    */
    ID: number;
    Login: (string | null);
    Last_Name: (string | null);
    First_Name: (string | null);
    Email: (string | null);
    RoleName: (string | null);
    IsActive: (boolean | null);
    IsDeleted: (string | null);
    Middle_Name: (string | null);
    Sex: (string | null);
    BirthDate: (string | null);
    Comment: (string | null);
    /**
     * @type array | undefined
    */
    permissions?: string[];
}