/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface StudentCreate {
    /**
     * @type string
    */
    Login: string;
    Last_Name?: (string | null);
    First_Name?: (string | null);
    Middle_Name?: (string | null);
    Email?: (string | null);
    Phone?: (string | null);
    Sex?: (string | null);
    BirthDate?: (string | null);
    Comment?: (string | null);
    RoleID?: (number | null);
    IsActive?: (boolean | null);
    /**
     * @type string
    */
    Password: string;
}