/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export enum StudentFieldEnum {
    "ID" = "ID",
    "Login" = "Login",
    "Email" = "Email",
    "Phone" = "Phone"
}

export type StudentField = StudentFieldEnum;