/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubjectRead } from "./SubjectRead.ts";

export interface SubjectListResponse {
    /**
     * @type string
    */
    message: string;
    count?: (number | null);
    /**
     * @type array
    */
    subjects: SubjectRead[];
}