/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface SubjectRead {
    /**
     * @type integer
    */
    ID: number;
    /**
     * @type string
    */
    Name: string;
    /**
     * @type string
    */
    Description: string;
    /**
     * @type string
    */
    EnglishName: string;
}