/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskRead } from "./TaskRead.ts";

export interface TaskListResponse {
    /**
     * @type string
    */
    message: string;
    count?: (number | null);
    /**
     * @type array
    */
    tasks: TaskRead[];
}