/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface TaskRead {
    /**
     * @type integer
    */
    TaskID: number;
    /**
     * @type integer
    */
    SubjectID: number;
    TaskNumber?: (number | null);
    TaskTitle?: (string | null);
}