/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentAuth } from "./StudentAuth.ts";

export interface TokenWithStudent {
    /**
     * @type string
    */
    access_token: string;
    /**
     * @type string
    */
    token_type: string;
    /**
     * @type object
    */
    student: StudentAuth;
}