/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export interface UserCreate {
    /**
     * @type string, email
    */
    email: string;
    /**
     * @type string
    */
    login: string;
    /**
     * @type string
    */
    password: string;
    /**
     * @type string
    */
    phone: string;
}