/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubjectsQueryResponse } from "../../types/Subjects/Subjects.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { subjects } from "../../services/SubjectsService/subjects.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const subjectsSuspenseQueryKey = () => [{ url: '/api/subjects' }] as const

export type SubjectsSuspenseQueryKey = ReturnType<typeof subjectsSuspenseQueryKey>

export function subjectsSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = subjectsSuspenseQueryKey()
  return queryOptions<SubjectsQueryResponse, ResponseErrorConfig<Error>, SubjectsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return subjects(config)
   },
  })
}

/**
 * @description так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список всех предметов (Информатика, Математика)
 * {@link /api/subjects}
 */
export function useSubjectsSuspense<TData = SubjectsQueryResponse, TQueryKey extends QueryKey = SubjectsSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<SubjectsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? subjectsSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...subjectsSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}