/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubjectsQueryResponse } from "../../types/Subjects/Subjects.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { subjects } from "../../services/SubjectsService/subjects.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const subjectsQueryKey = () => [{ url: '/api/subjects' }] as const

export type SubjectsQueryKey = ReturnType<typeof subjectsQueryKey>

export function subjectsQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = subjectsQueryKey()
  return queryOptions<SubjectsQueryResponse, ResponseErrorConfig<Error>, SubjectsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return subjects(config)
   },
  })
}

/**
 * @description так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список всех предметов (Информатика, Математика)
 * {@link /api/subjects}
 */
export function useSubjects<TData = SubjectsQueryResponse, TQueryData = SubjectsQueryResponse, TQueryKey extends QueryKey = SubjectsQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<SubjectsQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? subjectsQueryKey()

  const query = useQuery({
   ...subjectsQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}