/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubjectsSubjectIDQueryResponse, SubjectsSubjectIDPathParams, SubjectsSubjectID422 } from "../../types/Subjects/SubjectsSubjectID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { subjectsSubjectID } from "../../services/SubjectsService/subjectsSubjectID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const subjectsSubjectIDSuspenseQueryKey = (subjectID: SubjectsSubjectIDPathParams["subjectID"]) => [{ url: '/api/subjects/:subjectID', params: {subjectID:subjectID} }] as const

export type SubjectsSubjectIDSuspenseQueryKey = ReturnType<typeof subjectsSubjectIDSuspenseQueryKey>

export function subjectsSubjectIDSuspenseQueryOptions(subjectID: SubjectsSubjectIDPathParams["subjectID"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = subjectsSubjectIDSuspenseQueryKey(subjectID)
  return queryOptions<SubjectsSubjectIDQueryResponse, ResponseErrorConfig<SubjectsSubjectID422>, SubjectsSubjectIDQueryResponse, typeof queryKey>({
   enabled: !!(subjectID),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return subjectsSubjectID(subjectID, config)
   },
  })
}

/**
 * @description так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить предмет по его subjectID
 * {@link /api/subjects/:subjectID}
 */
export function useSubjectsSubjectIDSuspense<TData = SubjectsSubjectIDQueryResponse, TQueryKey extends QueryKey = SubjectsSubjectIDSuspenseQueryKey>(subjectID: SubjectsSubjectIDPathParams["subjectID"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<SubjectsSubjectIDQueryResponse, ResponseErrorConfig<SubjectsSubjectID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? subjectsSubjectIDSuspenseQueryKey(subjectID)

  const query = useSuspenseQuery({
   ...subjectsSubjectIDSuspenseQueryOptions(subjectID, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<SubjectsSubjectID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}