/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetDocumentationApiDocsGetQueryResponse } from "../../types/Default/GetDocumentationApiDocsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { getDocumentationApiDocsGetQueryResponseSchema } from "../../zod/DefaultSchemas/getDocumentationApiDocsGetSchema.ts";

function getGetDocumentationApiDocsGetUrl() {
  const res = { method: 'GET', url: `/api/docs` as const }  
  return res
}

/**
 * @summary Get Documentation
 * {@link /api/docs}
 */
export async function getDocumentationApiDocsGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetDocumentationApiDocsGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetDocumentationApiDocsGetUrl().url.toString(), ... requestConfig })  
  return getDocumentationApiDocsGetQueryResponseSchema.parse(res.data)
}