/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetRedocDocumentationApiRedocGetQueryResponse } from "../../types/Default/GetRedocDocumentationApiRedocGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { getRedocDocumentationApiRedocGetQueryResponseSchema } from "../../zod/DefaultSchemas/getRedocDocumentationApiRedocGetSchema.ts";

function getGetRedocDocumentationApiRedocGetUrl() {
  const res = { method: 'GET', url: `/api/redoc` as const }  
  return res
}

/**
 * @summary Get Redoc Documentation
 * {@link /api/redoc}
 */
export async function getRedocDocumentationApiRedocGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetRedocDocumentationApiRedocGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getGetRedocDocumentationApiRedocGetUrl().url.toString(), ... requestConfig })  
  return getRedocDocumentationApiRedocGetQueryResponseSchema.parse(res.data)
}