/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { OpenapiApiOpenapiJsonGetQueryResponse } from "../../types/Default/OpenapiApiOpenapiJsonGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { openapiApiOpenapiJsonGetQueryResponseSchema } from "../../zod/DefaultSchemas/openapiApiOpenapiJsonGetSchema.ts";

function getOpenapiApiOpenapiJsonGetUrl() {
  const res = { method: 'GET', url: `/api/openapi.json` as const }  
  return res
}

/**
 * @summary Openapi
 * {@link /api/openapi.json}
 */
export async function openapiApiOpenapiJsonGet(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<OpenapiApiOpenapiJsonGetQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getOpenapiApiOpenapiJsonGetUrl().url.toString(), ... requestConfig })  
  return openapiApiOpenapiJsonGetQueryResponseSchema.parse(res.data)
}