/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AdminChangePasswordRequest } from "../types/AdminChangePasswordRequest.ts";
import { z } from "zod";

export const adminChangePasswordRequestSchema = z.object({
    "new_password": z.string().min(6)
    }) as unknown as z.ZodType<AdminChangePasswordRequest>