/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AssignPermissionsRequest } from "../types/AssignPermissionsRequest.ts";
import { z } from "zod";

export const assignPermissionsRequestSchema = z.object({
    "permission_ids": z.array(z.int())
    }) as unknown as z.ZodType<AssignPermissionsRequest>