/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthRequest } from "../types/AuthRequest.ts";
import { z } from "zod";

export const authRequestSchema = z.object({
    "identifier": z.string(),
"password": z.string()
    }) as unknown as z.ZodType<AuthRequest>