/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodySubtasksUpdateSubtaskID } from "../types/BodySubtasksUpdateSubtaskID.ts";
import { z } from "zod";

export const bodySubtasksUpdateSubtaskIDSchema = z.object({
    "task_id": z.optional(z.int().describe("Task_id категории")),
"subtask_number": z.optional(z.string().describe("Номер задачи в категории")),
"variant_id": z.optional(z.int().describe("ID варианта (если есть)")),
"blocks": z.string().describe("JSON список блоков: [{\"type\":\"image\",\"content\":\"image.png\"},{\"type\":\"text\",\"content\":\"Текст\"}]"),
"files_blocks": z.optional(z.union([z.array(z.instanceof(File)), z.null()]).describe("Файлы для блоков")),
"answer": z.optional(z.string().describe("Ответ на задачу")),
"files_solution": z.optional(z.union([z.array(z.instanceof(File)), z.null()]).describe("Файлы решения")),
"files_extra": z.optional(z.union([z.array(z.instanceof(File)), z.null()]).describe("Дополнительные файлы"))
    }) as unknown as z.ZodType<BodySubtasksUpdateSubtaskID>