/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodySubtasksCreate } from "../types/BodySubtasksCreate.ts";
import { z } from "zod";

export const bodySubtasksCreateSchema = z.object({
    "task_id": z.optional(z.int().describe("Task_id категории")),
"subtask_number": z.optional(z.string().describe("Номер задачи в категории")),
"variant_id": z.optional(z.int().describe("ID варианта (если есть)")),
"blocks": z.string().describe("JSON список блоков: [{\"type\":\"text\",\"content\":\"Текст\"},{\"type\":\"image\",\"content\":\"image.png\"}]"),
"files_blocks": z.optional(z.array(z.instanceof(File)).describe("Список файлов для блоков")),
"answer": z.optional(z.string().describe("Ответ на задачу")),
"files_solution": z.optional(z.array(z.instanceof(File)).describe("Список файлов для решения")),
"files_extra": z.optional(z.array(z.instanceof(File)).describe("Список дополнительных файлов к задаче"))
    }) as unknown as z.ZodType<BodySubtasksCreate>