/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ChangePasswordRequest } from "../types/ChangePasswordRequest.ts";
import { z } from "zod";

export const changePasswordRequestSchema = z.object({
    "old_password": z.string(),
"new_password": z.string().min(6),
"repeat_new_password": z.string().min(6)
    }) as unknown as z.ZodType<ChangePasswordRequest>