/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../types/HTTPValidationError.ts";
import { validationErrorSchema } from "./validationErrorSchema.ts";
import { z } from "zod";

export const HTTPValidationErrorSchema = z.object({
    get "detail"(){
                return z.optional(z.array(validationErrorSchema))
              }
    }) as unknown as z.ZodType<HTTPValidationError>