/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordReset } from "../types/PasswordReset.ts";
import { z } from "zod";

export const passwordResetSchema = z.object({
    "Email": z.email()
    }) as unknown as z.ZodType<PasswordReset>