/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PasswordResetConfirm } from "../types/PasswordResetConfirm.ts";
import { z } from "zod";

export const passwordResetConfirmSchema = z.object({
    "token": z.string(),
"new_password": z.string().min(6),
"repeat_new_password": z.string().min(6)
    }) as unknown as z.ZodType<PasswordResetConfirm>