/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Permission } from "../types/Permission.ts";
import { z } from "zod";

export const permissionSchema = z.object({
    "PermissionID": z.int(),
"Name": z.string(),
"Description": z.string()
    }) as unknown as z.ZodType<Permission>