/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Roles } from "../types/Roles.ts";
import { z } from "zod";

export const rolesSchema = z.object({
    "RoleID": z.int(),
"Name": z.string()
    }) as unknown as z.ZodType<Roles>