/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SortDirection } from "../types/SortDirection.ts";
import { z } from "zod";

export const sortDirectionSchema = z.enum(["ASC", "DESC"]) as unknown as z.ZodType<SortDirection>