/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SortableFields } from "../types/SortableFields.ts";
import { z } from "zod";

export const sortableFieldsSchema = z.enum(["StudentTaskID", "StudentID", "SubTaskID", "TaskID", "SubjectID", "VariantID", "StartDate", "ModifiedDate", "CompletionDate", "DeadlineDate", "TypeVariant", "YearVariant", "NumberVarinat", "DifficultyLevel", "Attempts"]) as unknown as z.ZodType<SortableFields>