/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentTaskRead } from "../types/StudentTaskRead.ts";
import { z } from "zod";

export const studentTaskReadSchema = z.object({
    "StudentTaskID": z.int(),
"StudentID": z.int(),
"SubTaskID": z.int(),
"StudentAnswer": z.optional(z.union([z.string(), z.null()])),
"CompletionStatus": z.optional(z.union([z.string(), z.null()])),
"Score": z.optional(z.union([z.int(), z.null()])),
"StartDate": z.optional(z.union([z.iso.datetime({ offset: true }), z.null()])),
"ModifiedDate": z.optional(z.union([z.iso.datetime({ offset: true }), z.null()])),
"CompletionDate": z.optional(z.union([z.iso.datetime({ offset: true }), z.null()])),
"DeadlineDate": z.optional(z.union([z.iso.datetime({ offset: true }), z.null()])),
"Attempts": z.optional(z.union([z.int(), z.null()])),
"Login": z.optional(z.union([z.string(), z.null()])),
"ID": z.optional(z.union([z.int(), z.null()])),
"Name": z.optional(z.union([z.string(), z.null()])),
"TaskID": z.optional(z.union([z.int(), z.null()])),
"TaskTitle": z.optional(z.union([z.string(), z.null()])),
"SubTaskNumber": z.optional(z.union([z.int(), z.null()])),
"Blocks": z.optional(z.union([z.string(), z.null()])),
"SolutionStudentPath": z.optional(z.union([z.string(), z.null()])),
"Description": z.optional(z.union([z.string(), z.null()])),
"VariantID": z.optional(z.union([z.int(), z.null()])),
"VariantName": z.optional(z.union([z.string(), z.null()])),
"TypeVariant": z.optional(z.union([z.string(), z.null()])),
"YearVariant": z.optional(z.union([z.int(), z.null()])),
"NumberVarinat": z.optional(z.union([z.int(), z.null()])),
"DifficultyLevel": z.optional(z.union([z.int(), z.null()])),
"Comment": z.optional(z.union([z.string(), z.null()]))
    }) as unknown as z.ZodType<StudentTaskRead>