/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentAuth } from "../types/StudentAuth.ts";
import { z } from "zod";

export const studentAuthSchema = z.object({
    "ID": z.int(),
"Login": z.union([z.string(), z.null()]),
"Last_Name": z.union([z.string(), z.null()]),
"First_Name": z.union([z.string(), z.null()]),
"Email": z.union([z.email(), z.null()]),
"RoleName": z.union([z.string(), z.null()]),
"IsActive": z.union([z.boolean(), z.null()]),
"IsDeleted": z.union([z.iso.date(), z.null()])
    }) as unknown as z.ZodType<StudentAuth>