/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentOut } from "../types/StudentOut.ts";
import { z } from "zod";

export const studentOutSchema = z.object({
    "ID": z.int(),
"Login": z.union([z.string(), z.null()]),
"Last_Name": z.union([z.string(), z.null()]),
"First_Name": z.union([z.string(), z.null()]),
"Email": z.union([z.email(), z.null()]),
"RoleName": z.union([z.string(), z.null()]),
"IsActive": z.union([z.boolean(), z.null()]),
"IsDeleted": z.union([z.iso.date(), z.null()]),
"Middle_Name": z.union([z.string(), z.null()]),
"Sex": z.union([z.string(), z.null()]),
"BirthDate": z.union([z.iso.date(), z.null()]),
"Comment": z.union([z.string(), z.null()]),
"permissions": z.optional(z.array(z.string()))
    }) as unknown as z.ZodType<StudentOut>