/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentCreate } from "../types/StudentCreate.ts";
import { z } from "zod";

export const studentCreateSchema = z.object({
    "Login": z.string(),
"Last_Name": z.optional(z.union([z.string(), z.null()])),
"First_Name": z.optional(z.union([z.string(), z.null()])),
"Middle_Name": z.optional(z.union([z.string(), z.null()])),
"Email": z.optional(z.union([z.email(), z.null()])),
"Phone": z.optional(z.union([z.string(), z.null()])),
"Sex": z.optional(z.union([z.string(), z.null()])),
"BirthDate": z.optional(z.union([z.iso.date(), z.null()])),
"Comment": z.optional(z.union([z.string(), z.null()])),
"RoleID": z.optional(z.union([z.int(), z.null()])),
"IsActive": z.optional(z.union([z.boolean(), z.null()])),
"Password": z.string()
    }) as unknown as z.ZodType<StudentCreate>