/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentField } from "../types/StudentField.ts";
import { z } from "zod";

export const studentFieldSchema = z.enum(["ID", "Login", "Email", "Phone"]) as unknown as z.ZodType<StudentField>