/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubjectRead } from "../types/SubjectRead.ts";
import { z } from "zod";

export const subjectReadSchema = z.object({
    "ID": z.int(),
"Name": z.string(),
"Description": z.string(),
"EnglishName": z.string()
    }) as unknown as z.ZodType<SubjectRead>