/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubjectListResponse } from "../types/SubjectListResponse.ts";
import { subjectReadSchema } from "./subjectReadSchema.ts";
import { z } from "zod";

export const subjectListResponseSchema = z.object({
    "message": z.string(),
"count": z.optional(z.union([z.int(), z.null()])),
get "subjects"(){
                return z.array(subjectReadSchema)
              }
    }) as unknown as z.ZodType<SubjectListResponse>