/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskRead } from "../types/TaskRead.ts";
import { z } from "zod";

export const taskReadSchema = z.object({
    "TaskID": z.int(),
"SubjectID": z.int(),
"TaskNumber": z.optional(z.union([z.int(), z.null()])),
"TaskTitle": z.optional(z.union([z.string(), z.null()]))
    }) as unknown as z.ZodType<TaskRead>