/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TaskListResponse } from "../types/TaskListResponse.ts";
import { taskReadSchema } from "./taskReadSchema.ts";
import { z } from "zod";

export const taskListResponseSchema = z.object({
    "message": z.string(),
"count": z.optional(z.union([z.int(), z.null()])),
get "tasks"(){
                return z.array(taskReadSchema)
              }
    }) as unknown as z.ZodType<TaskListResponse>