/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TokenWithStudent } from "../types/TokenWithStudent.ts";
import { studentAuthSchema } from "./studentAuthSchema.ts";
import { z } from "zod";

export const tokenWithStudentSchema = z.object({
    "access_token": z.string(),
"token_type": z.string(),
get "student"(){
                return studentAuthSchema
              }
    }) as unknown as z.ZodType<TokenWithStudent>