/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserCreate } from "../types/UserCreate.ts";
import { z } from "zod";

export const userCreateSchema = z.object({
    "email": z.email(),
"login": z.string(),
"password": z.string(),
"phone": z.string()
    }) as unknown as z.ZodType<UserCreate>