/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ValidationError } from "../types/ValidationError.ts";
import { z } from "zod";

export const validationErrorSchema = z.object({
    "loc": z.array(z.union([z.int(), z.string()])),
"msg": z.string(),
"type": z.string()
    }) as unknown as z.ZodType<ValidationError>