/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Subjects200, SubjectsQueryResponse } from "../../types/Subjects/Subjects.ts";
import { subjectListResponseSchema } from "../subjectListResponseSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const subjects200Schema = subjectListResponseSchema as unknown as z.ZodType<Subjects200>

export const subjectsQueryResponseSchema = subjects200Schema as unknown as z.ZodType<SubjectsQueryResponse>