/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubjectsSubjectIDPathParams, SubjectsSubjectID200, SubjectsSubjectID422, SubjectsSubjectIDQueryResponse } from "../../types/Subjects/SubjectsSubjectID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { subjectReadSchema } from "../subjectReadSchema.ts";
import { z } from "zod";

export const subjectsSubjectIDPathParamsSchema = z.object({
    "subjectID": z.coerce.number().int()
    }) as unknown as z.ZodType<SubjectsSubjectIDPathParams>

/**
 * @description Successful Response
 */
export const subjectsSubjectID200Schema = subjectReadSchema as unknown as z.ZodType<SubjectsSubjectID200>

/**
 * @description Validation Error
 */
export const subjectsSubjectID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<SubjectsSubjectID422>

export const subjectsSubjectIDQueryResponseSchema = subjectsSubjectID200Schema as unknown as z.ZodType<SubjectsSubjectIDQueryResponse>