/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSubtasksQueryResponse, StudentsSubtasksQueryParams, StudentsSubtasks422 } from "../../types/StudentsSubtasks/StudentsSubtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { studentsSubtasksQueryResponseSchema } from "../../zod/StudentsSubtasksSchemas/studentsSubtasksSchema.ts";

function getStudentsSubtasksUrl() {
  const res = { method: 'GET', url: `/api/students_subtasks` as const }  
  return res
}

/**
 * @description В качестве фильтров передаются параметры                                                `StudentTaskID` - по Номеру задачи Студента                                              `StudentID` - по id студента                                            `SubTaskID` - по id задачи                                              `TaskID` - по id категории                                              `SubjectID` - по id предмета                                              `VariantID` - по id варианта                                              `CompletionStatus` - по статусу выполнения                                               `Search` - Поиск по ключевому слову (логин, описание и т.п.)                                              `SortColumn1` - Выбор колонки для сортировки 1 уровень                                              `SortColumn2` - Выбор колонки для сортировки 2 уровень                                              `SortDirection1` - Сортировка (по возрастанию ASC ) DESC -по убыванию                                              `SortDirection2`	NVARCHAR(4)		= 'ASC'                                                `Offset` - с какой строки начинать выводить                                              `Limit` - количество выведенных строк (По умолчанию: 500)
 * @summary ГЛАВНЫЙ РОУТ с получением списка задач студента по фильтрам
 * {@link /api/students_subtasks}
 */
export async function studentsSubtasks({ params }: { params?: StudentsSubtasksQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasks422>, unknown>({ method : "GET", url : getStudentsSubtasksUrl().url.toString(), params, ... requestConfig })  
  return studentsSubtasksQueryResponseSchema.parse(res.data)
}