/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSubtasksAssignSubtasksQueryResponse, StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks422 } from "../../types/StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { studentsSubtasksAssignSubtasksQueryResponseSchema } from "../../zod/StudentsSubtasksSchemas/studentsSubtasksAssignSubtasksSchema.ts";

function getStudentsSubtasksAssignSubtasksUrl() {
  const res = { method: 'GET', url: `/api/students_subtasks/assign_subtasks` as const }  
  return res
}

/**
 * @description Для выбранного студента с (student_id)  назначиться задача сsubtask_id со статусом 'не начата'
 * @summary назначение задач студенту
 * {@link /api/students_subtasks/assign_subtasks}
 */
export async function studentsSubtasksAssignSubtasks({ params }: { params: StudentsSubtasksAssignSubtasksQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsSubtasksAssignSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>, unknown>({ method : "GET", url : getStudentsSubtasksAssignSubtasksUrl().url.toString(), params, ... requestConfig })  
  return studentsSubtasksAssignSubtasksQueryResponseSchema.parse(res.data)
}