/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { studentsSubtasks } from "./studentsSubtasks.ts";
import { studentsSubtasksAssignSubtasks } from "./studentsSubtasksAssignSubtasks.ts";

export function StudentsSubtasksService() {
  return { studentsSubtasks, studentsSubtasksAssignSubtasks }
}