export type { AdminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey } from "./AdminHooks/useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export type { AssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey } from "./AdminHooks/useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export type { AssignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey } from "./AdminHooks/useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export type { GetLogsApiAdminStudentsLogsGetQueryKey } from "./AdminHooks/useGetLogsApiAdminStudentsLogsGet.ts";
export type { GetLogsApiAdminStudentsLogsGetSuspenseQueryKey } from "./AdminHooks/useGetLogsApiAdminStudentsLogsGetSuspense.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetQueryKey } from "./AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGet.ts";
export type { GetLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey } from "./AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGetSuspense.ts";
export type { ReadAllStudentsApiAdminStudentsGetQueryKey } from "./AdminHooks/useReadAllStudentsApiAdminStudentsGet.ts";
export type { ReadAllStudentsApiAdminStudentsGetSuspenseQueryKey } from "./AdminHooks/useReadAllStudentsApiAdminStudentsGetSuspense.ts";
export type { ReadPermissionApiAdminPermissionGetQueryKey } from "./AdminHooks/useReadPermissionApiAdminPermissionGet.ts";
export type { ReadPermissionApiAdminPermissionGetSuspenseQueryKey } from "./AdminHooks/useReadPermissionApiAdminPermissionGetSuspense.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetQueryKey } from "./AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export type { ReadPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey } from "./AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense.ts";
export type { ReadRolesApiAdminRolesGetQueryKey } from "./AdminHooks/useReadRolesApiAdminRolesGet.ts";
export type { ReadRolesApiAdminRolesGetSuspenseQueryKey } from "./AdminHooks/useReadRolesApiAdminRolesGetSuspense.ts";
export type { AuthChangePasswordMutationKey } from "./AuthHooks/useAuthChangePassword.ts";
export type { AuthCheckTokenQueryKey } from "./AuthHooks/useAuthCheckToken.ts";
export type { AuthCheckTokenSuspenseQueryKey } from "./AuthHooks/useAuthCheckTokenSuspense.ts";
export type { AuthConfirmEmailQueryKey } from "./AuthHooks/useAuthConfirmEmail.ts";
export type { AuthConfirmEmailSuspenseQueryKey } from "./AuthHooks/useAuthConfirmEmailSuspense.ts";
export type { AuthLoginMutationKey } from "./AuthHooks/useAuthLogin.ts";
export type { AuthLogoutMutationKey } from "./AuthHooks/useAuthLogout.ts";
export type { AuthPasswordResetMutationKey } from "./AuthHooks/useAuthPasswordReset.ts";
export type { AuthPasswordResetWithTokenMutationKey } from "./AuthHooks/useAuthPasswordResetWithToken.ts";
export type { AuthRegisterMutationKey } from "./AuthHooks/useAuthRegister.ts";
export type { GetDocumentationApiDocsGetQueryKey } from "./DefaultHooks/useGetDocumentationApiDocsGet.ts";
export type { GetDocumentationApiDocsGetSuspenseQueryKey } from "./DefaultHooks/useGetDocumentationApiDocsGetSuspense.ts";
export type { GetRedocDocumentationApiRedocGetQueryKey } from "./DefaultHooks/useGetRedocDocumentationApiRedocGet.ts";
export type { GetRedocDocumentationApiRedocGetSuspenseQueryKey } from "./DefaultHooks/useGetRedocDocumentationApiRedocGetSuspense.ts";
export type { OpenapiApiOpenapiJsonGetQueryKey } from "./DefaultHooks/useOpenapiApiOpenapiJsonGet.ts";
export type { OpenapiApiOpenapiJsonGetSuspenseQueryKey } from "./DefaultHooks/useOpenapiApiOpenapiJsonGetSuspense.ts";
export type { HealthCheckApiHealthGetQueryKey } from "./HealthHooks/useHealthCheckApiHealthGet.ts";
export type { HealthCheckApiHealthGetSuspenseQueryKey } from "./HealthHooks/useHealthCheckApiHealthGetSuspense.ts";
export type { DeleteStudentMutationKey } from "./StudentsHooks/useDeleteStudent.ts";
export type { NewStudentMutationKey } from "./StudentsHooks/useNewStudent.ts";
export type { StudentsQueryKey, StudentsMutationKey } from "./StudentsHooks/useStudents.ts";
export type { StudentsSearchQueryKey } from "./StudentsHooks/useStudentsSearch.ts";
export type { StudentsSearchSuspenseQueryKey } from "./StudentsHooks/useStudentsSearchSuspense.ts";
export type { StudentsStudentIDQueryKey } from "./StudentsHooks/useStudentsStudentID.ts";
export type { StudentsStudentIDSuspenseQueryKey } from "./StudentsHooks/useStudentsStudentIDSuspense.ts";
export type { StudentsSuspenseQueryKey } from "./StudentsHooks/useStudentsSuspense.ts";
export type { StudentsSubtasksQueryKey } from "./StudentsSubtasksHooks/useStudentsSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksQueryKey } from "./StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasks.ts";
export type { StudentsSubtasksAssignSubtasksSuspenseQueryKey } from "./StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasksSuspense.ts";
export type { StudentsSubtasksSuspenseQueryKey } from "./StudentsSubtasksHooks/useStudentsSubtasksSuspense.ts";
export type { SubjectsQueryKey } from "./SubjectsHooks/useSubjects.ts";
export type { SubjectsSubjectIDQueryKey } from "./SubjectsHooks/useSubjectsSubjectID.ts";
export type { SubjectsSubjectIDSuspenseQueryKey } from "./SubjectsHooks/useSubjectsSubjectIDSuspense.ts";
export type { SubjectsSuspenseQueryKey } from "./SubjectsHooks/useSubjectsSuspense.ts";
export type { SubtasksQueryKey } from "./SubtasksHooks/useSubtasks.ts";
export type { SubtasksCreateMutationKey } from "./SubtasksHooks/useSubtasksCreate.ts";
export type { SubtasksDeleteSubtaskIDMutationKey } from "./SubtasksHooks/useSubtasksDeleteSubtaskID.ts";
export type { SubtasksSubtaskIDQueryKey } from "./SubtasksHooks/useSubtasksSubtaskID.ts";
export type { SubtasksSubtaskIDSuspenseQueryKey } from "./SubtasksHooks/useSubtasksSubtaskIDSuspense.ts";
export type { SubtasksSuspenseQueryKey } from "./SubtasksHooks/useSubtasksSuspense.ts";
export type { SubtasksUpdateSubtaskIDMutationKey } from "./SubtasksHooks/useSubtasksUpdateSubtaskID.ts";
export type { TasksQueryKey } from "./TasksHooks/useTasks.ts";
export type { TasksSuspenseQueryKey } from "./TasksHooks/useTasksSuspense.ts";
export type { TasksTaskIDQueryKey } from "./TasksHooks/useTasksTaskID.ts";
export type { TasksTaskIDSuspenseQueryKey } from "./TasksHooks/useTasksTaskIDSuspense.ts";
export type { VariantsQueryKey } from "./VariantsHooks/useVariants.ts";
export type { VariantsExecVariantIDStudentIDQueryKey } from "./VariantsHooks/useVariantsExecVariantIDStudentID.ts";
export type { VariantsExecVariantIDStudentIDSuspenseQueryKey } from "./VariantsHooks/useVariantsExecVariantIDStudentIDSuspense.ts";
export type { VariantsSuspenseQueryKey } from "./VariantsHooks/useVariantsSuspense.ts";
export type { VariantsVariantIDQueryKey } from "./VariantsHooks/useVariantsVariantID.ts";
export type { VariantsVariantIDSuspenseQueryKey } from "./VariantsHooks/useVariantsVariantIDSuspense.ts";
export { adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationKey, adminChangePasswordApiAdminStudentsStudentIdChangePasswordPostMutationOptions, useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost } from "./AdminHooks/useAdminChangePasswordApiAdminStudentsStudentIdChangePasswordPost.ts";
export { assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationKey, assignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPostMutationOptions, useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost } from "./AdminHooks/useAssignPermissionForRoleApiAdminRolesRoleIdAssignPermissionPost.ts";
export { assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationKey, assignRoleToStudentApiAdminStudentsStudentIDAssignRolePostMutationOptions, useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost } from "./AdminHooks/useAssignRoleToStudentApiAdminStudentsStudentIDAssignRolePost.ts";
export { getLogsApiAdminStudentsLogsGetQueryKey, getLogsApiAdminStudentsLogsGetQueryOptions, useGetLogsApiAdminStudentsLogsGet } from "./AdminHooks/useGetLogsApiAdminStudentsLogsGet.ts";
export { getLogsApiAdminStudentsLogsGetSuspenseQueryKey, getLogsApiAdminStudentsLogsGetSuspenseQueryOptions, useGetLogsApiAdminStudentsLogsGetSuspense } from "./AdminHooks/useGetLogsApiAdminStudentsLogsGetSuspense.ts";
export { getLogsApiAdminStudentsStudentIDLogsGetQueryKey, getLogsApiAdminStudentsStudentIDLogsGetQueryOptions, useGetLogsApiAdminStudentsStudentIDLogsGet } from "./AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGet.ts";
export { getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryKey, getLogsApiAdminStudentsStudentIDLogsGetSuspenseQueryOptions, useGetLogsApiAdminStudentsStudentIDLogsGetSuspense } from "./AdminHooks/useGetLogsApiAdminStudentsStudentIDLogsGetSuspense.ts";
export { readAllStudentsApiAdminStudentsGetQueryKey, readAllStudentsApiAdminStudentsGetQueryOptions, useReadAllStudentsApiAdminStudentsGet } from "./AdminHooks/useReadAllStudentsApiAdminStudentsGet.ts";
export { readAllStudentsApiAdminStudentsGetSuspenseQueryKey, readAllStudentsApiAdminStudentsGetSuspenseQueryOptions, useReadAllStudentsApiAdminStudentsGetSuspense } from "./AdminHooks/useReadAllStudentsApiAdminStudentsGetSuspense.ts";
export { readPermissionApiAdminPermissionGetQueryKey, readPermissionApiAdminPermissionGetQueryOptions, useReadPermissionApiAdminPermissionGet } from "./AdminHooks/useReadPermissionApiAdminPermissionGet.ts";
export { readPermissionApiAdminPermissionGetSuspenseQueryKey, readPermissionApiAdminPermissionGetSuspenseQueryOptions, useReadPermissionApiAdminPermissionGetSuspense } from "./AdminHooks/useReadPermissionApiAdminPermissionGetSuspense.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGetQueryKey, readPermissionsRoleApiAdminRolesRoleIdGetQueryOptions, useReadPermissionsRoleApiAdminRolesRoleIdGet } from "./AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGet.ts";
export { readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryKey, readPermissionsRoleApiAdminRolesRoleIdGetSuspenseQueryOptions, useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense } from "./AdminHooks/useReadPermissionsRoleApiAdminRolesRoleIdGetSuspense.ts";
export { readRolesApiAdminRolesGetQueryKey, readRolesApiAdminRolesGetQueryOptions, useReadRolesApiAdminRolesGet } from "./AdminHooks/useReadRolesApiAdminRolesGet.ts";
export { readRolesApiAdminRolesGetSuspenseQueryKey, readRolesApiAdminRolesGetSuspenseQueryOptions, useReadRolesApiAdminRolesGetSuspense } from "./AdminHooks/useReadRolesApiAdminRolesGetSuspense.ts";
export { authChangePasswordMutationKey, authChangePasswordMutationOptions, useAuthChangePassword } from "./AuthHooks/useAuthChangePassword.ts";
export { authCheckTokenQueryKey, authCheckTokenQueryOptions, useAuthCheckToken } from "./AuthHooks/useAuthCheckToken.ts";
export { authCheckTokenSuspenseQueryKey, authCheckTokenSuspenseQueryOptions, useAuthCheckTokenSuspense } from "./AuthHooks/useAuthCheckTokenSuspense.ts";
export { authConfirmEmailQueryKey, authConfirmEmailQueryOptions, useAuthConfirmEmail } from "./AuthHooks/useAuthConfirmEmail.ts";
export { authConfirmEmailSuspenseQueryKey, authConfirmEmailSuspenseQueryOptions, useAuthConfirmEmailSuspense } from "./AuthHooks/useAuthConfirmEmailSuspense.ts";
export { authLoginMutationKey, authLoginMutationOptions, useAuthLogin } from "./AuthHooks/useAuthLogin.ts";
export { authLogoutMutationKey, authLogoutMutationOptions, useAuthLogout } from "./AuthHooks/useAuthLogout.ts";
export { authPasswordResetMutationKey, authPasswordResetMutationOptions, useAuthPasswordReset } from "./AuthHooks/useAuthPasswordReset.ts";
export { authPasswordResetWithTokenMutationKey, authPasswordResetWithTokenMutationOptions, useAuthPasswordResetWithToken } from "./AuthHooks/useAuthPasswordResetWithToken.ts";
export { authRegisterMutationKey, authRegisterMutationOptions, useAuthRegister } from "./AuthHooks/useAuthRegister.ts";
export { getDocumentationApiDocsGetQueryKey, getDocumentationApiDocsGetQueryOptions, useGetDocumentationApiDocsGet } from "./DefaultHooks/useGetDocumentationApiDocsGet.ts";
export { getDocumentationApiDocsGetSuspenseQueryKey, getDocumentationApiDocsGetSuspenseQueryOptions, useGetDocumentationApiDocsGetSuspense } from "./DefaultHooks/useGetDocumentationApiDocsGetSuspense.ts";
export { getRedocDocumentationApiRedocGetQueryKey, getRedocDocumentationApiRedocGetQueryOptions, useGetRedocDocumentationApiRedocGet } from "./DefaultHooks/useGetRedocDocumentationApiRedocGet.ts";
export { getRedocDocumentationApiRedocGetSuspenseQueryKey, getRedocDocumentationApiRedocGetSuspenseQueryOptions, useGetRedocDocumentationApiRedocGetSuspense } from "./DefaultHooks/useGetRedocDocumentationApiRedocGetSuspense.ts";
export { openapiApiOpenapiJsonGetQueryKey, openapiApiOpenapiJsonGetQueryOptions, useOpenapiApiOpenapiJsonGet } from "./DefaultHooks/useOpenapiApiOpenapiJsonGet.ts";
export { openapiApiOpenapiJsonGetSuspenseQueryKey, openapiApiOpenapiJsonGetSuspenseQueryOptions, useOpenapiApiOpenapiJsonGetSuspense } from "./DefaultHooks/useOpenapiApiOpenapiJsonGetSuspense.ts";
export { healthCheckApiHealthGetQueryKey, healthCheckApiHealthGetQueryOptions, useHealthCheckApiHealthGet } from "./HealthHooks/useHealthCheckApiHealthGet.ts";
export { healthCheckApiHealthGetSuspenseQueryKey, healthCheckApiHealthGetSuspenseQueryOptions, useHealthCheckApiHealthGetSuspense } from "./HealthHooks/useHealthCheckApiHealthGetSuspense.ts";
export { deleteStudentMutationKey, deleteStudentMutationOptions, useDeleteStudent } from "./StudentsHooks/useDeleteStudent.ts";
export { newStudentMutationKey, newStudentMutationOptions, useNewStudent } from "./StudentsHooks/useNewStudent.ts";
export { studentsQueryKey, studentsQueryOptions, useStudents, studentsMutationKey, studentsMutationOptions } from "./StudentsHooks/useStudents.ts";
export { studentsSearchQueryKey, studentsSearchQueryOptions, useStudentsSearch } from "./StudentsHooks/useStudentsSearch.ts";
export { studentsSearchSuspenseQueryKey, studentsSearchSuspenseQueryOptions, useStudentsSearchSuspense } from "./StudentsHooks/useStudentsSearchSuspense.ts";
export { studentsStudentIDQueryKey, studentsStudentIDQueryOptions, useStudentsStudentID } from "./StudentsHooks/useStudentsStudentID.ts";
export { studentsStudentIDSuspenseQueryKey, studentsStudentIDSuspenseQueryOptions, useStudentsStudentIDSuspense } from "./StudentsHooks/useStudentsStudentIDSuspense.ts";
export { studentsSuspenseQueryKey, studentsSuspenseQueryOptions, useStudentsSuspense } from "./StudentsHooks/useStudentsSuspense.ts";
export { studentsSubtasksQueryKey, studentsSubtasksQueryOptions, useStudentsSubtasks } from "./StudentsSubtasksHooks/useStudentsSubtasks.ts";
export { studentsSubtasksAssignSubtasksQueryKey, studentsSubtasksAssignSubtasksQueryOptions, useStudentsSubtasksAssignSubtasks } from "./StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasks.ts";
export { studentsSubtasksAssignSubtasksSuspenseQueryKey, studentsSubtasksAssignSubtasksSuspenseQueryOptions, useStudentsSubtasksAssignSubtasksSuspense } from "./StudentsSubtasksHooks/useStudentsSubtasksAssignSubtasksSuspense.ts";
export { studentsSubtasksSuspenseQueryKey, studentsSubtasksSuspenseQueryOptions, useStudentsSubtasksSuspense } from "./StudentsSubtasksHooks/useStudentsSubtasksSuspense.ts";
export { subjectsQueryKey, subjectsQueryOptions, useSubjects } from "./SubjectsHooks/useSubjects.ts";
export { subjectsSubjectIDQueryKey, subjectsSubjectIDQueryOptions, useSubjectsSubjectID } from "./SubjectsHooks/useSubjectsSubjectID.ts";
export { subjectsSubjectIDSuspenseQueryKey, subjectsSubjectIDSuspenseQueryOptions, useSubjectsSubjectIDSuspense } from "./SubjectsHooks/useSubjectsSubjectIDSuspense.ts";
export { subjectsSuspenseQueryKey, subjectsSuspenseQueryOptions, useSubjectsSuspense } from "./SubjectsHooks/useSubjectsSuspense.ts";
export { subtasksQueryKey, subtasksQueryOptions, useSubtasks } from "./SubtasksHooks/useSubtasks.ts";
export { subtasksCreateMutationKey, subtasksCreateMutationOptions, useSubtasksCreate } from "./SubtasksHooks/useSubtasksCreate.ts";
export { subtasksDeleteSubtaskIDMutationKey, subtasksDeleteSubtaskIDMutationOptions, useSubtasksDeleteSubtaskID } from "./SubtasksHooks/useSubtasksDeleteSubtaskID.ts";
export { subtasksSubtaskIDQueryKey, subtasksSubtaskIDQueryOptions, useSubtasksSubtaskID } from "./SubtasksHooks/useSubtasksSubtaskID.ts";
export { subtasksSubtaskIDSuspenseQueryKey, subtasksSubtaskIDSuspenseQueryOptions, useSubtasksSubtaskIDSuspense } from "./SubtasksHooks/useSubtasksSubtaskIDSuspense.ts";
export { subtasksSuspenseQueryKey, subtasksSuspenseQueryOptions, useSubtasksSuspense } from "./SubtasksHooks/useSubtasksSuspense.ts";
export { subtasksUpdateSubtaskIDMutationKey, subtasksUpdateSubtaskIDMutationOptions, useSubtasksUpdateSubtaskID } from "./SubtasksHooks/useSubtasksUpdateSubtaskID.ts";
export { tasksQueryKey, tasksQueryOptions, useTasks } from "./TasksHooks/useTasks.ts";
export { tasksSuspenseQueryKey, tasksSuspenseQueryOptions, useTasksSuspense } from "./TasksHooks/useTasksSuspense.ts";
export { tasksTaskIDQueryKey, tasksTaskIDQueryOptions, useTasksTaskID } from "./TasksHooks/useTasksTaskID.ts";
export { tasksTaskIDSuspenseQueryKey, tasksTaskIDSuspenseQueryOptions, useTasksTaskIDSuspense } from "./TasksHooks/useTasksTaskIDSuspense.ts";
export { variantsQueryKey, variantsQueryOptions, useVariants } from "./VariantsHooks/useVariants.ts";
export { variantsExecVariantIDStudentIDQueryKey, variantsExecVariantIDStudentIDQueryOptions, useVariantsExecVariantIDStudentID } from "./VariantsHooks/useVariantsExecVariantIDStudentID.ts";
export { variantsExecVariantIDStudentIDSuspenseQueryKey, variantsExecVariantIDStudentIDSuspenseQueryOptions, useVariantsExecVariantIDStudentIDSuspense } from "./VariantsHooks/useVariantsExecVariantIDStudentIDSuspense.ts";
export { variantsSuspenseQueryKey, variantsSuspenseQueryOptions, useVariantsSuspense } from "./VariantsHooks/useVariantsSuspense.ts";
export { variantsVariantIDQueryKey, variantsVariantIDQueryOptions, useVariantsVariantID } from "./VariantsHooks/useVariantsVariantID.ts";
export { variantsVariantIDSuspenseQueryKey, variantsVariantIDSuspenseQueryOptions, useVariantsVariantIDSuspense } from "./VariantsHooks/useVariantsVariantIDSuspense.ts";