/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksDeleteSubtaskIDMutationResponse, SubtasksDeleteSubtaskIDPathParams, SubtasksDeleteSubtaskID422 } from "../../types/Subtasks/SubtasksDeleteSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { subtasksDeleteSubtaskID } from "../../services/SubtasksService/subtasksDeleteSubtaskID.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const subtasksDeleteSubtaskIDMutationKey = () => [{ url: '/api/subtasks/delete/:subtask_id' }] as const

export type SubtasksDeleteSubtaskIDMutationKey = ReturnType<typeof subtasksDeleteSubtaskIDMutationKey>

export function subtasksDeleteSubtaskIDMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = subtasksDeleteSubtaskIDMutationKey()
  return mutationOptions<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, {subtask_id: SubtasksDeleteSubtaskIDPathParams["subtask_id"]}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ subtask_id }) => {
      return subtasksDeleteSubtaskID(subtask_id, config)
    },
  })
}

/**
 * @description Удаляет подзадачу, все её файлы и записи из таблиц
 * @summary Удаление подзадачи
 * {@link /api/subtasks/delete/:subtask_id}
 */
export function useSubtasksDeleteSubtaskID<TContext>(options: 
{
  mutation?: UseMutationOptions<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, {subtask_id: SubtasksDeleteSubtaskIDPathParams["subtask_id"]}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? subtasksDeleteSubtaskIDMutationKey()

  const baseOptions = subtasksDeleteSubtaskIDMutationOptions(config) as UseMutationOptions<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, {subtask_id: SubtasksDeleteSubtaskIDPathParams["subtask_id"]}, TContext>

  return useMutation<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, {subtask_id: SubtasksDeleteSubtaskIDPathParams["subtask_id"]}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SubtasksDeleteSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksDeleteSubtaskID422>, {subtask_id: SubtasksDeleteSubtaskIDPathParams["subtask_id"]}, TContext>
}