/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksQueryResponse, SubtasksQueryParams, Subtasks422 } from "../../types/Subtasks/Subtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { subtasks } from "../../services/SubtasksService/subtasks.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const subtasksQueryKey = (params?: SubtasksQueryParams) => [{ url: '/api/subtasks' }, ...(params ? [params] : [])] as const

export type SubtasksQueryKey = ReturnType<typeof subtasksQueryKey>

export function subtasksQueryOptions(params?: SubtasksQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = subtasksQueryKey(params)
  return queryOptions<SubtasksQueryResponse, ResponseErrorConfig<Subtasks422>, SubtasksQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return subtasks(params, config)
   },
  })
}

/**
 * @description Возвращает список всех подзадач с их блоками и прикрепленными файлами.          Подзадачи могут фильтроваться по параметрам: SubTaskID, TaskID, SubjectID, VariantID,           Search, UploadDate, Creator, сортироваться по любым колонкам и ограничиваться диапазоном           через Offset и Limit.
 * @summary Получение всех задач с блоками и дополнительными файлами
 * {@link /api/subtasks}
 */
export function useSubtasks<TData = SubtasksQueryResponse, TQueryData = SubtasksQueryResponse, TQueryKey extends QueryKey = SubtasksQueryKey>(params?: SubtasksQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<SubtasksQueryResponse, ResponseErrorConfig<Subtasks422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? subtasksQueryKey(params)

  const query = useQuery({
   ...subtasksQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Subtasks422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}