/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksUpdateSubtaskIDMutationRequest, SubtasksUpdateSubtaskIDMutationResponse, SubtasksUpdateSubtaskIDPathParams, SubtasksUpdateSubtaskID422 } from "../../types/Subtasks/SubtasksUpdateSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { subtasksUpdateSubtaskID } from "../../services/SubtasksService/subtasksUpdateSubtaskID.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const subtasksUpdateSubtaskIDMutationKey = () => [{ url: '/api/subtasks/update/:subtask_id' }] as const

export type SubtasksUpdateSubtaskIDMutationKey = ReturnType<typeof subtasksUpdateSubtaskIDMutationKey>

export function subtasksUpdateSubtaskIDMutationOptions(config: Partial<RequestConfig<SubtasksUpdateSubtaskIDMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = subtasksUpdateSubtaskIDMutationKey()
  return mutationOptions<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, {subtask_id: SubtasksUpdateSubtaskIDPathParams["subtask_id"], data: SubtasksUpdateSubtaskIDMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ subtask_id, data }) => {
      return subtasksUpdateSubtaskID(subtask_id, data, config)
    },
  })
}

/**
 * @description Заменяет старые значения на новые!(старые файлы удаляются и записываются новые).
 * @summary Полное обновление задачи с блоками и файлами
 * {@link /api/subtasks/update/:subtask_id}
 */
export function useSubtasksUpdateSubtaskID<TContext>(options: 
{
  mutation?: UseMutationOptions<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, {subtask_id: SubtasksUpdateSubtaskIDPathParams["subtask_id"], data: SubtasksUpdateSubtaskIDMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SubtasksUpdateSubtaskIDMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? subtasksUpdateSubtaskIDMutationKey()

  const baseOptions = subtasksUpdateSubtaskIDMutationOptions(config) as UseMutationOptions<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, {subtask_id: SubtasksUpdateSubtaskIDPathParams["subtask_id"], data: SubtasksUpdateSubtaskIDMutationRequest}, TContext>

  return useMutation<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, {subtask_id: SubtasksUpdateSubtaskIDPathParams["subtask_id"], data: SubtasksUpdateSubtaskIDMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SubtasksUpdateSubtaskIDMutationResponse, ResponseErrorConfig<SubtasksUpdateSubtaskID422>, {subtask_id: SubtasksUpdateSubtaskIDPathParams["subtask_id"], data: SubtasksUpdateSubtaskIDMutationRequest}, TContext>
}