/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksSubtaskIDQueryResponse, SubtasksSubtaskIDPathParams, SubtasksSubtaskID422 } from "../../types/Subtasks/SubtasksSubtaskID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { subtasksSubtaskID } from "../../services/SubtasksService/subtasksSubtaskID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const subtasksSubtaskIDSuspenseQueryKey = (subtask_id: SubtasksSubtaskIDPathParams["subtask_id"]) => [{ url: '/api/subtasks/:subtask_id', params: {subtask_id:subtask_id} }] as const

export type SubtasksSubtaskIDSuspenseQueryKey = ReturnType<typeof subtasksSubtaskIDSuspenseQueryKey>

export function subtasksSubtaskIDSuspenseQueryOptions(subtask_id: SubtasksSubtaskIDPathParams["subtask_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = subtasksSubtaskIDSuspenseQueryKey(subtask_id)
  return queryOptions<SubtasksSubtaskIDQueryResponse, ResponseErrorConfig<SubtasksSubtaskID422>, SubtasksSubtaskIDQueryResponse, typeof queryKey>({
   enabled: !!(subtask_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return subtasksSubtaskID(subtask_id, config)
   },
  })
}

/**
 * @description Возвращает задачу с текстовыми, графическими и другими блоками, а также прикрепленные файлы.
 * @summary Получение задачи с блоками и с дополнительными файлами
 * {@link /api/subtasks/:subtask_id}
 */
export function useSubtasksSubtaskIDSuspense<TData = SubtasksSubtaskIDQueryResponse, TQueryKey extends QueryKey = SubtasksSubtaskIDSuspenseQueryKey>(subtask_id: SubtasksSubtaskIDPathParams["subtask_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<SubtasksSubtaskIDQueryResponse, ResponseErrorConfig<SubtasksSubtaskID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? subtasksSubtaskIDSuspenseQueryKey(subtask_id)

  const query = useSuspenseQuery({
   ...subtasksSubtaskIDSuspenseQueryOptions(subtask_id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<SubtasksSubtaskID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}