/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubtasksCreateMutationRequest, SubtasksCreateMutationResponse, SubtasksCreate422 } from "../../types/Subtasks/SubtasksCreate.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { subtasksCreate } from "../../services/SubtasksService/subtasksCreate.ts";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const subtasksCreateMutationKey = () => [{ url: '/api/subtasks/create' }] as const

export type SubtasksCreateMutationKey = ReturnType<typeof subtasksCreateMutationKey>

export function subtasksCreateMutationOptions(config: Partial<RequestConfig<SubtasksCreateMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = subtasksCreateMutationKey()
  return mutationOptions<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, {data: SubtasksCreateMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return subtasksCreate(data, config)
    },
  })
}

/**
 * @description Создает задачу с текстовыми, графическими и другими блоками.  Поддерживает прикрепление файлов через multipart/form-data.  возвращает `files_blocks` - количество вставленных файлов с изображением задачи  `files_solution` - количество вставленных файлов с решением задачи  `files` - количество вставленных дополнительных файлов к задачи
 * @summary Создание задачи с файлами и блоками
 * {@link /api/subtasks/create}
 */
export function useSubtasksCreate<TContext>(options: 
{
  mutation?: UseMutationOptions<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, {data: SubtasksCreateMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<SubtasksCreateMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? subtasksCreateMutationKey()

  const baseOptions = subtasksCreateMutationOptions(config) as UseMutationOptions<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, {data: SubtasksCreateMutationRequest}, TContext>

  return useMutation<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, {data: SubtasksCreateMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<SubtasksCreateMutationResponse, ResponseErrorConfig<SubtasksCreate422>, {data: SubtasksCreateMutationRequest}, TContext>
}