/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { TaskListResponse } from "../TaskListResponse.ts";

export interface TasksQueryParams {
    /**
     * @description ID предмета для фильтрации
    */
    subjectID?: (number | null);
}

/**
 * @description Successful Response
*/
export type Tasks200 = TaskListResponse;

/**
 * @description Validation Error
*/
export type Tasks422 = HTTPValidationError;

export type TasksQueryResponse = Tasks200;

export type TasksQuery = {
    Response: Tasks200;
    QueryParams: TasksQueryParams;
    Errors: Tasks422;
};