/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface TasksTaskIDPathParams {
    /**
     * @type integer
    */
    task_id: number;
}

/**
 * @description Successful Response
*/
export type TasksTaskID200 = unknown;

/**
 * @description Validation Error
*/
export type TasksTaskID422 = HTTPValidationError;

export type TasksTaskIDQueryResponse = TasksTaskID200;

export type TasksTaskIDQuery = {
    Response: TasksTaskID200;
    PathParams: TasksTaskIDPathParams;
    Errors: TasksTaskID422;
};