/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsExecVariantIDStudentIDQueryResponse, VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID422 } from "../../types/Variants/VariantsExecVariantIDStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { variantsExecVariantIDStudentID } from "../../services/VariantsService/variantsExecVariantIDStudentID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const variantsExecVariantIDStudentIDSuspenseQueryKey = (VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"]) => [{ url: '/api/variants/exec/:VariantID/:StudentID', params: {VariantID:VariantID,StudentID:StudentID} }] as const

export type VariantsExecVariantIDStudentIDSuspenseQueryKey = ReturnType<typeof variantsExecVariantIDStudentIDSuspenseQueryKey>

export function variantsExecVariantIDStudentIDSuspenseQueryOptions(VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = variantsExecVariantIDStudentIDSuspenseQueryKey(VariantID, StudentID)
  return queryOptions<VariantsExecVariantIDStudentIDQueryResponse, ResponseErrorConfig<VariantsExecVariantIDStudentID422>, VariantsExecVariantIDStudentIDQueryResponse, typeof queryKey>({
   enabled: !!(VariantID&& StudentID),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return variantsExecVariantIDStudentID(VariantID, StudentID, config)
   },
  })
}

/**
 * @summary роут с вызовом хранимой процедуры
 * {@link /api/variants/exec/:VariantID/:StudentID}
 */
export function useVariantsExecVariantIDStudentIDSuspense<TData = VariantsExecVariantIDStudentIDQueryResponse, TQueryKey extends QueryKey = VariantsExecVariantIDStudentIDSuspenseQueryKey>(VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<VariantsExecVariantIDStudentIDQueryResponse, ResponseErrorConfig<VariantsExecVariantIDStudentID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? variantsExecVariantIDStudentIDSuspenseQueryKey(VariantID, StudentID)

  const query = useSuspenseQuery({
   ...variantsExecVariantIDStudentIDSuspenseQueryOptions(VariantID, StudentID, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<VariantsExecVariantIDStudentID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}