/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsVariantIDQueryResponse, VariantsVariantIDPathParams, VariantsVariantID422 } from "../../types/Variants/VariantsVariantID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { variantsVariantID } from "../../services/VariantsService/variantsVariantID.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const variantsVariantIDQueryKey = (variant_id: VariantsVariantIDPathParams["variant_id"]) => [{ url: '/api/variants/:variant_id', params: {variant_id:variant_id} }] as const

export type VariantsVariantIDQueryKey = ReturnType<typeof variantsVariantIDQueryKey>

export function variantsVariantIDQueryOptions(variant_id: VariantsVariantIDPathParams["variant_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = variantsVariantIDQueryKey(variant_id)
  return queryOptions<VariantsVariantIDQueryResponse, ResponseErrorConfig<VariantsVariantID422>, VariantsVariantIDQueryResponse, typeof queryKey>({
   enabled: !!(variant_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return variantsVariantID(variant_id, config)
   },
  })
}

/**
 * @summary Получить вариант по его variant_id
 * {@link /api/variants/:variant_id}
 */
export function useVariantsVariantID<TData = VariantsVariantIDQueryResponse, TQueryData = VariantsVariantIDQueryResponse, TQueryKey extends QueryKey = VariantsVariantIDQueryKey>(variant_id: VariantsVariantIDPathParams["variant_id"], options: 
{
  query?: Partial<QueryObserverOptions<VariantsVariantIDQueryResponse, ResponseErrorConfig<VariantsVariantID422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? variantsVariantIDQueryKey(variant_id)

  const query = useQuery({
   ...variantsVariantIDQueryOptions(variant_id, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<VariantsVariantID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}