/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsVariantIDQueryResponse, VariantsVariantIDPathParams, VariantsVariantID422 } from "../../types/Variants/VariantsVariantID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { variantsVariantID } from "../../services/VariantsService/variantsVariantID.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const variantsVariantIDSuspenseQueryKey = (variant_id: VariantsVariantIDPathParams["variant_id"]) => [{ url: '/api/variants/:variant_id', params: {variant_id:variant_id} }] as const

export type VariantsVariantIDSuspenseQueryKey = ReturnType<typeof variantsVariantIDSuspenseQueryKey>

export function variantsVariantIDSuspenseQueryOptions(variant_id: VariantsVariantIDPathParams["variant_id"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = variantsVariantIDSuspenseQueryKey(variant_id)
  return queryOptions<VariantsVariantIDQueryResponse, ResponseErrorConfig<VariantsVariantID422>, VariantsVariantIDQueryResponse, typeof queryKey>({
   enabled: !!(variant_id),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return variantsVariantID(variant_id, config)
   },
  })
}

/**
 * @summary Получить вариант по его variant_id
 * {@link /api/variants/:variant_id}
 */
export function useVariantsVariantIDSuspense<TData = VariantsVariantIDQueryResponse, TQueryKey extends QueryKey = VariantsVariantIDSuspenseQueryKey>(variant_id: VariantsVariantIDPathParams["variant_id"], options: 
{
  query?: Partial<UseSuspenseQueryOptions<VariantsVariantIDQueryResponse, ResponseErrorConfig<VariantsVariantID422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? variantsVariantIDSuspenseQueryKey(variant_id)

  const query = useSuspenseQuery({
   ...variantsVariantIDSuspenseQueryOptions(variant_id, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<VariantsVariantID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}