/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsExecVariantIDStudentIDQueryResponse, VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID422 } from "../../types/Variants/VariantsExecVariantIDStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { variantsExecVariantIDStudentID } from "../../services/VariantsService/variantsExecVariantIDStudentID.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const variantsExecVariantIDStudentIDQueryKey = (VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"]) => [{ url: '/api/variants/exec/:VariantID/:StudentID', params: {VariantID:VariantID,StudentID:StudentID} }] as const

export type VariantsExecVariantIDStudentIDQueryKey = ReturnType<typeof variantsExecVariantIDStudentIDQueryKey>

export function variantsExecVariantIDStudentIDQueryOptions(VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"], config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = variantsExecVariantIDStudentIDQueryKey(VariantID, StudentID)
  return queryOptions<VariantsExecVariantIDStudentIDQueryResponse, ResponseErrorConfig<VariantsExecVariantIDStudentID422>, VariantsExecVariantIDStudentIDQueryResponse, typeof queryKey>({
   enabled: !!(VariantID&& StudentID),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return variantsExecVariantIDStudentID(VariantID, StudentID, config)
   },
  })
}

/**
 * @summary роут с вызовом хранимой процедуры
 * {@link /api/variants/exec/:VariantID/:StudentID}
 */
export function useVariantsExecVariantIDStudentID<TData = VariantsExecVariantIDStudentIDQueryResponse, TQueryData = VariantsExecVariantIDStudentIDQueryResponse, TQueryKey extends QueryKey = VariantsExecVariantIDStudentIDQueryKey>(VariantID: VariantsExecVariantIDStudentIDPathParams["VariantID"], StudentID: VariantsExecVariantIDStudentIDPathParams["StudentID"], options: 
{
  query?: Partial<QueryObserverOptions<VariantsExecVariantIDStudentIDQueryResponse, ResponseErrorConfig<VariantsExecVariantIDStudentID422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? variantsExecVariantIDStudentIDQueryKey(VariantID, StudentID)

  const query = useQuery({
   ...variantsExecVariantIDStudentIDQueryOptions(VariantID, StudentID, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<VariantsExecVariantIDStudentID422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}