/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { VariantsQueryResponse, VariantsQueryParams, Variants422 } from "../../types/Variants/Variants.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { variants } from "../../services/VariantsService/variants.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const variantsSuspenseQueryKey = (params?: VariantsQueryParams) => [{ url: '/api/variants' }, ...(params ? [params] : [])] as const

export type VariantsSuspenseQueryKey = ReturnType<typeof variantsSuspenseQueryKey>

export function variantsSuspenseQueryOptions(params?: VariantsQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = variantsSuspenseQueryKey(params)
  return queryOptions<VariantsQueryResponse, ResponseErrorConfig<Variants422>, VariantsQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return variants(params, config)
   },
  })
}

/**
 * @description Если передан параметр **subject_id**, то возвращаются варианты только для указанного предмета.                              Если параметр не передан, возвращаются варианты по всем предметам.                              **subjectID** передается как Query-параметр                                       "`/api/variants` — все варианты"                                      "`/api/variants?subjectID=10` — варианты для предмета с subject ID 10"                                      так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список вариантов
 * {@link /api/variants}
 */
export function useVariantsSuspense<TData = VariantsQueryResponse, TQueryKey extends QueryKey = VariantsSuspenseQueryKey>(params?: VariantsQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<VariantsQueryResponse, ResponseErrorConfig<Variants422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? variantsSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...variantsSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Variants422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}