/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodySubtasksUpdateSubtaskID } from "../BodySubtasksUpdateSubtaskID.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface SubtasksUpdateSubtaskIDPathParams {
    /**
     * @type integer
    */
    subtask_id: number;
}

/**
 * @description Successful Response
*/
export type SubtasksUpdateSubtaskID200 = unknown;

/**
 * @description Validation Error
*/
export type SubtasksUpdateSubtaskID422 = HTTPValidationError;

export type SubtasksUpdateSubtaskIDMutationRequest = BodySubtasksUpdateSubtaskID;

export type SubtasksUpdateSubtaskIDMutationResponse = SubtasksUpdateSubtaskID200;

export type SubtasksUpdateSubtaskIDMutation = {
    Response: SubtasksUpdateSubtaskID200;
    Request: SubtasksUpdateSubtaskIDMutationRequest;
    PathParams: SubtasksUpdateSubtaskIDPathParams;
    Errors: SubtasksUpdateSubtaskID422;
};