/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface SubtasksDeleteSubtaskIDPathParams {
    /**
     * @type integer
    */
    subtask_id: number;
}

/**
 * @description Successful Response
*/
export type SubtasksDeleteSubtaskID200 = unknown;

/**
 * @description Validation Error
*/
export type SubtasksDeleteSubtaskID422 = HTTPValidationError;

export type SubtasksDeleteSubtaskIDMutationResponse = SubtasksDeleteSubtaskID200;

export type SubtasksDeleteSubtaskIDMutation = {
    Response: SubtasksDeleteSubtaskID200;
    PathParams: SubtasksDeleteSubtaskIDPathParams;
    Errors: SubtasksDeleteSubtaskID422;
};