/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface SubtasksSubtaskIDPathParams {
    /**
     * @type integer
    */
    subtask_id: number;
}

/**
 * @description Successful Response
*/
export type SubtasksSubtaskID200 = unknown;

/**
 * @description Validation Error
*/
export type SubtasksSubtaskID422 = HTTPValidationError;

export type SubtasksSubtaskIDQueryResponse = SubtasksSubtaskID200;

export type SubtasksSubtaskIDQuery = {
    Response: SubtasksSubtaskID200;
    PathParams: SubtasksSubtaskIDPathParams;
    Errors: SubtasksSubtaskID422;
};