/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { BodySubtasksCreate } from "../BodySubtasksCreate.ts";
import type { HTTPValidationError } from "../HTTPValidationError.ts";

/**
 * @description Successful Response
*/
export type SubtasksCreate200 = unknown;

/**
 * @description Validation Error
*/
export type SubtasksCreate422 = HTTPValidationError;

export type SubtasksCreateMutationRequest = BodySubtasksCreate;

export type SubtasksCreateMutationResponse = SubtasksCreate200;

export type SubtasksCreateMutation = {
    Response: SubtasksCreate200;
    Request: SubtasksCreateMutationRequest;
    Errors: SubtasksCreate422;
};