/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";

export interface SubtasksQueryParams {
    subtask_id?: (number | null);
    task_id?: (number | null);
    subject_id?: (number | null);
    variant_id?: (number | null);
    search?: (string | null);
    created_date?: (string | null);
    creator?: (string | null);
    /**
     * @default "SubTaskID"
    */
    sort_column1?: (string | null);
    /**
     * @default "SubTaskID"
    */
    sort_column2?: (string | null);
    /**
     * @default "ASC"
    */
    sort_direction1?: (string | null);
    /**
     * @default "ASC"
    */
    sort_direction2?: (string | null);
    /**
     * @default 0
    */
    p_offset?: (number | null);
    /**
     * @default 500000
    */
    p_limit?: (number | null);
}

/**
 * @description Successful Response
*/
export type Subtasks200 = unknown;

/**
 * @description Validation Error
*/
export type Subtasks422 = HTTPValidationError;

export type SubtasksQueryResponse = Subtasks200;

export type SubtasksQuery = {
    Response: Subtasks200;
    QueryParams: SubtasksQueryParams;
    Errors: Subtasks422;
};