/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthPasswordReset200, AuthPasswordReset422, AuthPasswordResetMutationRequest, AuthPasswordResetMutationResponse } from "../../types/Auth/AuthPasswordReset.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { passwordResetSchema } from "../passwordResetSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authPasswordReset200Schema = z.unknown() as unknown as z.ZodType<AuthPasswordReset200>

/**
 * @description Validation Error
 */
export const authPasswordReset422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthPasswordReset422>

export const authPasswordResetMutationRequestSchema = passwordResetSchema as unknown as z.ZodType<AuthPasswordResetMutationRequest>

export const authPasswordResetMutationResponseSchema = authPasswordReset200Schema as unknown as z.ZodType<AuthPasswordResetMutationResponse>