/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthChangePassword200, AuthChangePassword422, AuthChangePasswordMutationRequest, AuthChangePasswordMutationResponse } from "../../types/Auth/AuthChangePassword.ts";
import { changePasswordRequestSchema } from "../changePasswordRequestSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authChangePassword200Schema = z.unknown() as unknown as z.ZodType<AuthChangePassword200>

/**
 * @description Validation Error
 */
export const authChangePassword422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthChangePassword422>

export const authChangePasswordMutationRequestSchema = changePasswordRequestSchema as unknown as z.ZodType<AuthChangePasswordMutationRequest>

export const authChangePasswordMutationResponseSchema = authChangePassword200Schema as unknown as z.ZodType<AuthChangePasswordMutationResponse>