/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthPasswordResetWithToken200, AuthPasswordResetWithToken422, AuthPasswordResetWithTokenMutationRequest, AuthPasswordResetWithTokenMutationResponse } from "../../types/Auth/AuthPasswordResetWithToken.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { passwordResetConfirmSchema } from "../passwordResetConfirmSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authPasswordResetWithToken200Schema = z.unknown() as unknown as z.ZodType<AuthPasswordResetWithToken200>

/**
 * @description Validation Error
 */
export const authPasswordResetWithToken422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthPasswordResetWithToken422>

export const authPasswordResetWithTokenMutationRequestSchema = passwordResetConfirmSchema as unknown as z.ZodType<AuthPasswordResetWithTokenMutationRequest>

export const authPasswordResetWithTokenMutationResponseSchema = authPasswordResetWithToken200Schema as unknown as z.ZodType<AuthPasswordResetWithTokenMutationResponse>