/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthRegister200, AuthRegister422, AuthRegisterMutationRequest, AuthRegisterMutationResponse } from "../../types/Auth/AuthRegister.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { userCreateSchema } from "../userCreateSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authRegister200Schema = z.unknown() as unknown as z.ZodType<AuthRegister200>

/**
 * @description Validation Error
 */
export const authRegister422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthRegister422>

export const authRegisterMutationRequestSchema = userCreateSchema as unknown as z.ZodType<AuthRegisterMutationRequest>

export const authRegisterMutationResponseSchema = authRegister200Schema as unknown as z.ZodType<AuthRegisterMutationResponse>