/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthLogout200, AuthLogoutMutationResponse } from "../../types/Auth/AuthLogout.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authLogout200Schema = z.unknown() as unknown as z.ZodType<AuthLogout200>

export const authLogoutMutationResponseSchema = authLogout200Schema as unknown as z.ZodType<AuthLogoutMutationResponse>