/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthCheckToken200, AuthCheckTokenQueryResponse } from "../../types/Auth/AuthCheckToken.ts";
import { studentOutSchema } from "../studentOutSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authCheckToken200Schema = studentOutSchema as unknown as z.ZodType<AuthCheckToken200>

export const authCheckTokenQueryResponseSchema = authCheckToken200Schema as unknown as z.ZodType<AuthCheckTokenQueryResponse>