/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthConfirmEmailQueryParams, AuthConfirmEmail200, AuthConfirmEmail422, AuthConfirmEmailQueryResponse } from "../../types/Auth/AuthConfirmEmail.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const authConfirmEmailQueryParamsSchema = z.object({
    "token": z.string()
    }) as unknown as z.ZodType<AuthConfirmEmailQueryParams>

/**
 * @description Successful Response
 */
export const authConfirmEmail200Schema = z.unknown() as unknown as z.ZodType<AuthConfirmEmail200>

/**
 * @description Validation Error
 */
export const authConfirmEmail422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthConfirmEmail422>

export const authConfirmEmailQueryResponseSchema = authConfirmEmail200Schema as unknown as z.ZodType<AuthConfirmEmailQueryResponse>