/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AuthLogin200, AuthLogin422, AuthLoginMutationRequest, AuthLoginMutationResponse } from "../../types/Auth/AuthLogin.ts";
import { authRequestSchema } from "../authRequestSchema.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { tokenWithStudentSchema } from "../tokenWithStudentSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const authLogin200Schema = tokenWithStudentSchema as unknown as z.ZodType<AuthLogin200>

/**
 * @description Validation Error
 */
export const authLogin422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<AuthLogin422>

export const authLoginMutationRequestSchema = authRequestSchema as unknown as z.ZodType<AuthLoginMutationRequest>

export const authLoginMutationResponseSchema = authLogin200Schema as unknown as z.ZodType<AuthLoginMutationResponse>