/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HTTPValidationError } from "../HTTPValidationError.ts";
import type { SubjectRead } from "../SubjectRead.ts";

export interface SubjectsSubjectIDPathParams {
    /**
     * @type integer
    */
    subjectID: number;
}

/**
 * @description Successful Response
*/
export type SubjectsSubjectID200 = SubjectRead;

/**
 * @description Validation Error
*/
export type SubjectsSubjectID422 = HTTPValidationError;

export type SubjectsSubjectIDQueryResponse = SubjectsSubjectID200;

export type SubjectsSubjectIDQuery = {
    Response: SubjectsSubjectID200;
    PathParams: SubjectsSubjectIDPathParams;
    Errors: SubjectsSubjectID422;
};