/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SubjectListResponse } from "../SubjectListResponse.ts";

/**
 * @description Successful Response
*/
export type Subjects200 = SubjectListResponse;

export type SubjectsQueryResponse = Subjects200;

export type SubjectsQuery = {
    Response: Subjects200;
    Errors: any;
};