/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TasksTaskIDPathParams, TasksTaskID200, TasksTaskID422, TasksTaskIDQueryResponse } from "../../types/Tasks/TasksTaskID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const tasksTaskIDPathParamsSchema = z.object({
    "task_id": z.coerce.number().int()
    }) as unknown as z.ZodType<TasksTaskIDPathParams>

/**
 * @description Successful Response
 */
export const tasksTaskID200Schema = z.unknown() as unknown as z.ZodType<TasksTaskID200>

/**
 * @description Validation Error
 */
export const tasksTaskID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<TasksTaskID422>

export const tasksTaskIDQueryResponseSchema = tasksTaskID200Schema as unknown as z.ZodType<TasksTaskIDQueryResponse>