/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TasksQueryParams, Tasks200, Tasks422, TasksQueryResponse } from "../../types/Tasks/Tasks.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { taskListResponseSchema } from "../taskListResponseSchema.ts";
import { z } from "zod";

export const tasksQueryParamsSchema = z.object({
    "subjectID": z.optional(z.union([z.coerce.number().int(), z.null()]).describe("ID предмета для фильтрации"))
    }).optional() as unknown as z.ZodType<TasksQueryParams>

/**
 * @description Successful Response
 */
export const tasks200Schema = taskListResponseSchema as unknown as z.ZodType<Tasks200>

/**
 * @description Validation Error
 */
export const tasks422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<Tasks422>

export const tasksQueryResponseSchema = tasks200Schema as unknown as z.ZodType<TasksQueryResponse>