/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteStudentQueryParams, DeleteStudent200, DeleteStudent422, DeleteStudentMutationResponse } from "../../types/Students/DeleteStudent.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentFieldSchema } from "../studentFieldSchema.ts";
import { z } from "zod";

export const deleteStudentQueryParamsSchema = z.object({
    get "field_name"(){
                return z.optional(z.union([studentFieldSchema, z.null()]))
              },
"value": z.string()
    }) as unknown as z.ZodType<DeleteStudentQueryParams>

/**
 * @description Successful Response
 */
export const deleteStudent200Schema = z.unknown() as unknown as z.ZodType<DeleteStudent200>

/**
 * @description Validation Error
 */
export const deleteStudent422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<DeleteStudent422>

export const deleteStudentMutationResponseSchema = deleteStudent200Schema as unknown as z.ZodType<DeleteStudentMutationResponse>