/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { EditStudentQueryParams, EditStudent200, EditStudent422, EditStudentMutationRequest, EditStudentMutationResponse } from "../../types/Students/EditStudent.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentEditSchema } from "../studentEditSchema.ts";
import { z } from "zod";

export const editStudentQueryParamsSchema = z.object({
    "id": z.coerce.number().int()
    }) as unknown as z.ZodType<EditStudentQueryParams>

/**
 * @description Successful Response
 */
export const editStudent200Schema = z.unknown() as unknown as z.ZodType<EditStudent200>

/**
 * @description Validation Error
 */
export const editStudent422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<EditStudent422>

export const editStudentMutationRequestSchema = studentEditSchema as unknown as z.ZodType<EditStudentMutationRequest>

export const editStudentMutationResponseSchema = editStudent200Schema as unknown as z.ZodType<EditStudentMutationResponse>