/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NewStudent200, NewStudent422, NewStudentMutationRequest, NewStudentMutationResponse } from "../../types/Students/NewStudent.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentCreateSchema } from "../studentCreateSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const newStudent200Schema = z.unknown() as unknown as z.ZodType<NewStudent200>

/**
 * @description Validation Error
 */
export const newStudent422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<NewStudent422>

export const newStudentMutationRequestSchema = studentCreateSchema as unknown as z.ZodType<NewStudentMutationRequest>

export const newStudentMutationResponseSchema = newStudent200Schema as unknown as z.ZodType<NewStudentMutationResponse>