/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentsSearchQueryParams, StudentsSearch200, StudentsSearch422, StudentsSearchQueryResponse } from "../../types/Students/StudentsSearch.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentFieldSchema } from "../studentFieldSchema.ts";
import { z } from "zod";

export const studentsSearchQueryParamsSchema = z.object({
    get "field_name"(){
                return studentFieldSchema
              },
"value": z.string()
    }) as unknown as z.ZodType<StudentsSearchQueryParams>

/**
 * @description Successful Response
 */
export const studentsSearch200Schema = z.unknown() as unknown as z.ZodType<StudentsSearch200>

/**
 * @description Validation Error
 */
export const studentsSearch422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<StudentsSearch422>

export const studentsSearchQueryResponseSchema = studentsSearch200Schema as unknown as z.ZodType<StudentsSearchQueryResponse>