/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Students200, StudentsQueryResponse, StudentsQueryParams, Students422, StudentsMutationResponse } from "../../types/Students/Students.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentOutSchema } from "../studentOutSchema.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const students200Schema = z.array(studentOutSchema) as unknown as z.ZodType<Students200>

export const studentsQueryResponseSchema = students200Schema as unknown as z.ZodType<StudentsQueryResponse>

export const studentsQueryParamsSchema = z.object({
    "id": z.coerce.number().int(),
"flag": z.boolean()
    }) as unknown as z.ZodType<StudentsQueryParams>

/**
 * @description Successful Response
 */
export const students200Schema = z.unknown() as unknown as z.ZodType<Students200>

/**
 * @description Validation Error
 */
export const students422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<Students422>

export const studentsMutationResponseSchema = students200Schema as unknown as z.ZodType<StudentsMutationResponse>