/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { StudentsStudentIDPathParams, StudentsStudentID200, StudentsStudentID422, StudentsStudentIDQueryResponse } from "../../types/Students/StudentsStudentID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { studentAuthSchema } from "../studentAuthSchema.ts";
import { z } from "zod";

export const studentsStudentIDPathParamsSchema = z.object({
    "student_id": z.coerce.number().int()
    }) as unknown as z.ZodType<StudentsStudentIDPathParams>

/**
 * @description Successful Response
 */
export const studentsStudentID200Schema = studentAuthSchema as unknown as z.ZodType<StudentsStudentID200>

/**
 * @description Validation Error
 */
export const studentsStudentID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<StudentsStudentID422>

export const studentsStudentIDQueryResponseSchema = studentsStudentID200Schema as unknown as z.ZodType<StudentsStudentIDQueryResponse>