/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { HealthCheckApiHealthGet200, HealthCheckApiHealthGetQueryResponse } from "../../types/Health/HealthCheckApiHealthGet.ts";
import { z } from "zod";

/**
 * @description Successful Response
 */
export const healthCheckApiHealthGet200Schema = z.unknown() as unknown as z.ZodType<HealthCheckApiHealthGet200>

export const healthCheckApiHealthGetQueryResponseSchema = healthCheckApiHealthGet200Schema as unknown as z.ZodType<HealthCheckApiHealthGetQueryResponse>