/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthConfirmEmailQueryResponse, AuthConfirmEmailQueryParams, AuthConfirmEmail422 } from "../../types/Auth/AuthConfirmEmail.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authConfirmEmailQueryResponseSchema } from "../../zod/AuthSchemas/authConfirmEmailSchema.ts";

function getAuthConfirmEmailUrl() {
  const res = { method: 'GET', url: `/api/auth/confirm-email` as const }  
  return res
}

/**
 * @description данный роут вызывается после открытия ссылки из письма с подтверждением email
 * @summary Подтверждение email
 * {@link /api/auth/confirm-email}
 */
export async function authConfirmEmail({ params }: { params: AuthConfirmEmailQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AuthConfirmEmailQueryResponse, ResponseErrorConfig<AuthConfirmEmail422>, unknown>({ method : "GET", url : getAuthConfirmEmailUrl().url.toString(), params, ... requestConfig })  
  return authConfirmEmailQueryResponseSchema.parse(res.data)
}