/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthChangePasswordMutationRequest, AuthChangePasswordMutationResponse, AuthChangePassword422 } from "../../types/Auth/AuthChangePassword.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authChangePasswordMutationResponseSchema, authChangePasswordMutationRequestSchema } from "../../zod/AuthSchemas/authChangePasswordSchema.ts";

function getAuthChangePasswordUrl() {
  const res = { method: 'POST', url: `/api/auth/change-password` as const }  
  return res
}

/**
 * @description пользователя получаем по токену, который передается из заголовка с frontend. Требуется проверка студента.
 * @summary Сменить пароль текущего пользователя (меняет сам пользователь)
 * {@link /api/auth/change-password}
 */
export async function authChangePassword({ data }: { data: AuthChangePasswordMutationRequest }, config: Partial<RequestConfig<AuthChangePasswordMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = authChangePasswordMutationRequestSchema.parse(data)  
  
  const res = await request<AuthChangePasswordMutationResponse, ResponseErrorConfig<AuthChangePassword422>, AuthChangePasswordMutationRequest>({ method : "POST", url : getAuthChangePasswordUrl().url.toString(), data : requestData, ... requestConfig })  
  return authChangePasswordMutationResponseSchema.parse(res.data)
}