/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthLoginMutationRequest, AuthLoginMutationResponse, AuthLogin422 } from "../../types/Auth/AuthLogin.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authLoginMutationResponseSchema, authLoginMutationRequestSchema } from "../../zod/AuthSchemas/authLoginSchema.ts";

function getAuthLoginUrl() {
  const res = { method: 'POST', url: `/api/auth/login` as const }  
  return res
}

/**
 * @description Возвращает токен, тип заголовка и небольшую информацию о пользователе, если (логин / email / телефон) и пароль корректны и пользователь активен.
 * @summary Аутентификация (запрос токена для пользователя (логин / email / телефон))
 * {@link /api/auth/login}
 */
export async function authLogin({ data }: { data: AuthLoginMutationRequest }, config: Partial<RequestConfig<AuthLoginMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = authLoginMutationRequestSchema.parse(data)  
  
  const res = await request<AuthLoginMutationResponse, ResponseErrorConfig<AuthLogin422>, AuthLoginMutationRequest>({ method : "POST", url : getAuthLoginUrl().url.toString(), data : requestData, ... requestConfig })  
  return authLoginMutationResponseSchema.parse(res.data)
}