/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthRegisterMutationRequest, AuthRegisterMutationResponse, AuthRegister422 } from "../../types/Auth/AuthRegister.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authRegisterMutationResponseSchema, authRegisterMutationRequestSchema } from "../../zod/AuthSchemas/authRegisterSchema.ts";

function getAuthRegisterUrl() {
  const res = { method: 'POST', url: `/api/auth/register` as const }  
  return res
}

/**
 * @description после ввода данных на указанный email отправляется письмо с подтверждением почты
 * @summary Регистрация пользователя
 * {@link /api/auth/register}
 */
export async function authRegister({ data }: { data: AuthRegisterMutationRequest }, config: Partial<RequestConfig<AuthRegisterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = authRegisterMutationRequestSchema.parse(data)  
  
  const res = await request<AuthRegisterMutationResponse, ResponseErrorConfig<AuthRegister422>, AuthRegisterMutationRequest>({ method : "POST", url : getAuthRegisterUrl().url.toString(), data : requestData, ... requestConfig })  
  return authRegisterMutationResponseSchema.parse(res.data)
}