/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthLogoutMutationResponse } from "../../types/Auth/AuthLogout.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authLogoutMutationResponseSchema } from "../../zod/AuthSchemas/authLogoutSchema.ts";

function getAuthLogoutUrl() {
  const res = { method: 'POST', url: `/api/auth/logout` as const }  
  return res
}

/**
 * @description Необходимо в заголовке отправлять токен (требуется для логироания выхода пользователя
 * @summary Выход, удаление токена при использовании 'HttpOnly cookie'
 * {@link /api/auth/logout}
 */
export async function authLogout(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AuthLogoutMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "POST", url : getAuthLogoutUrl().url.toString(), ... requestConfig })  
  return authLogoutMutationResponseSchema.parse(res.data)
}