/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthPasswordResetWithTokenMutationRequest, AuthPasswordResetWithTokenMutationResponse, AuthPasswordResetWithToken422 } from "../../types/Auth/AuthPasswordResetWithToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authPasswordResetWithTokenMutationResponseSchema, authPasswordResetWithTokenMutationRequestSchema } from "../../zod/AuthSchemas/authPasswordResetWithTokenSchema.ts";

function getAuthPasswordResetWithTokenUrl() {
  const res = { method: 'POST', url: `/api/auth/password_reset_with_token` as const }  
  return res
}

/**
 * @description на один токен идет только один сброс пароля, для повторного сброса надо запрашивать новый токен
 * @summary Сброс пароля по токену
 * {@link /api/auth/password_reset_with_token}
 */
export async function authPasswordResetWithToken({ data }: { data: AuthPasswordResetWithTokenMutationRequest }, config: Partial<RequestConfig<AuthPasswordResetWithTokenMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = authPasswordResetWithTokenMutationRequestSchema.parse(data)  
  
  const res = await request<AuthPasswordResetWithTokenMutationResponse, ResponseErrorConfig<AuthPasswordResetWithToken422>, AuthPasswordResetWithTokenMutationRequest>({ method : "POST", url : getAuthPasswordResetWithTokenUrl().url.toString(), data : requestData, ... requestConfig })  
  return authPasswordResetWithTokenMutationResponseSchema.parse(res.data)
}