/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthCheckTokenQueryResponse } from "../../types/Auth/AuthCheckToken.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authCheckTokenQueryResponseSchema } from "../../zod/AuthSchemas/authCheckTokenSchema.ts";

function getAuthCheckTokenUrl() {
  const res = { method: 'GET', url: `/api/auth/check-token` as const }  
  return res
}

/**
 * @summary Образец получения данных пользователя по токену (с разрешениями)
 * {@link /api/auth/check-token}
 */
export async function authCheckToken(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<AuthCheckTokenQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getAuthCheckTokenUrl().url.toString(), ... requestConfig })  
  return authCheckTokenQueryResponseSchema.parse(res.data)
}