/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { authChangePassword } from "./authChangePassword.ts";
import { authCheckToken } from "./authCheckToken.ts";
import { authConfirmEmail } from "./authConfirmEmail.ts";
import { authLogin } from "./authLogin.ts";
import { authLogout } from "./authLogout.ts";
import { authPasswordReset } from "./authPasswordReset.ts";
import { authPasswordResetWithToken } from "./authPasswordResetWithToken.ts";
import { authRegister } from "./authRegister.ts";

export function AuthService() {
  return { authLogin, authCheckToken, authRegister, authPasswordReset, authPasswordResetWithToken, authConfirmEmail, authLogout, authChangePassword }
}