/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { AuthPasswordResetMutationRequest, AuthPasswordResetMutationResponse, AuthPasswordReset422 } from "../../types/Auth/AuthPasswordReset.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { authPasswordResetMutationResponseSchema, authPasswordResetMutationRequestSchema } from "../../zod/AuthSchemas/authPasswordResetSchema.ts";

function getAuthPasswordResetUrl() {
  const res = { method: 'POST', url: `/api/auth/password_reset` as const }  
  return res
}

/**
 * @description Высылается письмо с ссылкой для сброса пароля с использованием временного токена, который вшит в ссылку                               `https://info-run.ru/auth/reset-password?token={token}`                                далее используется роут `/api/auth/password_reset_with_token` непосредственно для изменения пароля
 * @summary Запрос на сброс пароля
 * {@link /api/auth/password_reset}
 */
export async function authPasswordReset({ data }: { data: AuthPasswordResetMutationRequest }, config: Partial<RequestConfig<AuthPasswordResetMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = authPasswordResetMutationRequestSchema.parse(data)  
  
  const res = await request<AuthPasswordResetMutationResponse, ResponseErrorConfig<AuthPasswordReset422>, AuthPasswordResetMutationRequest>({ method : "POST", url : getAuthPasswordResetUrl().url.toString(), data : requestData, ... requestConfig })  
  return authPasswordResetMutationResponseSchema.parse(res.data)
}