/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VariantsVariantIDPathParams, VariantsVariantID200, VariantsVariantID422, VariantsVariantIDQueryResponse } from "../../types/Variants/VariantsVariantID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const variantsVariantIDPathParamsSchema = z.object({
    "variant_id": z.coerce.number().int()
    }) as unknown as z.ZodType<VariantsVariantIDPathParams>

/**
 * @description Successful Response
 */
export const variantsVariantID200Schema = z.unknown() as unknown as z.ZodType<VariantsVariantID200>

/**
 * @description Validation Error
 */
export const variantsVariantID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<VariantsVariantID422>

export const variantsVariantIDQueryResponseSchema = variantsVariantID200Schema as unknown as z.ZodType<VariantsVariantIDQueryResponse>