/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VariantsQueryParams, Variants200, Variants422, VariantsQueryResponse } from "../../types/Variants/Variants.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const variantsQueryParamsSchema = z.object({
    "subject_id": z.optional(z.union([z.coerce.number().int(), z.null()]).describe("ID предмета для фильтрации"))
    }).optional() as unknown as z.ZodType<VariantsQueryParams>

/**
 * @description Successful Response
 */
export const variants200Schema = z.unknown() as unknown as z.ZodType<Variants200>

/**
 * @description Validation Error
 */
export const variants422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<Variants422>

export const variantsQueryResponseSchema = variants200Schema as unknown as z.ZodType<VariantsQueryResponse>