/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VariantsExecVariantIDStudentIDPathParams, VariantsExecVariantIDStudentID200, VariantsExecVariantIDStudentID422, VariantsExecVariantIDStudentIDQueryResponse } from "../../types/Variants/VariantsExecVariantIDStudentID.ts";
import { HTTPValidationErrorSchema } from "../HTTPValidationErrorSchema.ts";
import { z } from "zod";

export const variantsExecVariantIDStudentIDPathParamsSchema = z.object({
    "VariantID": z.coerce.number().int(),
"StudentID": z.coerce.number().int()
    }) as unknown as z.ZodType<VariantsExecVariantIDStudentIDPathParams>

/**
 * @description Successful Response
 */
export const variantsExecVariantIDStudentID200Schema = z.unknown() as unknown as z.ZodType<VariantsExecVariantIDStudentID200>

/**
 * @description Validation Error
 */
export const variantsExecVariantIDStudentID422Schema = HTTPValidationErrorSchema as unknown as z.ZodType<VariantsExecVariantIDStudentID422>

export const variantsExecVariantIDStudentIDQueryResponseSchema = variantsExecVariantIDStudentID200Schema as unknown as z.ZodType<VariantsExecVariantIDStudentIDQueryResponse>