/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { DeleteStudentMutationResponse, DeleteStudentQueryParams, DeleteStudent422 } from "../../types/Students/DeleteStudent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { deleteStudentMutationResponseSchema } from "../../zod/StudentsSchemas/deleteStudentSchema.ts";

function getDeleteStudentUrl() {
  const res = { method: 'POST', url: `/api/students/delete_student` as const }  
  return res
}

/**
 * @summary Удаление студента выбранному полю
 * {@link /api/students/delete_student}
 */
export async function deleteStudent({ params }: { params: DeleteStudentQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<DeleteStudentMutationResponse, ResponseErrorConfig<DeleteStudent422>, unknown>({ method : "POST", url : getDeleteStudentUrl().url.toString(), params, ... requestConfig })  
  return deleteStudentMutationResponseSchema.parse(res.data)
}