/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { EditStudentMutationRequest, EditStudentMutationResponse, EditStudentQueryParams, EditStudent422 } from "../../types/Students/EditStudent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { editStudentMutationResponseSchema, editStudentMutationRequestSchema } from "../../zod/StudentsSchemas/editStudentSchema.ts";

function getEditStudentUrl() {
  const res = { method: 'PATCH', url: `/api/students/edit_student` as const }  
  return res
}

/**
 * @summary Изменение данных студента по id
 * {@link /api/students/edit_student}
 */
export async function editStudent({ data, params }: { data: EditStudentMutationRequest; params: EditStudentQueryParams }, config: Partial<RequestConfig<EditStudentMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = editStudentMutationRequestSchema.parse(data)  
  
  const res = await request<EditStudentMutationResponse, ResponseErrorConfig<EditStudent422>, EditStudentMutationRequest>({ method : "PATCH", url : getEditStudentUrl().url.toString(), params, data : requestData, ... requestConfig })  
  return editStudentMutationResponseSchema.parse(res.data)
}