/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { NewStudentMutationRequest, NewStudentMutationResponse, NewStudent422 } from "../../types/Students/NewStudent.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { newStudentMutationResponseSchema, newStudentMutationRequestSchema } from "../../zod/StudentsSchemas/newStudentSchema.ts";

function getNewStudentUrl() {
  const res = { method: 'POST', url: `/api/students/new_student` as const }  
  return res
}

/**
 * @description `Login`, `email` обязательный поля  (должны быть уникальными)    `Sex` может быть: М, Ж, пустой      `RoleID` именно id роли, а не её имя    `Phone` строка, но должна состоять из цифр
 * @summary Добавить нового студента
 * {@link /api/students/new_student}
 */
export async function newStudent({ data }: { data: NewStudentMutationRequest }, config: Partial<RequestConfig<NewStudentMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = newStudentMutationRequestSchema.parse(data)  
  
  const res = await request<NewStudentMutationResponse, ResponseErrorConfig<NewStudent422>, NewStudentMutationRequest>({ method : "POST", url : getNewStudentUrl().url.toString(), data : requestData, ... requestConfig })  
  return newStudentMutationResponseSchema.parse(res.data)
}