/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSearchQueryResponse, StudentsSearchQueryParams, StudentsSearch422 } from "../../types/Students/StudentsSearch.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { studentsSearchQueryResponseSchema } from "../../zod/StudentsSchemas/studentsSearchSchema.ts";

function getStudentsSearchUrl() {
  const res = { method: 'GET', url: `/api/students/search` as const }  
  return res
}

/**
 * @summary Поиск студента по выбранному полю(ID, Login, Email, Phone
 * {@link /api/students/search}
 */
export async function studentsSearch({ params }: { params: StudentsSearchQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsSearchQueryResponse, ResponseErrorConfig<StudentsSearch422>, unknown>({ method : "GET", url : getStudentsSearchUrl().url.toString(), params, ... requestConfig })  
  return studentsSearchQueryResponseSchema.parse(res.data)
}