/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { deleteStudent } from "./deleteStudent.ts";
import { editStudent } from "./editStudent.ts";
import { newStudent } from "./newStudent.ts";
import { students } from "./students.ts";
import { studentsSearch } from "./studentsSearch.ts";
import { studentsStudentID } from "./studentsStudentID.ts";

export function StudentsService() {
  return { students, studentsStudentID, studentsSearch, newStudent, editStudent, students, deleteStudent }
}