/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsStudentIDQueryResponse, StudentsStudentIDPathParams, StudentsStudentID422 } from "../../types/Students/StudentsStudentID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { studentsStudentIDQueryResponseSchema } from "../../zod/StudentsSchemas/studentsStudentIDSchema.ts";

function getStudentsStudentIDUrl({ studentId }: { studentId: StudentsStudentIDPathParams["student_id"] }) {
  const res = { method: 'GET', url: `/api/students/api/${studentId}` as const }  
  return res
}

/**
 * @summary Получить студента по его ID)
 * {@link /api/students/api/:student_id}
 */
export async function studentsStudentID({ studentId }: { studentId: StudentsStudentIDPathParams["student_id"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsStudentIDQueryResponse, ResponseErrorConfig<StudentsStudentID422>, unknown>({ method : "GET", url : getStudentsStudentIDUrl({ studentId }).url.toString(), ... requestConfig })  
  return studentsStudentIDQueryResponseSchema.parse(res.data)
}