/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsQueryResponse, StudentsMutationResponse, StudentsQueryParams, Students422 } from "../../types/Students/Students.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { studentsQueryResponseSchema, studentsMutationResponseSchema } from "../../zod/StudentsSchemas/studentsSchema.ts";

function getStudentsUrl() {
  const res = { method: 'GET', url: `/api/students` as const }  
  return res
}

/**
 * @summary Получить список студентов в формате JSON
 * {@link /api/students}
 */
export async function students(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getStudentsUrl().url.toString(), ... requestConfig })  
  return studentsQueryResponseSchema.parse(res.data)
}

function getStudentsUrl() {
  const res = { method: 'POST', url: `/api/students/active` as const }  
  return res
}

/**
 * @summary Активация/деакцтивация студента
 * {@link /api/students/active}
 */
export async function students({ params }: { params: StudentsQueryParams }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<StudentsMutationResponse, ResponseErrorConfig<Students422>, unknown>({ method : "POST", url : getStudentsUrl().url.toString(), params, ... requestConfig })  
  return studentsMutationResponseSchema.parse(res.data)
}