/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { HealthCheckApiHealthGetQueryResponse } from "../../types/Health/HealthCheckApiHealthGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { healthCheckApiHealthGet } from "../../services/HealthService/healthCheckApiHealthGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const healthCheckApiHealthGetQueryKey = () => [{ url: '/api/health' }] as const

export type HealthCheckApiHealthGetQueryKey = ReturnType<typeof healthCheckApiHealthGetQueryKey>

export function healthCheckApiHealthGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = healthCheckApiHealthGetQueryKey()
  return queryOptions<HealthCheckApiHealthGetQueryResponse, ResponseErrorConfig<Error>, HealthCheckApiHealthGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return healthCheckApiHealthGet(config)
   },
  })
}

/**
 * @description Проверка состояния сервиса.
 * @summary роут проверки конфигурации
 * {@link /api/health}
 */
export function useHealthCheckApiHealthGet<TData = HealthCheckApiHealthGetQueryResponse, TQueryData = HealthCheckApiHealthGetQueryResponse, TQueryKey extends QueryKey = HealthCheckApiHealthGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<HealthCheckApiHealthGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? healthCheckApiHealthGetQueryKey()

  const query = useQuery({
   ...healthCheckApiHealthGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}