/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { HealthCheckApiHealthGetQueryResponse } from "../../types/Health/HealthCheckApiHealthGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { healthCheckApiHealthGet } from "../../services/HealthService/healthCheckApiHealthGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const healthCheckApiHealthGetSuspenseQueryKey = () => [{ url: '/api/health' }] as const

export type HealthCheckApiHealthGetSuspenseQueryKey = ReturnType<typeof healthCheckApiHealthGetSuspenseQueryKey>

export function healthCheckApiHealthGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = healthCheckApiHealthGetSuspenseQueryKey()
  return queryOptions<HealthCheckApiHealthGetQueryResponse, ResponseErrorConfig<Error>, HealthCheckApiHealthGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return healthCheckApiHealthGet(config)
   },
  })
}

/**
 * @description Проверка состояния сервиса.
 * @summary роут проверки конфигурации
 * {@link /api/health}
 */
export function useHealthCheckApiHealthGetSuspense<TData = HealthCheckApiHealthGetQueryResponse, TQueryKey extends QueryKey = HealthCheckApiHealthGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<HealthCheckApiHealthGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? healthCheckApiHealthGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...healthCheckApiHealthGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}