/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetRedocDocumentationApiRedocGetQueryResponse } from "../../types/Default/GetRedocDocumentationApiRedocGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getRedocDocumentationApiRedocGet } from "../../services/DefaultService/getRedocDocumentationApiRedocGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getRedocDocumentationApiRedocGetSuspenseQueryKey = () => [{ url: '/api/redoc' }] as const

export type GetRedocDocumentationApiRedocGetSuspenseQueryKey = ReturnType<typeof getRedocDocumentationApiRedocGetSuspenseQueryKey>

export function getRedocDocumentationApiRedocGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRedocDocumentationApiRedocGetSuspenseQueryKey()
  return queryOptions<GetRedocDocumentationApiRedocGetQueryResponse, ResponseErrorConfig<Error>, GetRedocDocumentationApiRedocGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getRedocDocumentationApiRedocGet(config)
   },
  })
}

/**
 * @summary Get Redoc Documentation
 * {@link /api/redoc}
 */
export function useGetRedocDocumentationApiRedocGetSuspense<TData = GetRedocDocumentationApiRedocGetQueryResponse, TQueryKey extends QueryKey = GetRedocDocumentationApiRedocGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetRedocDocumentationApiRedocGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getRedocDocumentationApiRedocGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getRedocDocumentationApiRedocGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}