/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetRedocDocumentationApiRedocGetQueryResponse } from "../../types/Default/GetRedocDocumentationApiRedocGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getRedocDocumentationApiRedocGet } from "../../services/DefaultService/getRedocDocumentationApiRedocGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getRedocDocumentationApiRedocGetQueryKey = () => [{ url: '/api/redoc' }] as const

export type GetRedocDocumentationApiRedocGetQueryKey = ReturnType<typeof getRedocDocumentationApiRedocGetQueryKey>

export function getRedocDocumentationApiRedocGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getRedocDocumentationApiRedocGetQueryKey()
  return queryOptions<GetRedocDocumentationApiRedocGetQueryResponse, ResponseErrorConfig<Error>, GetRedocDocumentationApiRedocGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getRedocDocumentationApiRedocGet(config)
   },
  })
}

/**
 * @summary Get Redoc Documentation
 * {@link /api/redoc}
 */
export function useGetRedocDocumentationApiRedocGet<TData = GetRedocDocumentationApiRedocGetQueryResponse, TQueryData = GetRedocDocumentationApiRedocGetQueryResponse, TQueryKey extends QueryKey = GetRedocDocumentationApiRedocGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetRedocDocumentationApiRedocGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getRedocDocumentationApiRedocGetQueryKey()

  const query = useQuery({
   ...getRedocDocumentationApiRedocGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}