/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetDocumentationApiDocsGetQueryResponse } from "../../types/Default/GetDocumentationApiDocsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { getDocumentationApiDocsGet } from "../../services/DefaultService/getDocumentationApiDocsGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getDocumentationApiDocsGetSuspenseQueryKey = () => [{ url: '/api/docs' }] as const

export type GetDocumentationApiDocsGetSuspenseQueryKey = ReturnType<typeof getDocumentationApiDocsGetSuspenseQueryKey>

export function getDocumentationApiDocsGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDocumentationApiDocsGetSuspenseQueryKey()
  return queryOptions<GetDocumentationApiDocsGetQueryResponse, ResponseErrorConfig<Error>, GetDocumentationApiDocsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDocumentationApiDocsGet(config)
   },
  })
}

/**
 * @summary Get Documentation
 * {@link /api/docs}
 */
export function useGetDocumentationApiDocsGetSuspense<TData = GetDocumentationApiDocsGetQueryResponse, TQueryKey extends QueryKey = GetDocumentationApiDocsGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetDocumentationApiDocsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDocumentationApiDocsGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getDocumentationApiDocsGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}