/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { GetDocumentationApiDocsGetQueryResponse } from "../../types/Default/GetDocumentationApiDocsGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { getDocumentationApiDocsGet } from "../../services/DefaultService/getDocumentationApiDocsGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getDocumentationApiDocsGetQueryKey = () => [{ url: '/api/docs' }] as const

export type GetDocumentationApiDocsGetQueryKey = ReturnType<typeof getDocumentationApiDocsGetQueryKey>

export function getDocumentationApiDocsGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getDocumentationApiDocsGetQueryKey()
  return queryOptions<GetDocumentationApiDocsGetQueryResponse, ResponseErrorConfig<Error>, GetDocumentationApiDocsGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getDocumentationApiDocsGet(config)
   },
  })
}

/**
 * @summary Get Documentation
 * {@link /api/docs}
 */
export function useGetDocumentationApiDocsGet<TData = GetDocumentationApiDocsGetQueryResponse, TQueryData = GetDocumentationApiDocsGetQueryResponse, TQueryKey extends QueryKey = GetDocumentationApiDocsGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetDocumentationApiDocsGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getDocumentationApiDocsGetQueryKey()

  const query = useQuery({
   ...getDocumentationApiDocsGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}