/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { OpenapiApiOpenapiJsonGetQueryResponse } from "../../types/Default/OpenapiApiOpenapiJsonGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { openapiApiOpenapiJsonGet } from "../../services/DefaultService/openapiApiOpenapiJsonGet.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const openapiApiOpenapiJsonGetQueryKey = () => [{ url: '/api/openapi.json' }] as const

export type OpenapiApiOpenapiJsonGetQueryKey = ReturnType<typeof openapiApiOpenapiJsonGetQueryKey>

export function openapiApiOpenapiJsonGetQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = openapiApiOpenapiJsonGetQueryKey()
  return queryOptions<OpenapiApiOpenapiJsonGetQueryResponse, ResponseErrorConfig<Error>, OpenapiApiOpenapiJsonGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return openapiApiOpenapiJsonGet(config)
   },
  })
}

/**
 * @summary Openapi
 * {@link /api/openapi.json}
 */
export function useOpenapiApiOpenapiJsonGet<TData = OpenapiApiOpenapiJsonGetQueryResponse, TQueryData = OpenapiApiOpenapiJsonGetQueryResponse, TQueryKey extends QueryKey = OpenapiApiOpenapiJsonGetQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<OpenapiApiOpenapiJsonGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? openapiApiOpenapiJsonGetQueryKey()

  const query = useQuery({
   ...openapiApiOpenapiJsonGetQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}