/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { OpenapiApiOpenapiJsonGetQueryResponse } from "../../types/Default/OpenapiApiOpenapiJsonGet.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { openapiApiOpenapiJsonGet } from "../../services/DefaultService/openapiApiOpenapiJsonGet.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const openapiApiOpenapiJsonGetSuspenseQueryKey = () => [{ url: '/api/openapi.json' }] as const

export type OpenapiApiOpenapiJsonGetSuspenseQueryKey = ReturnType<typeof openapiApiOpenapiJsonGetSuspenseQueryKey>

export function openapiApiOpenapiJsonGetSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = openapiApiOpenapiJsonGetSuspenseQueryKey()
  return queryOptions<OpenapiApiOpenapiJsonGetQueryResponse, ResponseErrorConfig<Error>, OpenapiApiOpenapiJsonGetQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return openapiApiOpenapiJsonGet(config)
   },
  })
}

/**
 * @summary Openapi
 * {@link /api/openapi.json}
 */
export function useOpenapiApiOpenapiJsonGetSuspense<TData = OpenapiApiOpenapiJsonGetQueryResponse, TQueryKey extends QueryKey = OpenapiApiOpenapiJsonGetSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<OpenapiApiOpenapiJsonGetQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? openapiApiOpenapiJsonGetSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...openapiApiOpenapiJsonGetSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}