/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubjectsSubjectIDQueryResponse, SubjectsSubjectIDPathParams, SubjectsSubjectID422 } from "../../types/Subjects/SubjectsSubjectID.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subjectsSubjectIDQueryResponseSchema } from "../../zod/SubjectsSchemas/subjectsSubjectIDSchema.ts";

function getSubjectsSubjectIDUrl({ subjectID }: { subjectID: SubjectsSubjectIDPathParams["subjectID"] }) {
  const res = { method: 'GET', url: `/api/subjects/${subjectID}` as const }  
  return res
}

/**
 * @description так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить предмет по его subjectID
 * {@link /api/subjects/:subjectID}
 */
export async function subjectsSubjectID({ subjectID }: { subjectID: SubjectsSubjectIDPathParams["subjectID"] }, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SubjectsSubjectIDQueryResponse, ResponseErrorConfig<SubjectsSubjectID422>, unknown>({ method : "GET", url : getSubjectsSubjectIDUrl({ subjectID }).url.toString(), ... requestConfig })  
  return subjectsSubjectIDQueryResponseSchema.parse(res.data)
}