/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { subjects } from "./subjects.ts";
import { subjectsSubjectID } from "./subjectsSubjectID.ts";

export function SubjectsService() {
  return { subjects, subjectsSubjectID }
}