/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { SubjectsQueryResponse } from "../../types/Subjects/Subjects.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import { subjectsQueryResponseSchema } from "../../zod/SubjectsSchemas/subjectsSchema.ts";

function getSubjectsUrl() {
  const res = { method: 'GET', url: `/api/subjects` as const }  
  return res
}

/**
 * @description так же необходимо передавать в заголовке **токен** пользователя
 * @summary Получить список всех предметов (Информатика, Математика)
 * {@link /api/subjects}
 */
export async function subjects(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<SubjectsQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : getSubjectsUrl().url.toString(), ... requestConfig })  
  return subjectsQueryResponseSchema.parse(res.data)
}