/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSubtasksAssignSubtasksQueryResponse, StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks422 } from "../../types/StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { studentsSubtasksAssignSubtasks } from "../../services/StudentsSubtasksService/studentsSubtasksAssignSubtasks.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const studentsSubtasksAssignSubtasksQueryKey = (params: StudentsSubtasksAssignSubtasksQueryParams) => [{ url: '/api/students_subtasks/assign_subtasks' }, ...(params ? [params] : [])] as const

export type StudentsSubtasksAssignSubtasksQueryKey = ReturnType<typeof studentsSubtasksAssignSubtasksQueryKey>

export function studentsSubtasksAssignSubtasksQueryOptions(params: StudentsSubtasksAssignSubtasksQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSubtasksAssignSubtasksQueryKey(params)
  return queryOptions<StudentsSubtasksAssignSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>, StudentsSubtasksAssignSubtasksQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsSubtasksAssignSubtasks(params, config)
   },
  })
}

/**
 * @description Для выбранного студента с (student_id)  назначиться задача сsubtask_id со статусом 'не начата'
 * @summary назначение задач студенту
 * {@link /api/students_subtasks/assign_subtasks}
 */
export function useStudentsSubtasksAssignSubtasks<TData = StudentsSubtasksAssignSubtasksQueryResponse, TQueryData = StudentsSubtasksAssignSubtasksQueryResponse, TQueryKey extends QueryKey = StudentsSubtasksAssignSubtasksQueryKey>(params: StudentsSubtasksAssignSubtasksQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<StudentsSubtasksAssignSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSubtasksAssignSubtasksQueryKey(params)

  const query = useQuery({
   ...studentsSubtasksAssignSubtasksQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}