/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSubtasksQueryResponse, StudentsSubtasksQueryParams, StudentsSubtasks422 } from "../../types/StudentsSubtasks/StudentsSubtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { studentsSubtasks } from "../../services/StudentsSubtasksService/studentsSubtasks.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const studentsSubtasksQueryKey = (params?: StudentsSubtasksQueryParams) => [{ url: '/api/students_subtasks' }, ...(params ? [params] : [])] as const

export type StudentsSubtasksQueryKey = ReturnType<typeof studentsSubtasksQueryKey>

export function studentsSubtasksQueryOptions(params?: StudentsSubtasksQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSubtasksQueryKey(params)
  return queryOptions<StudentsSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasks422>, StudentsSubtasksQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsSubtasks(params, config)
   },
  })
}

/**
 * @description В качестве фильтров передаются параметры                                                `StudentTaskID` - по Номеру задачи Студента                                              `StudentID` - по id студента                                            `SubTaskID` - по id задачи                                              `TaskID` - по id категории                                              `SubjectID` - по id предмета                                              `VariantID` - по id варианта                                              `CompletionStatus` - по статусу выполнения                                               `Search` - Поиск по ключевому слову (логин, описание и т.п.)                                              `SortColumn1` - Выбор колонки для сортировки 1 уровень                                              `SortColumn2` - Выбор колонки для сортировки 2 уровень                                              `SortDirection1` - Сортировка (по возрастанию ASC ) DESC -по убыванию                                              `SortDirection2`	NVARCHAR(4)		= 'ASC'                                                `Offset` - с какой строки начинать выводить                                              `Limit` - количество выведенных строк (По умолчанию: 500)
 * @summary ГЛАВНЫЙ РОУТ с получением списка задач студента по фильтрам
 * {@link /api/students_subtasks}
 */
export function useStudentsSubtasks<TData = StudentsSubtasksQueryResponse, TQueryData = StudentsSubtasksQueryResponse, TQueryKey extends QueryKey = StudentsSubtasksQueryKey>(params?: StudentsSubtasksQueryParams, options: 
{
  query?: Partial<QueryObserverOptions<StudentsSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasks422>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSubtasksQueryKey(params)

  const query = useQuery({
   ...studentsSubtasksQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<StudentsSubtasks422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}