/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { StudentsSubtasksAssignSubtasksQueryResponse, StudentsSubtasksAssignSubtasksQueryParams, StudentsSubtasksAssignSubtasks422 } from "../../types/StudentsSubtasks/StudentsSubtasksAssignSubtasks.ts";
import type { RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { studentsSubtasksAssignSubtasks } from "../../services/StudentsSubtasksService/studentsSubtasksAssignSubtasks.ts";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const studentsSubtasksAssignSubtasksSuspenseQueryKey = (params: StudentsSubtasksAssignSubtasksQueryParams) => [{ url: '/api/students_subtasks/assign_subtasks' }, ...(params ? [params] : [])] as const

export type StudentsSubtasksAssignSubtasksSuspenseQueryKey = ReturnType<typeof studentsSubtasksAssignSubtasksSuspenseQueryKey>

export function studentsSubtasksAssignSubtasksSuspenseQueryOptions(params: StudentsSubtasksAssignSubtasksQueryParams, config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = studentsSubtasksAssignSubtasksSuspenseQueryKey(params)
  return queryOptions<StudentsSubtasksAssignSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>, StudentsSubtasksAssignSubtasksQueryResponse, typeof queryKey>({
   enabled: !!(params),
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return studentsSubtasksAssignSubtasks(params, config)
   },
  })
}

/**
 * @description Для выбранного студента с (student_id)  назначиться задача сsubtask_id со статусом 'не начата'
 * @summary назначение задач студенту
 * {@link /api/students_subtasks/assign_subtasks}
 */
export function useStudentsSubtasksAssignSubtasksSuspense<TData = StudentsSubtasksAssignSubtasksQueryResponse, TQueryKey extends QueryKey = StudentsSubtasksAssignSubtasksSuspenseQueryKey>(params: StudentsSubtasksAssignSubtasksQueryParams, options: 
{
  query?: Partial<UseSuspenseQueryOptions<StudentsSubtasksAssignSubtasksQueryResponse, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? studentsSubtasksAssignSubtasksSuspenseQueryKey(params)

  const query = useSuspenseQuery({
   ...studentsSubtasksAssignSubtasksSuspenseQueryOptions(params, config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<StudentsSubtasksAssignSubtasks422>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}