/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


/**
 * @description Successful Response
*/
export type HealthCheckApiHealthGet200 = unknown;

export type HealthCheckApiHealthGetQueryResponse = HealthCheckApiHealthGet200;

export type HealthCheckApiHealthGetQuery = {
    Response: HealthCheckApiHealthGet200;
    Errors: any;
};